import type { GlobalConfig, Field } from 'payload'
import { moduleAccess } from '@/access'

// Helper: field màu với ColorPickerField custom component
const colorField = (name: string, label: string, defaultValue?: string, opts?: Record<string, unknown>): Field => ({
  name,
  label,
  type: 'text',
  ...(defaultValue ? { defaultValue } : {}),
  admin: {
    components: {
      Field: '/src/components/admin/ColorPickerField#default',
    },
    ...(opts?.admin as Record<string, unknown> || {}),
  },
  ...(opts || {}),
} as Field)


const defaultQuickTopics = [
  { label: 'Lịch khám', value: 'Xem lịch khám bác sĩ' },
  { label: 'Đặt khám', value: 'Tôi muốn đặt lịch khám' },
  { label: 'Bảng giá', value: 'Tra cứu bảng giá dịch vụ' },
  { label: 'Tiêm ngừa', value: 'Thông tin tiêm ngừa' },
]

const defaultAssistantAnswers = [
  { question: 'Lịch khám bác sĩ', keywords: 'lịch khám, bác sĩ, khoa khám', answer: 'Bạn có thể xem lịch khám theo ngày, theo tuần hoặc lịch đính kèm tại đây.', linkLabel: 'Xem lịch khám', linkUrl: '/lich-kham' },
  { question: 'Đặt lịch khám', keywords: 'đặt khám, đặt lịch, Medpro', answer: 'Bạn có thể đặt lịch khám trực tuyến qua Medpro.', linkLabel: 'Đặt khám qua Medpro', linkUrl: '{{MEDPRO_URL}}', openNewTab: true },
  { question: 'Bảng giá dịch vụ', keywords: 'bảng giá, chi phí, giá dịch vụ', answer: 'Bảng giá BHYT và giá dịch vụ được bệnh viện cập nhật tại đây.', linkLabel: 'Tra cứu bảng giá', linkUrl: '/bang-gia' },
  { question: 'Thông tin tiêm ngừa', keywords: 'tiêm ngừa, tiêm chủng, vắc xin, vaccine', answer: 'Xem thông báo lịch tiêm, các đợt tiêm và danh mục vắc xin.', linkLabel: 'Xem thông tin tiêm ngừa', linkUrl: '/tiem-chung' },
  { question: 'Hướng dẫn khám BHYT', keywords: 'BHYT, bảo hiểm y tế, khám bảo hiểm', answer: 'Thông tin khám BHYT và hướng dẫn cần thiết được đăng tại đây.', linkLabel: 'Xem hướng dẫn BHYT', linkUrl: '/trang/kham-bhyt' },
  { question: 'Thông báo bệnh viện', keywords: 'thông báo, thông tin mới', answer: 'Xem toàn bộ thông báo mới và thông báo quan trọng của bệnh viện.', linkLabel: 'Xem thông báo', linkUrl: '/thong-bao' },
  { question: 'Tin tức và hoạt động', keywords: 'tin tức, hoạt động bệnh viện', answer: 'Tin tức và hoạt động mới nhất của bệnh viện được cập nhật tại đây.', linkLabel: 'Xem tin tức', linkUrl: '/tin-tuc' },
  { question: 'Liên hệ và hotline', keywords: 'địa chỉ, liên hệ, hotline, số điện thoại, cấp cứu', answer: 'Bạn có thể gọi bệnh viện theo số {{HOTLINE}} hoặc mở trang Liên hệ.', linkLabel: 'Gọi bệnh viện', linkUrl: 'tel:{{HOTLINE}}' },
]

export const SiteSettings: GlobalConfig = {
  slug: 'site-settings',
  label: 'Header & Nhận diện',
  admin: { group: '🌐 Trang chủ & Giao diện Website' },
  access: { read: () => true, update: moduleAccess('site-settings', 'edit') },
  versions: { max: 20 },
  hooks: {
    afterRead: [({ doc }) => ({
      ...doc,
      websiteAssistant: {
        enabled: true,
        backToTopEnabled: true,
        assistantName: 'Trợ lý Thới Lai',
        statusText: 'Đang trực tuyến',
        greeting: 'Xin chào! Tôi có thể giúp bạn tra cứu lịch khám, bảng giá, tiêm ngừa và thông tin bệnh viện.',
        inputPlaceholder: 'Nhập nội dung cần hỏi…',
        noticeText: 'Thông tin chỉ mang tính tham khảo. Trường hợp cấp cứu, vui lòng gọi bệnh viện ngay.',
        fallbackResponse: 'Tôi chưa hiểu rõ câu hỏi. Bạn hãy chọn một mục gợi ý hoặc liên hệ trực tiếp với bệnh viện để được hỗ trợ.',
        fallbackLinkLabel: 'Liên hệ bệnh viện',
        fallbackLinkUrl: '/lien-he',
        primaryColor: '#0878D1',
        ...(doc?.websiteAssistant || {}),
        quickTopics: Array.isArray(doc?.websiteAssistant?.quickTopics) ? doc.websiteAssistant.quickTopics : defaultQuickTopics,
        customAnswers: Array.isArray(doc?.websiteAssistant?.customAnswers) ? doc.websiteAssistant.customAnswers : defaultAssistantAnswers,
      },
    })],
  },
  fields: [
    { name: 'hospitalName', label: 'Tên bệnh viện', type: 'text', defaultValue: 'Bệnh viện Đa khoa Khu vực Thới Lai', required: true },
    { name: 'logo', label: 'Logo bệnh viện', type: 'upload', relationTo: 'media', admin: { description: 'Logo chính dùng đồng bộ tại Header và Footer. Website hiển thị trực tiếp file gốc, không dùng ảnh thumbnail. Nên dùng PNG nền trong suốt từ 800×800 px trở lên để chữ và chi tiết logo rõ nét.' } },
    { name: 'headerSlogan', label: 'Slogan dưới tên bệnh viện', type: 'text', defaultValue: 'Điều trị bằng trái tim - Chăm sóc bằng tấm lòng' },
    { name: 'headerShowSlogan', label: 'Hiển thị slogan', type: 'checkbox', defaultValue: true },
    { name: 'headerShowUtilityBar', label: 'Hiển thị thanh ngày giờ / mạng xã hội', type: 'checkbox', defaultValue: true },
    { name: 'headerShowSearch', label: 'Hiển thị ô tìm kiếm', type: 'checkbox', defaultValue: true },
    { name: 'headerShowContactCards', label: 'Hiển thị các ô liên hệ nhanh', type: 'checkbox', defaultValue: true },
    { name: 'headerStickyMenu', label: 'Menu bám đầu trang', type: 'checkbox', defaultValue: true },
    {
      name: 'headerUtilityAppearance',
      label: 'Thanh ngày giờ phía trên',
      type: 'group',
      fields: [
        { name: 'timePrefix', label: 'Chữ trước thời gian', type: 'text', defaultValue: '' },
        { name: 'showCalendarIcon', label: 'Hiển thị icon lịch', type: 'checkbox', defaultValue: true },
        colorField('background', 'Nền thanh trên', '#064a83'),
        colorField('timeColor', 'Màu chữ thời gian', '#FFFFFF'),
        { name: 'timeFontSize', label: 'Cỡ chữ thời gian (px)', type: 'number', min: 10, max: 22, defaultValue: 13 },
        { name: 'timeFontWeight', label: 'Độ đậm chữ thời gian', type: 'text', defaultValue: '700', admin: { placeholder: '600, 700, 800...' } },
      ],
    },
    {
      name: 'headerBrandAppearance',
      label: 'Nhận diện: Logo, tên bệnh viện, slogan và nền Header',
      type: 'group',
      admin: { description: 'Logo được chọn ở trường Logo bệnh viện phía trên. Tại đây chỉnh hiển thị, kích thước, màu chữ, căn lề, bảng màu, font chữ, hiệu ứng nổi bật và ảnh/màu nền của vùng nhận diện.' },
      fields: [
        {
          name: 'colorScheme',
          label: '🎨 Bảng màu chủ đạo (Color Scheme)',
          type: 'select',
          enumName: 'brand_color_scheme',
          defaultValue: 'custom',
          admin: {
            description: 'Chọn bảng màu phối hợp sẵn cho Tên đơn vị + Slogan. Chọn "Tuỳ chọn" để dùng màu tự chọn bên dưới.',
          },
          options: [
            { label: '🏥 Y tế xanh dương (Mặc định)', value: 'custom' },
            { label: '🌊 Navy & Vàng sang trọng', value: 'navy-gold' },
            { label: '🌿 Xanh lá y tế & Trắng tinh khiết', value: 'green-white' },
            { label: '🌙 Tối premium (Dark Mode)', value: 'dark-premium' },
            { label: '❤️ Đỏ y tế & Trắng', value: 'red-white' },
            { label: '☀️ Xanh trời & Cam ấm áp', value: 'sky-orange' },
          ],
        },
        {
          name: 'logoSize',
          label: 'Kích thước logo (px)',
          type: 'number',
          defaultValue: 66,
          min: 42,
          max: 140,
        },
        {
          name: 'titleFontSize',
          label: 'Cỡ chữ dòng “BỆNH VIỆN ĐA KHOA” (px)',
          type: 'number',
          defaultValue: 17,
          min: 12,
          max: 28,
        },
        {
          name: 'subtitleFontSize',
          label: 'Cỡ chữ dòng “KHU VỰC THỚI LAI” (px)',
          type: 'number',
          defaultValue: 13,
          min: 9,
          max: 22,
        },
        {
          name: 'nameFontFamily',
          label: '🔤 Kiểu chữ Tên đơn vị',
          type: 'select',
          enumName: 'brand_name_font',
          defaultValue: 'inherit',
          admin: { description: 'Font chữ riêng cho dòng tên bệnh viện. "Theo website" = dùng font hệ thống chung.' },
          options: [
            { label: 'Theo font hệ thống website', value: 'inherit' },
            { label: '"Be Vietnam Pro" – Hiện đại, chuẩn y tế Việt', value: '"Be Vietnam Pro", sans-serif' },
            { label: '"Montserrat" – Sang trọng, quốc tế', value: '"Montserrat", sans-serif' },
            { label: '"Roboto" – Khoa học, sạch sẽ', value: '"Roboto", sans-serif' },
            { label: '"Nunito" – Mềm mại, thân thiện', value: '"Nunito", sans-serif' },
            { label: '"Inter" – Tối giản, chuyên nghiệp', value: '"Inter", sans-serif' },
          ],
        },
        {
          name: 'nameFontWeight',
          label: '💪 Độ đậm chữ Tên đơn vị',
          type: 'select',
          enumName: 'brand_name_weight',
          defaultValue: '800',
          options: [
            { label: 'Bình thường (400)', value: '400' },
            { label: 'Vừa (600)', value: '600' },
            { label: 'Đậm (700)', value: '700' },
            { label: 'Rất đậm (800) – Khuyên dùng', value: '800' },
            { label: 'Siêu đậm (900)', value: '900' },
          ],
        },
        {
          name: 'nameTextEffect',
          label: '✨ Hiệu ứng nổi bật Tên đơn vị',
          type: 'select',
          enumName: 'brand_name_effect',
          defaultValue: 'none',
          admin: { description: 'Chọn hiệu ứng để tên bệnh viện nổi bật hơn trên Header.' },
          options: [
            { label: 'Bình thường (không hiệu ứng)', value: 'none' },
            { label: '🌟 Chữ gradient màu (Gradient Text)', value: 'gradient-text' },
            { label: '🔦 Đổ bóng nhẹ (Text Shadow)', value: 'shadow' },
            { label: '📌 Viền nhấn bên trái (Left Accent Border)', value: 'border-accent' },
            { label: '〰️ Gạch chân màu nhấn (Underline Accent)', value: 'underline-accent' },
            { label: '🔳 Nền nổi bật (Highlight Background)', value: 'highlight-bg' },
          ],
        },
        colorField('headerBackgroundColor', 'Màu nền thanh đầu trang', '#FFFFFF', { admin: { description: 'Nhập mã màu, ví dụ: #FFFFFF' } }),
        colorField('logoBackgroundColor', 'Màu nền khung logo', '#FFFFFF', { admin: { description: 'Nhập mã màu, ví dụ: #FFFFFF' } }),
        colorField('titleColor', 'Màu chữ dòng Bệnh viện ĐA KHOA', '#143653', { admin: { description: 'Nhập mã màu, ví dụ: #143653' } }),
        colorField('subtitleColor', 'Màu chữ dòng KHU VỰC THỚI LAI', '#0878D1', { admin: { description: 'Nhập mã màu, ví dụ: #0878D1' } }),
        {
          name: 'sloganAlign',
          label: 'Căn lề khẩu hiệu / Slogan',
          type: 'select',
          enumName: 'header_slogan_align',
          defaultValue: 'center',
          options: [
            { label: 'Căn giữa (khuyên dùng)', value: 'center' },
            { label: 'Căn trái', value: 'left' },
            { label: 'Căn phải', value: 'right' },
          ],
          admin: { description: 'Vị trí căn của câu slogan so với tên đơn vị.' },
        },
        colorField('sloganColor', 'Màu chữ slogan', '#0a9b50', { admin: { description: 'Mặc định màu xanh lá #0a9b50 hoặc xanh dương #0878D1' } }),
        { name: 'sloganFontSize', label: 'Cỡ chữ slogan (px)', type: 'number', min: 10, max: 24, defaultValue: 13 },
        {
          name: 'sloganFontWeight',
          label: '💪 Độ đậm chữ Slogan',
          type: 'select',
          enumName: 'brand_slogan_weight',
          defaultValue: '500',
          options: [
            { label: 'Mảnh (400)', value: '400' },
            { label: 'Vừa (500) – Khuyên dùng cho slogan', value: '500' },
            { label: 'Vừa đậm (600)', value: '600' },
            { label: 'Đậm (700)', value: '700' },
            { label: 'Rất đậm (800)', value: '800' },
          ],
        },
        {
          name: 'sloganItalic',
          label: '📝 In nghiêng slogan (Italic)',
          type: 'checkbox',
          defaultValue: false,
          admin: { description: 'Bật để slogan hiển thị nghiêng – phong cách khẩu hiệu truyền thống.' },
        },
        {
          name: 'sloganTextEffect',
          label: '✨ Hiệu ứng nổi bật Slogan',
          type: 'select',
          enumName: 'brand_slogan_effect',
          defaultValue: 'none',
          admin: { description: 'Chọn hiệu ứng để câu slogan nổi bật hơn.' },
          options: [
            { label: 'Bình thường (không hiệu ứng)', value: 'none' },
            { label: '🌟 Chữ gradient màu (Gradient Text)', value: 'gradient-text' },
            { label: '🔦 Đổ bóng nhẹ (Text Shadow)', value: 'shadow' },
            { label: '〰️ Gạch chân trang trí (Decorative Underline)', value: 'decorative-underline' },
            { label: '💎 Icon hoa văn hai bên (★ Slogan ★)', value: 'star-wrap' },
          ],
        },
        { name: 'showLogo', label: 'Hiển thị logo', type: 'checkbox', defaultValue: true },
        { name: 'showHospitalName', label: 'Hiển thị tên bệnh viện', type: 'checkbox', defaultValue: true },
        { name: 'backgroundImage', label: 'Ảnh nền khu vực nhận diện', type: 'upload', relationTo: 'media', admin: { description: 'Có thể chọn ảnh đã tải lên. Để trống sẽ dùng màu nền.' } },
        { name: 'backgroundSize', label: 'Kiểu phủ ảnh nền', type: 'text', defaultValue: 'cover', admin: { placeholder: 'cover hoặc contain' } },
        { name: 'backgroundPosition', label: 'Vị trí ảnh nền', type: 'text', defaultValue: 'center center', admin: { placeholder: 'center center' } },
        { name: 'backgroundOverlay', label: 'Lớp phủ trên ảnh nền', type: 'text', defaultValue: 'rgba(255,255,255,0.88)', admin: { placeholder: 'rgba(255,255,255,0.88)' } },
        { name: 'minHeight', label: 'Chiều cao tối thiểu khối nhận diện (px)', type: 'number', min: 70, max: 260, defaultValue: 110 },
      ],
    },
    {
      name: 'headerMenuAppearance',
      label: '🎨 Tùy chỉnh Menu chính & Menu thả xuống (Dropdown)',
      type: 'group',
      admin: {
        description: 'Tùy chỉnh toàn diện kích thước chữ, khoảng cách, căn lề, màu sắc thanh menu, màu menu con (dropdown), hiệu ứng chuyển động animation và font chữ.',
      },
      fields: [
        {
          type: 'collapsible',
          label: '🔤 Kích thước chữ & Font chữ Menu',
          admin: { initCollapsed: false },
          fields: [
            {
              type: 'row',
              fields: [
                {
                  name: 'fontSize',
                  label: 'Cỡ chữ menu chính (px)',
                  type: 'number',
                  min: 10,
                  max: 24,
                  defaultValue: 14,
                  admin: { width: '33%', description: 'Khuyên dùng 13 - 15px để chữ to, rõ nét và dễ nhìn.' },
                },
                {
                  name: 'fontWeight',
                  label: 'Độ đậm chữ menu chính',
                  type: 'select',
                  enumName: 'menu_font_weight',
                  dbName: 'menu_font_weight',
                  defaultValue: '700',
                  admin: { width: '33%' },
                  options: [
                    { label: 'Bình thường (400)', value: '400' },
                    { label: 'Vừa (600)', value: '600' },
                    { label: 'Đậm (700)', value: '700' },
                    { label: 'Rất đậm (800)', value: '800' },
                    { label: 'Siêu đậm (900)', value: '900' },
                  ],
                },
                {
                  name: 'textTransform',
                  label: 'Kiểu viết hoa / thường',
                  type: 'select',
                  enumName: 'menu_text_transform',
                  dbName: 'menu_text_transform',
                  defaultValue: 'uppercase',
                  admin: { width: '34%' },
                  options: [
                    { label: 'IN HOA TOÀN BỘ (UPPERCASE)', value: 'uppercase' },
                    { label: 'Chữ tiêu chuẩn bình thường (Normal)', value: 'none' },
                    { label: 'Viết Hoa Chữ Cái Đầu (Capitalize)', value: 'capitalize' },
                  ],
                },
              ],
            },
            {
              type: 'row',
              fields: [
                {
                  name: 'fontFamily',
                  label: 'Font chữ menu',
                  type: 'select',
                  enumName: 'menu_font_family',
                  dbName: 'menu_font_family',
                  defaultValue: 'inherit',
                  admin: { width: '50%' },
                  options: [
                    { label: 'Theo font hệ thống website', value: 'inherit' },
                    { label: 'Arial, sans-serif', value: 'Arial, Helvetica, sans-serif' },
                    { label: '"Segoe UI", Roboto, sans-serif', value: '"Segoe UI", Roboto, sans-serif' },
                    { label: '"Montserrat", sans-serif', value: '"Montserrat", sans-serif' },
                    { label: '"Roboto", sans-serif', value: '"Roboto", sans-serif' },
                    { label: '"Be Vietnam Pro", sans-serif', value: '"Be Vietnam Pro", sans-serif' },
                  ],
                },
                {
                  name: 'letterSpacing',
                  label: 'Khoảng cách giữa các ký tự chữ (px)',
                  type: 'number',
                  min: -2,
                  max: 5,
                  defaultValue: 0,
                  admin: { width: '50%', description: '0 là chuẩn, 0.5 - 1px tạo độ thoáng' },
                },
              ],
            },
          ],
        },
        {
          type: 'collapsible',
          label: '📐 Chiều cao, Vị trí & Khoảng cách giữa các Menu',
          admin: { initCollapsed: false },
          fields: [
            {
              type: 'row',
              fields: [
                {
                  name: 'height',
                  label: 'Chiều cao thanh menu (px)',
                  type: 'number',
                  min: 44,
                  max: 80,
                  defaultValue: 56,
                  admin: { width: '33%', description: 'Mặc định 56px' },
                },
                {
                  name: 'justifyContent',
                  label: 'Vị trí dàn hàng menu',
                  type: 'select',
                  enumName: 'menu_justify_content',
                  dbName: 'menu_justify_content',
                  defaultValue: 'space-between',
                  admin: { width: '33%' },
                  options: [
                    { label: 'Dàn đều toàn hàng (Space Between)', value: 'space-between' },
                    { label: 'Căn giữa (Center)', value: 'center' },
                    { label: 'Căn trái (Left / Flex-start)', value: 'flex-start' },
                    { label: 'Căn phải (Right / Flex-end)', value: 'flex-end' },
                    { label: 'Dàn đều có khoảng đệm (Space Around)', value: 'space-around' },
                  ],
                },
                {
                  name: 'itemSpacing',
                  label: 'Khoảng cách đệm giữa các mục (px)',
                  type: 'number',
                  min: 0,
                  max: 40,
                  defaultValue: 8,
                  admin: { width: '34%', description: 'Khoảng trống padding hai bên mỗi mục menu.' },
                },
              ],
            },
            {
              type: 'row',
              fields: [
                {
                  name: 'borderRadius',
                  label: 'Bo tròn góc thanh menu (px)',
                  type: 'number',
                  min: 0,
                  max: 30,
                  defaultValue: 0,
                  admin: { width: '50%' },
                },
                {
                  name: 'itemBorderRadius',
                  label: 'Bo tròn nền khi hover vào mục menu (px)',
                  type: 'number',
                  min: 0,
                  max: 20,
                  defaultValue: 6,
                  admin: { width: '50%' },
                },
              ],
            },
          ],
        },
        {
          type: 'collapsible',
          label: '🎨 Màu sắc Thanh Menu Chính',
          admin: { initCollapsed: false },
          fields: [
            {
              type: 'row',
              fields: [
                colorField('background', 'Màu nền thanh menu', '#075db8'),
                colorField('gradientEnd', 'Màu kết thúc gradient (nếu có)', '#006bc7'),
                colorField('textColor', 'Màu chữ menu', '#FFFFFF'),
              ],
            },
            {
              type: 'row',
              fields: [
                colorField('hoverTextColor', 'Màu chữ khi di chuột (Hover)', '#FFE272'),
                colorField('hoverBackground', 'Màu nền khi di chuột (Hover)', 'rgba(255,255,255,0.1)'),
                colorField('activeIndicatorColor', 'Màu đường gạch chân hiệu ứng', '#FFD24D'),
              ],
            },
          ],
        },
        {
          type: 'collapsible',
          label: '📂 Tùy chỉnh Menu thả xuống (Dropdown)',
          admin: { initCollapsed: false },
          fields: [
            {
              type: 'row',
              fields: [
                {
                  name: 'dropdownWidth',
                  label: 'Chiều rộng hộp menu thả xuống (px)',
                  type: 'number',
                  min: 180,
                  max: 450,
                  defaultValue: 250,
                  admin: { width: '33%' },
                },
                {
                  name: 'dropdownFontSize',
                  label: 'Cỡ chữ menu con (px)',
                  type: 'number',
                  min: 11,
                  max: 20,
                  defaultValue: 14,
                  admin: { width: '33%' },
                },
                {
                  name: 'dropdownBorderRadius',
                  label: 'Bo tròn góc hộp menu thả xuống (px)',
                  type: 'number',
                  min: 0,
                  max: 24,
                  defaultValue: 12,
                  admin: { width: '34%' },
                },
              ],
            },
            {
              type: 'row',
              fields: [
                colorField('dropdownBackground', 'Màu nền hộp menu con', '#FFFFFF'),
                colorField('dropdownTextColor', 'Màu chữ menu con', '#1e3a5f'),
                colorField('dropdownBorderColor', 'Màu đường viền hộp', '#e2e8f0'),
              ],
            },
            {
              type: 'row',
              fields: [
                colorField('dropdownHoverBackground', 'Màu nền menu con khi hover', '#f0f7ff'),
                colorField('dropdownHoverTextColor', 'Màu chữ menu con khi hover', '#075db8'),
                colorField('dropdownArrowColor', 'Màu mũi tên menu con (›)', '#94a3b8'),
              ],
            },
            {
              type: 'row',
              fields: [
                {
                  name: 'animationStyle',
                  label: 'Hiệu ứng Animation khi mở Menu con',
                  type: 'select',
                  enumName: 'menu_anim_style',
                  dbName: 'menu_anim_style',
                  defaultValue: 'slide-down',
                  admin: { width: '50%' },
                  options: [
                    { label: 'Trượt nhẹ từ trên xuống (Slide Down - Mượt mà)', value: 'slide-down' },
                    { label: 'Phóng to nhẹ (Zoom In)', value: 'zoom-in' },
                    { label: 'Mờ dần vào (Fade In)', value: 'fade-in' },
                    { label: 'Lật 3D (Flip In)', value: 'flip-in' },
                  ],
                },
                {
                  name: 'animationSpeed',
                  label: 'Tốc độ hiệu ứng Animation',
                  type: 'select',
                  enumName: 'menu_anim_speed',
                  dbName: 'menu_anim_speed',
                  defaultValue: '0.22s',
                  admin: { width: '50%' },
                  options: [
                    { label: 'Nhanh (0.15 giây)', value: '0.15s' },
                    { label: 'Tiêu chuẩn (0.22 giây)', value: '0.22s' },
                    { label: 'Êm dịu (0.35 giây)', value: '0.35s' },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      name: 'headerContactCards',
      label: 'Cấp cứu / Đặt lịch khám / Liên hệ nhanh Header',
      type: 'array',
      maxRows: 6,
      labels: { singular: 'Ô liên hệ / Nút Header', plural: 'Các ô liên hệ / Nút Header' },
      admin: {
        description: 'Tùy chỉnh toàn diện 2 ô "CẤP CỨU 24/7" và "ĐẶT LỊCH KHÁM" hoặc thêm các ô mới. Bạn có thể đổi đường link, đổi icon, màu sắc chữ, màu nền, font chữ, kích cỡ chữ và kích thước ô.',
        initCollapsed: false,
      },
      fields: [
        {
          type: 'row',
          fields: [
            { name: 'visible', label: 'Hiển thị', type: 'checkbox', defaultValue: true, admin: { width: '20%' } },
            { name: 'title', label: 'Dòng tiêu đề nhỏ', type: 'text', required: true, admin: { width: '40%', placeholder: 'VD: CẤP CỨU 24/7 hoặc ĐẶT LỊCH KHÁM' } },
            { name: 'text', label: 'Dòng nội dung chính', type: 'text', required: true, admin: { width: '40%', placeholder: 'VD: 02923686115 hoặc ĐẶT LỊCH NGAY' } },
          ],
        },
        {
          type: 'row',
          fields: [
            { name: 'href', label: 'Đường dẫn liên kết (Link)', type: 'text', admin: { width: '50%', placeholder: 'VD: tel:02923686115 hoặc /lich-kham hoặc https://medpro.vn' } },
            { name: 'extraText', label: 'Dòng chữ ghi chú phụ (nếu có)', type: 'text', admin: { width: '50%', placeholder: 'VD: Trực liên tục, Tư vấn miễn phí...' } },
          ],
        },
        {
          type: 'row',
          fields: [
            {
              name: 'iconType',
              label: 'Biểu tượng (Icon)',
              type: 'select',
              defaultValue: 'emergency',
              admin: { width: '40%' },
              options: [
                { label: '➕ Dấu thập Cấp cứu (Emergency Cross)', value: 'emergency' },
                { label: '📅 Lịch khám / Đồng hồ (Calendar)', value: 'calendar' },
                { label: '📞 Điện thoại (Phone)', value: 'phone' },
                { label: '🎧 Tổng đài / Tai nghe (Headset)', value: 'headset' },
                { label: '❤️ Trái tim y tế (Heart)', value: 'heart' },
                { label: 'ℹ️ Thông tin hỗ trợ (Info)', value: 'info' },
                { label: '🖼️ Dùng ảnh icon riêng (Upload bên dưới)', value: 'custom' },
              ],
            },
            {
              name: 'customIcon',
              label: 'Ảnh icon tự tải lên (nếu chọn icon riêng)',
              type: 'upload',
              relationTo: 'media',
              admin: { width: '35%', description: 'Tải PNG, SVG hoặc chọn ảnh có sẵn.' },
            },
            {
              name: 'hasArrow',
              label: 'Hiện mũi tên hành động (→)',
              type: 'checkbox',
              defaultValue: false,
              admin: { width: '25%' },
            },
          ],
        },
        {
          type: 'collapsible',
          label: '🎨 Tùy chỉnh màu sắc & Hiệu ứng',
          admin: { initCollapsed: true },
          fields: [
            {
              type: 'row',
              fields: [
                colorField('titleColor', 'Màu chữ tiêu đề', '#273B4C'),
                colorField('textColor', 'Màu chữ nội dung', '#0756B4'),
                colorField('extraTextColor', 'Màu chữ phụ', '#557082'),
              ],
            },
            {
              type: 'row',
              fields: [
                colorField('background', 'Màu nền ô', '#FFFFFF'),
                colorField('borderColor', 'Màu đường viền ô', '#E1E7EC'),
              ],
            },
            {
              type: 'row',
              fields: [
                colorField('iconColor', 'Màu biểu tượng (Icon)', '#075EC2'),
                colorField('iconBackground', 'Màu nền tròn biểu tượng', '#EAF5FF'),
              ],
            },
          ],
        },
        {
          type: 'collapsible',
          label: '🔤 Tùy chỉnh Font chữ & Kích thước hiển thị',
          admin: { initCollapsed: true },
          fields: [
            {
              type: 'row',
              fields: [
                {
                  name: 'fontFamily',
                  label: 'Kiểu font chữ',
                  type: 'select',
                  defaultValue: 'inherit',
                  admin: { width: '50%' },
                  options: [
                    { label: 'Theo font hệ thống website', value: 'inherit' },
                    { label: 'Arial, sans-serif', value: 'Arial, Helvetica, sans-serif' },
                    { label: '"Segoe UI", Roboto, sans-serif', value: '"Segoe UI", Roboto, sans-serif' },
                    { label: '"Montserrat", sans-serif', value: '"Montserrat", sans-serif' },
                    { label: '"Roboto", sans-serif', value: '"Roboto", sans-serif' },
                    { label: '"Be Vietnam Pro", sans-serif', value: '"Be Vietnam Pro", sans-serif' },
                  ],
                },
                {
                  name: 'fontWeight',
                  label: 'Độ đậm nội dung chính',
                  type: 'select',
                  defaultValue: '800',
                  admin: { width: '50%' },
                  options: [
                    { label: 'Bình thường (400)', value: '400' },
                    { label: 'Vừa (600)', value: '600' },
                    { label: 'Đậm (700)', value: '700' },
                    { label: 'Rất đậm (800)', value: '800' },
                    { label: 'Siêu đậm (900)', value: '900' },
                  ],
                },
              ],
            },
            {
              type: 'row',
              fields: [
                { name: 'titleFontSize', label: 'Cỡ chữ tiêu đề (px)', type: 'number', min: 8, max: 30, defaultValue: 11, admin: { width: '33%' } },
                { name: 'textFontSize', label: 'Cỡ chữ nội dung chính (px)', type: 'number', min: 10, max: 40, defaultValue: 17, admin: { width: '33%' } },
                { name: 'iconSize', label: 'Kích cỡ icon (px)', type: 'number', min: 28, max: 64, defaultValue: 46, admin: { width: '34%' } },
              ],
            },
            {
              type: 'row',
              fields: [
                { name: 'minWidth', label: 'Chiều rộng tối thiểu ô (px)', type: 'number', min: 140, max: 400, defaultValue: 220, admin: { width: '50%' } },
                { name: 'borderRadius', label: 'Bo tròn góc ô (px)', type: 'number', min: 0, max: 50, defaultValue: 16, admin: { width: '50%' } },
              ],
            },
          ],
        },
      ],
    },
    {
      name: 'headerSocialLinks',
      label: 'Icon mạng xã hội dùng chung Header + Footer',
      type: 'array',
      maxRows: 8,
      labels: { singular: 'Mạng xã hội', plural: 'Mạng xã hội' },
      admin: { description: 'Đây là nơi quản lý DUY NHẤT Facebook, Zalo, YouTube, TikTok trên giao diện. Header và Footer dùng chung danh sách này. Có thể tải icon riêng cho từng mạng.' },
      fields: [
        { name: 'visible', label: 'Hiển thị', type: 'checkbox', defaultValue: true },
        { name: 'platform', label: 'Loại', type: 'text', required: true, admin: { placeholder: 'facebook, zalo, youtube, tiktok hoặc custom' } },
        { name: 'label', label: 'Tên hiển thị', type: 'text' },
        { name: 'url', label: 'Liên kết', type: 'text', required: true },
        { name: 'customIcon', label: 'Đổi icon / Tải icon riêng', type: 'upload', relationTo: 'media', admin: { description: 'Để trống sẽ dùng icon chuẩn tích hợp. Chọn ảnh để thay icon Facebook/Zalo/YouTube/TikTok bằng icon riêng.' } },
      ],
    },
    { name: 'tiktokUrl', label: 'Liên kết TikTok (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    {
      name: 'slogan',
      label: 'Nội dung chữ chạy / Khẩu hiệu',
      type: 'text',
      admin: {
        description: 'Nội dung này chạy ngang ngay dưới menu. Để trống sẽ dùng thông báo đặt khám mặc định của bệnh viện.',
        placeholder: 'Nhập thông báo cần chạy trên website…',
      },
    },
    {
      name: 'tickerAppearance',
      label: 'Cài đặt thanh chữ chạy',
      type: 'group',
      fields: [
        { name: 'enabled', label: 'Hiển thị thanh chữ chạy', type: 'checkbox', defaultValue: true },
        colorField('backgroundColor', 'Màu nền', '#FF9F2F', { admin: { description: 'Nhập mã màu, ví dụ: #FF9F2F' } }),
        colorField('textColor', 'Màu chữ', '#FFFFFF', { admin: { description: 'Nhập mã màu, ví dụ: #FFFFFF' } }),
        {
          name: 'fontSize',
          label: 'Kích thước chữ (px)',
          type: 'number',
          defaultValue: 13,
          min: 10,
          max: 24,
        },
        {
          name: 'duration',
          label: 'Thời gian chạy hết một vòng (giây)',
          type: 'number',
          defaultValue: 24,
          min: 8,
          max: 120,
          admin: { description: 'Số nhỏ chạy nhanh hơn; số lớn chạy chậm hơn.' },
        },
      ],
    },
    {
      name: 'headerBanner',
      label: 'Banner đầu trang (nằm trên menu)',
      type: 'upload',
      relationTo: 'media',
      admin: { description: 'Tải banner mới hoặc chọn lại banner đã có trong thư viện. Nếu chưa chọn, website dùng banner có sẵn trong hệ thống.' },
    },
    {
      name: 'headerBannerWidth',
      label: 'Chiều rộng banner đầu trang (px)',
      type: 'number',
      min: 600,
      max: 3000,
      defaultValue: 1300,
      admin: { description: 'Nên dùng 1300 px. Ảnh banner tải lên nên có đúng kích thước 1300 × 200 px.' },
    },
    {
      name: 'headerBannerHeight',
      label: 'Chiều cao banner đầu trang (px)',
      type: 'number',
      min: 80,
      max: 360,
      defaultValue: 200,
      admin: { description: 'Nên dùng 200 px để khớp banner chuẩn 1300 × 200 px.' },
    },
    { name: 'favicon', label: 'Biểu tượng trình duyệt', type: 'upload', relationTo: 'media', admin: { description: 'Tải mới hoặc chọn lại hình đã có trong Thư viện Tệp & Hình ảnh.' } },
    { name: 'hotline', label: 'Hotline bệnh viện', type: 'text' },
    { name: 'emergencyHotline', label: 'Hotline cấp cứu', type: 'text' },
    { name: 'email', label: 'Email', type: 'email' },
    { name: 'address', label: 'Địa chỉ', type: 'textarea' },
    { name: 'workingHours', label: 'Thời gian làm việc', type: 'text' },
    { name: 'medproUrl', label: 'Liên kết đặt khám Medpro', type: 'text' },
    { name: 'zaloUrl', label: 'Liên kết Zalo (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    { name: 'facebookUrl', label: 'Liên kết Facebook (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    { name: 'youtubeUrl', label: 'Liên kết YouTube (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    {
      name: 'googleMapsEmbed',
      label: 'Bản đồ Google Maps',
      type: 'textarea',
      admin: {
        description: 'Dán toàn bộ mã <iframe> hoặc URL nhúng Google Maps (URL có /embed hoặc output=embed). Để trống, website tự hiển thị bản đồ theo Địa chỉ ở trên.',
      },
    },
    { name: 'footerText', label: 'Nội dung chân trang', type: 'textarea' },
    {
      name: 'servicePricePage',
      label: 'Trang Bảng giá dịch vụ',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, thông báo lưu ý BHYT, ô tìm kiếm và số dịch vụ hiển thị trên mỗi trang.' },
      fields: [
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Bảng giá dịch vụ' },
        { name: 'description', label: 'Mô tả', type: 'textarea', defaultValue: 'Tra cứu giá BHYT và giá dịch vụ được cập nhật trực tiếp từ hệ thống quản trị.' },
        {
          name: 'showNoticeBanner',
          label: 'Bật thông báo / lưu ý bảng giá trên đầu trang',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'noticeTitle',
          label: 'Tiêu đề lưu ý bảng giá',
          type: 'text',
          defaultValue: 'Lưu ý về giá khám chữa bệnh BHYT và Viện phí',
        },
        {
          name: 'noticeContent',
          label: 'Nội dung lưu ý (Hỗ trợ Enter xuống dòng)',
          type: 'textarea',
          defaultValue: '• Bảng giá dịch vụ khám bệnh, chữa bệnh được thực hiện công khai theo đúng quy định hiện hành của Bộ Y tế.\n• Người bệnh có thẻ BHYT đúng tuyến hoặc thông tuyến được hưởng đầy đủ quyền lợi chi trả theo quy định.\n• Các dịch vụ kỹ thuật cao, dịch vụ theo yêu cầu được tư vấn rõ ràng trước khi thực hiện.',
        },
        {
          name: 'noticeAlign',
          label: 'Canh lề bảng lưu ý',
          type: 'select',
          dbName: 'sp_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        { name: 'searchPlaceholder', label: 'Chữ gợi ý trong ô tìm kiếm', type: 'text', defaultValue: 'Nhập tên, mã dịch vụ, nhóm hoặc ghi chú…' },
        { name: 'rowsPerPage', label: 'Số dòng hiển thị trên mỗi trang', type: 'select', defaultValue: '40', required: true, options: [
          { label: '40 dịch vụ / trang', value: '40' },
          { label: '50 dịch vụ / trang', value: '50' },
        ] },
        { name: 'searchNotes', label: 'Cho phép tìm trong cột Ghi chú', type: 'checkbox', defaultValue: true },
        { name: 'emptyText', label: 'Thông báo khi không có kết quả', type: 'text', defaultValue: 'Không tìm thấy dịch vụ phù hợp.' },
      ],
    },
    {
      name: 'vaccinationPage',
      label: 'Trang Tiêm chủng vắc xin',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, banner thông báo và lưu ý an toàn tiêm chủng trên trang /tiem-chung.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'TIÊM NGỪA AN TOÀN' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Thông tin tiêm ngừa' },
        { name: 'description', label: 'Mô tả', type: 'textarea', defaultValue: 'Theo dõi thông báo lịch tiêm, các đợt tiêm và danh mục vắc xin tại bệnh viện.' },
        {
          name: 'showNoticeBanner',
          label: 'Bật thông báo lưu ý tiêm chủng',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'noticeTitle',
          label: 'Tiêu đề lưu ý tiêm chủng',
          type: 'text',
          defaultValue: 'Quy trình và An toàn Tiêm chủng tại Bệnh viện',
        },
        {
          name: 'noticeContent',
          label: 'Nội dung lưu ý (Hỗ trợ Enter xuống dòng)',
          type: 'textarea',
          defaultValue: '• Người đến tiêm chủng được khám sàng lọc trước tiêm và tư vấn chỉ định vắc xin phù hợp.\n• Theo dõi sức khỏe ít nhất 30 phút sau tiêm tại phòng theo dõi của bệnh viện.\n• Vui lòng mang theo sổ tiêm chủng hoặc ứng dụng tiêm chủng điện tử khi đến tiêm.',
        },
        {
          name: 'noticeAlign',
          label: 'Canh lề bảng lưu ý',
          type: 'select',
          dbName: 'vc_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    {
      name: 'examinationFlowPage',
      label: 'Trang Quy trình khám bệnh',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả, thông báo lưu ý và cấu hình hiển thị trên trang /quy-trinh-kham-benh.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'HƯỚNG DẪN DÀNH CHO NGƯỜI BỆNH' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Quy trình Khám chữa bệnh' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Sơ đồ và các bước hướng dẫn người bệnh khi đến thăm khám có thẻ BHYT, khám thu phí dịch vụ hoặc tiếp nhận cấp cứu tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        {
          name: 'showNoticeBanner',
          label: 'Bật thông báo đầu trang quy trình',
          type: 'checkbox',
          defaultValue: false,
        },
        {
          name: 'noticeTitle',
          label: 'Tiêu đề thông báo lưu ý',
          type: 'text',
          defaultValue: 'Lưu ý khi đến khám tại Bệnh viện Đa khoa Khu vực Thới Lai',
        },
        {
          name: 'noticeContent',
          label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)',
          type: 'textarea',
          defaultValue: '• Người bệnh có thẻ BHYT đúng tuyến hoặc thông tuyến được hưởng đầy đủ quyền lợi chi trả.\n• Bệnh viện tiếp nhận khám sớm từ 06:30 tại các khoa chuyên môn trọng điểm.\n• Người cao tuổi, phụ nữ mang thai và trẻ nhỏ được cấp số ưu tiên tiếp đón.',
        },
        {
          name: 'noticeAlign',
          label: 'Canh lề bảng lưu ý',
          type: 'select',
          enumName: 'enum_flow_not_align',
          dbName: 'notice_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'showChecklist',
          label: 'Hiển thị khối giấy tờ cần chuẩn bị',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showPriority',
          label: 'Hiển thị khối đối tượng ưu tiên tiếp đón',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showSupportBanner',
          label: 'Hiển thị banner đặt hẹn & cấp cứu',
          type: 'checkbox',
          defaultValue: true,
        },
      ],
    },
    {
      name: 'qualityPage',
      label: 'Trang Chất lượng bệnh viện',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả, thông báo lưu ý và cấu hình hiển thị trên trang /chat-luong-benh-vien.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'QUẢN LÝ CHẤT LƯỢNG & AN TOÀN NGƯỜI BỆNH' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Chất lượng Bệnh viện' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Bộ chỉ số đo lường 83 tiêu chí chất lượng, kết quả khảo sát sự hài lòng và các chương trình cải tiến liên tục tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        {
          name: 'showNoticeBanner',
          label: 'Bật thông báo lưu ý đầu trang',
          type: 'checkbox',
          defaultValue: false,
        },
        {
          name: 'noticeTitle',
          label: 'Tiêu đề thông báo lưu ý',
          type: 'text',
          defaultValue: 'Cam kết chất lượng phục vụ của Bệnh viện Đa khoa Khu vực Thới Lai',
        },
        {
          name: 'noticeContent',
          label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)',
          type: 'textarea',
          defaultValue: '• Lấy người bệnh làm trung tâm phục vụ, đảm bảo an toàn và quyền lợi người bệnh.\n• Đánh giá chất lượng định kỳ theo Bộ 83 Tiêu chí của Bộ Y tế.\n• Mọi ý kiến đóng góp được Ban Giám đốc tiếp nhận và cải tiến liên tục.',
        },
        {
          name: 'noticeAlign',
          label: 'Canh lề bảng lưu ý',
          type: 'select',
          enumName: 'enum_quality_not_align',
          dbName: 'notice_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'showQualityCards',
          label: 'Hiển thị các chỉ số chất lượng chính',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showDimensions',
          label: 'Hiển thị 5 nhóm tiêu chuẩn Bộ Y tế',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showPrograms',
          label: 'Hiển thị các chương trình cải tiến',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showFeedbackBox',
          label: 'Hiển thị khối khảo sát & tiếp nhận ý kiến',
          type: 'checkbox',
          defaultValue: true,
        },
      ],
    },
    {
      name: 'surveyPage',
      label: 'Trang Khảo sát ý kiến',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /khao-sat.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHĂM SÓC NGƯỜI BỆNH & KHẢO SÁT' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Khảo sát Ý kiến & Sự hài lòng' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Bệnh viện Đa khoa Khu vực Thới Lai trân trọng từng ý kiến đóng góp của người bệnh và thân nhân để không ngừng nâng cao y đức, văn hóa phục vụ và chất lượng điều trị.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo lưu ý', type: 'text', defaultValue: 'Quy chế khảo sát ẩn danh' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter)', type: 'textarea', defaultValue: 'Mọi câu trả lời của quý người bệnh hoàn toàn bảo mật và không ảnh hưởng đến quá trình điều trị.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    {
      name: 'faqPage',
      label: 'Trang Hỏi đáp y tế (FAQ)',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /hoi-dap.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHĂM SÓC NGƯỜI BỆNH & GIẢI ĐÁP' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Hỏi đáp Y tế & Câu hỏi thường gặp' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Tổng hợp các giải đáp chính xác, nhanh chóng nhất về chính sách khám chữa bệnh, quyền lợi bảo hiểm và hướng dẫn thủ tục tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo lưu ý', type: 'text', defaultValue: 'Giải đáp thắc mắc người bệnh' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter)', type: 'textarea', defaultValue: 'Nếu chưa tìm thấy thông tin cần biết, quý vị có thể đặt câu hỏi trực tuyến hoặc gọi hotline 02923686115.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    {
      name: 'formsPage',
      label: 'Trang Biểu mẫu điện tử',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /bieu-mau.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHĂM SÓC NGƯỜI BỆNH & THỦ TỤC ĐIỆN TỬ' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Biểu mẫu Điện tử & Đăng ký' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Hệ thống biểu mẫu hành chính số hóa giúp người bệnh đăng ký thủ tục nhanh chóng, tiết kiệm thời gian chờ đợi tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo lưu ý', type: 'text', defaultValue: 'Lưu ý khi điền biểu mẫu trực tuyến' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter)', type: 'textarea', defaultValue: 'Vui lòng cung cấp đúng số điện thoại để nhận mã xác nhận tiếp nhận từ bệnh viện.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    // ─── TRANG DÀNH CHO NGƯỜI BỆNH (PORTAL) ─────────────────────────────────
    {
      name: 'patientPortalPage',
      label: 'Trang Dành cho người bệnh (Portal)',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /danh-cho-nguoi-benh.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CỔNG TIỆN ÍCH NGƯỜI BỆNH' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Dành cho Người bệnh' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Tổng hợp đầy đủ các tiện ích, hướng dẫn và dịch vụ hỗ trợ người bệnh tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo', type: 'text', defaultValue: 'Thông báo dành cho người bệnh' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)', type: 'textarea', defaultValue: '• Vui lòng mang theo CCCD/CMND và thẻ BHYT khi đến khám.\n• Đặt lịch trực tuyến qua ứng dụng Medpro để được phục vụ ưu tiên.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'pp_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    // ─── TRANG LỊCH TRỰC ─────────────────────────────────────────────────────
    {
      name: 'lichTrucPage',
      label: 'Trang Lịch trực cấp cứu',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /lich-truc.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'TRỰC 24/7' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Lịch trực Cấp cứu' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Danh sách bác sĩ, điều dưỡng trực cấp cứu 24/7 tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: true },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo', type: 'text', defaultValue: 'Đường dây cấp cứu bệnh viện' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)', type: 'textarea', defaultValue: '• Cấp cứu 24/7: Gọi ngay 02923686115.\n• Ekip trực cấp cứu sẵn sàng tiếp nhận tất cả các ngày trong tuần, kể cả ngày lễ, Tết.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'lt_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    // ─── TRANG HOẠT ĐỘNG KHOA HỌC ────────────────────────────────────────────
    {
      name: 'scienceActivityPage',
      label: 'Trang Hoạt động Khoa học',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /hoat-dong-khoa-hoc.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'NGHIÊN CỨU & HỌC THUẬT' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Hoạt động Khoa học' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Tổng hợp các hội nghị khoa học, đề tài nghiên cứu, chương trình đào tạo chuyên môn và hoạt động học thuật tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo', type: 'text', defaultValue: 'Thông báo hoạt động khoa học' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)', type: 'textarea', defaultValue: '' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'sa_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    // ─── TRANG PHÁC ĐỒ ĐIỀU TRỊ ─────────────────────────────────────────────
    {
      name: 'clinicalProtocolPage',
      label: 'Trang Phác đồ điều trị',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /phac-do-dieu-tri.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHUYÊN MÔN LÂM SÀNG' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Phác đồ Điều trị' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Hệ thống phác đồ điều trị chuẩn được Ban Giám đốc và Hội đồng Khoa học thông qua, áp dụng thống nhất tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo', type: 'text', defaultValue: 'Lưu ý về phác đồ điều trị' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)', type: 'textarea', defaultValue: '• Phác đồ được cập nhật định kỳ theo hướng dẫn của Bộ Y tế và y văn quốc tế.\n• Áp dụng theo chỉ định của bác sĩ điều trị, không tự ý thay đổi.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'cp_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'showSearchBox',
          label: 'Hiển thị ô tìm kiếm phác đồ',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showCategoryFilter',
          label: 'Hiển thị bộ lọc theo nhóm bệnh',
          type: 'checkbox',
          defaultValue: true,
        },
      ],
    },
    {
      name: 'websiteAssistant',
      label: 'Chatbot và nút lên đầu trang',
      type: 'group',
      admin: { description: 'Tùy chỉnh trợ lý hỗ trợ hiển thị ở góc phải trên toàn bộ website.' },
      fields: [
        { name: 'enabled', label: 'Hiển thị chatbot', type: 'checkbox', defaultValue: true },
        { name: 'backToTopEnabled', label: 'Hiển thị nút lên đầu trang', type: 'checkbox', defaultValue: true },
        { name: 'assistantLogo', label: 'Logo chatbot', type: 'upload', relationTo: 'media', admin: { description: 'Chọn logo đã tải trong thư viện. Để trống sẽ tự dùng Logo bệnh viện.' } },
        { name: 'assistantName', label: 'Tên chatbot', type: 'text', defaultValue: 'Trợ lý Thới Lai' },
        { name: 'statusText', label: 'Dòng trạng thái', type: 'text', defaultValue: 'Đang trực tuyến' },
        {
          name: 'greeting',
          label: 'Lời chào mở đầu',
          type: 'textarea',
          defaultValue: 'Xin chào! Tôi có thể giúp bạn tra cứu lịch khám, bảng giá, tiêm ngừa và thông tin bệnh viện.',
        },
        { name: 'inputPlaceholder', label: 'Chữ gợi ý trong ô nhập', type: 'text', defaultValue: 'Nhập nội dung cần hỏi…' },
        { name: 'noticeText', label: 'Dòng ghi chú cuối chatbot', type: 'text', defaultValue: 'Thông tin chỉ mang tính tham khảo. Trường hợp cấp cứu, vui lòng gọi bệnh viện ngay.' },
        colorField('primaryColor', 'Màu chính chatbot', '#0878D1', { admin: { description: 'Nhập mã màu, ví dụ: #0878D1' } }),
        {
          name: 'quickTopics',
          dbName: 'site_assistant_topics',
          label: 'Các nút hỏi nhanh',
          type: 'array',
          maxRows: 12,
          defaultValue: defaultQuickTopics,
          admin: { description: 'Thêm, xóa hoặc kéo thả để đổi thứ tự các nút hiển thị dưới nội dung trò chuyện.' },
          fields: [
            { name: 'label', label: 'Tên nút', type: 'text', required: true },
            { name: 'value', label: 'Câu hỏi gửi vào chatbot', type: 'text', required: true },
          ],
        },
        {
          name: 'customAnswers',
          dbName: 'site_assistant_answers',
          label: 'Kho câu hỏi và câu trả lời',
          type: 'array',
          maxRows: 100,
          defaultValue: defaultAssistantAnswers,
          admin: { description: 'Chatbot dò các từ khóa để chọn câu trả lời. Có thể thêm tối đa 100 nội dung và gắn liên kết riêng. Dùng {{HOTLINE}} hoặc {{MEDPRO_URL}} để tự lấy cấu hình website.' },
          fields: [
            { name: 'question', label: 'Câu hỏi mẫu / Tên nội dung', type: 'text', required: true },
            { name: 'keywords', label: 'Từ khóa nhận biết', type: 'textarea', required: true, admin: { description: 'Ngăn cách bằng dấu phẩy. Ví dụ: lịch khám, bác sĩ, chuyên khoa' } },
            { name: 'answer', label: 'Nội dung trả lời', type: 'textarea', required: true },
            { name: 'linkLabel', label: 'Tên nút liên kết', type: 'text', admin: { placeholder: 'Ví dụ: Xem chi tiết' } },
            { name: 'linkUrl', label: 'Đường dẫn liên kết', type: 'text', admin: { placeholder: '/lich-kham hoặc https://...' } },
            { name: 'openNewTab', label: 'Mở liên kết trong tab mới', type: 'checkbox', defaultValue: false },
          ],
        },
        { name: 'fallbackResponse', label: 'Câu trả lời khi không tìm thấy nội dung', type: 'textarea', defaultValue: 'Tôi chưa hiểu rõ câu hỏi. Bạn hãy chọn một mục gợi ý hoặc liên hệ trực tiếp với bệnh viện để được hỗ trợ.' },
        { name: 'fallbackLinkLabel', label: 'Tên nút của câu trả lời mặc định', type: 'text', defaultValue: 'Liên hệ bệnh viện' },
        { name: 'fallbackLinkUrl', label: 'Liên kết của câu trả lời mặc định', type: 'text', defaultValue: '/lien-he' },
      ],
    },
    {
      name: 'brand',
      label: 'Màu thương hiệu (cũ – không dùng)',
      type: 'group',
      admin: { hidden: true, description: 'Trường cũ, đã chuyển sang headerBrandAppearance. Ẩn để tránh nhầm lẫn.' },
      fields: [
        colorField('primaryColor', 'Màu chính', '#0878D1'),
        colorField('secondaryColor', 'Màu phụ', '#FFFFFF'),
      ],
    },
  ],
}
