import type { GlobalConfig, Field } from 'payload'
import { loggedIn } from '@/access'

// Helper: field màu với ColorPickerField custom component
const colorField = (name: string, label: string, defaultValue?: string, opts?: Record<string, unknown>): Field => ({
  name,
  label,
  type: 'text',
  ...(defaultValue ? { defaultValue } : {}),
  admin: {
    components: {
      Field: '/src/components/admin/ColorPickerField#default',
    },
    ...(opts?.admin as Record<string, unknown> || {}),
  },
  ...(opts || {}),
} as Field)


const defaultQuickTopics = [
  { label: 'Lịch khám', value: 'Xem lịch khám bác sĩ' },
  { label: 'Đặt khám', value: 'Tôi muốn đặt lịch khám' },
  { label: 'Bảng giá', value: 'Tra cứu bảng giá dịch vụ' },
  { label: 'Tiêm ngừa', value: 'Thông tin tiêm ngừa' },
]

const defaultAssistantAnswers = [
  { question: 'Lịch khám bác sĩ', keywords: 'lịch khám, bác sĩ, khoa khám', answer: 'Bạn có thể xem lịch khám theo ngày, theo tuần hoặc lịch đính kèm tại đây.', linkLabel: 'Xem lịch khám', linkUrl: '/lich-kham' },
  { question: 'Đặt lịch khám', keywords: 'đặt khám, đặt lịch, Medpro', answer: 'Bạn có thể đặt lịch khám trực tuyến qua Medpro.', linkLabel: 'Đặt khám qua Medpro', linkUrl: '{{MEDPRO_URL}}', openNewTab: true },
  { question: 'Bảng giá dịch vụ', keywords: 'bảng giá, chi phí, giá dịch vụ', answer: 'Bảng giá BHYT và giá dịch vụ được bệnh viện cập nhật tại đây.', linkLabel: 'Tra cứu bảng giá', linkUrl: '/bang-gia' },
  { question: 'Thông tin tiêm ngừa', keywords: 'tiêm ngừa, tiêm chủng, vắc xin, vaccine', answer: 'Xem thông báo lịch tiêm, các đợt tiêm và danh mục vắc xin.', linkLabel: 'Xem thông tin tiêm ngừa', linkUrl: '/tiem-chung' },
  { question: 'Hướng dẫn khám BHYT', keywords: 'BHYT, bảo hiểm y tế, khám bảo hiểm', answer: 'Thông tin khám BHYT và hướng dẫn cần thiết được đăng tại đây.', linkLabel: 'Xem hướng dẫn BHYT', linkUrl: '/trang/kham-bhyt' },
  { question: 'Thông báo bệnh viện', keywords: 'thông báo, thông tin mới', answer: 'Xem toàn bộ thông báo mới và thông báo quan trọng của bệnh viện.', linkLabel: 'Xem thông báo', linkUrl: '/thong-bao' },
  { question: 'Tin tức và hoạt động', keywords: 'tin tức, hoạt động bệnh viện', answer: 'Tin tức và hoạt động mới nhất của bệnh viện được cập nhật tại đây.', linkLabel: 'Xem tin tức', linkUrl: '/tin-tuc' },
  { question: 'Liên hệ và hotline', keywords: 'địa chỉ, liên hệ, hotline, số điện thoại, cấp cứu', answer: 'Bạn có thể gọi bệnh viện theo số {{HOTLINE}} hoặc mở trang Liên hệ.', linkLabel: 'Gọi bệnh viện', linkUrl: 'tel:{{HOTLINE}}' },
]

export const SiteSettings: GlobalConfig = {
  slug: 'site-settings',
  label: 'Header & Nhận diện',
  admin: { group: 'Trang chủ & Giao diện' },
  access: { read: () => true, update: loggedIn },
  versions: { max: 20 },
  hooks: {
    afterRead: [({ doc }) => ({
      ...doc,
      websiteAssistant: {
        enabled: true,
        backToTopEnabled: true,
        assistantName: 'Trợ lý Thới Lai',
        statusText: 'Đang trực tuyến',
        greeting: 'Xin chào! Tôi có thể giúp bạn tra cứu lịch khám, bảng giá, tiêm ngừa và thông tin bệnh viện.',
        inputPlaceholder: 'Nhập nội dung cần hỏi…',
        noticeText: 'Thông tin chỉ mang tính tham khảo. Trường hợp cấp cứu, vui lòng gọi bệnh viện ngay.',
        fallbackResponse: 'Tôi chưa hiểu rõ câu hỏi. Bạn hãy chọn một mục gợi ý hoặc liên hệ trực tiếp với bệnh viện để được hỗ trợ.',
        fallbackLinkLabel: 'Liên hệ bệnh viện',
        fallbackLinkUrl: '/lien-he',
        primaryColor: '#0878D1',
        ...(doc?.websiteAssistant || {}),
        quickTopics: Array.isArray(doc?.websiteAssistant?.quickTopics) ? doc.websiteAssistant.quickTopics : defaultQuickTopics,
        customAnswers: Array.isArray(doc?.websiteAssistant?.customAnswers) ? doc.websiteAssistant.customAnswers : defaultAssistantAnswers,
      },
    })],
  },
  fields: [
    { name: 'hospitalName', label: 'Tên bệnh viện', type: 'text', defaultValue: 'Bệnh viện Đa khoa Khu vực Thới Lai', required: true },
    { name: 'logo', label: 'Logo bệnh viện', type: 'upload', relationTo: 'media', admin: { description: 'Logo chính dùng đồng bộ tại Header và Footer. Website hiển thị trực tiếp file gốc, không dùng ảnh thumbnail. Nên dùng PNG nền trong suốt từ 800×800 px trở lên để chữ và chi tiết logo rõ nét.' } },
    { name: 'headerSlogan', label: 'Slogan dưới tên bệnh viện', type: 'text', defaultValue: 'Điều trị bằng trái tim - Chăm sóc bằng tấm lòng' },
    { name: 'headerShowSlogan', label: 'Hiển thị slogan', type: 'checkbox', defaultValue: true },
    { name: 'headerShowUtilityBar', label: 'Hiển thị thanh ngày giờ / mạng xã hội', type: 'checkbox', defaultValue: true },
    { name: 'headerShowSearch', label: 'Hiển thị ô tìm kiếm', type: 'checkbox', defaultValue: true },
    { name: 'headerShowContactCards', label: 'Hiển thị các ô liên hệ nhanh', type: 'checkbox', defaultValue: true },
    { name: 'headerStickyMenu', label: 'Menu bám đầu trang', type: 'checkbox', defaultValue: true },
    {
      name: 'headerUtilityAppearance',
      label: 'Thanh ngày giờ phía trên',
      type: 'group',
      fields: [
        { name: 'timePrefix', label: 'Chữ trước thời gian', type: 'text', defaultValue: '' },
        { name: 'showCalendarIcon', label: 'Hiển thị icon lịch', type: 'checkbox', defaultValue: true },
        colorField('background', 'Nền thanh trên', '#064a83'),
        colorField('timeColor', 'Màu chữ thời gian', '#FFFFFF'),
        { name: 'timeFontSize', label: 'Cỡ chữ thời gian (px)', type: 'number', min: 10, max: 22, defaultValue: 13 },
        { name: 'timeFontWeight', label: 'Độ đậm chữ thời gian', type: 'text', defaultValue: '700', admin: { placeholder: '600, 700, 800...' } },
      ],
    },
    {
      name: 'headerBrandAppearance',
      label: 'Nhận diện: Logo, tên bệnh viện, slogan và nền Header',
      type: 'group',
      fields: [
        {
          name: 'logoSize',
          label: 'Kích thước logo (px)',
          type: 'number',
          defaultValue: 66,
          min: 42,
          max: 140,
        },
        {
          name: 'titleFontSize',
          label: 'Cỡ chữ dòng “BỆNH VIỆN ĐA KHOA” (px)',
          type: 'number',
          defaultValue: 17,
          min: 12,
          max: 28,
        },
        {
          name: 'subtitleFontSize',
          label: 'Cỡ chữ dòng “KHU VỰC THỚI LAI” (px)',
          type: 'number',
          defaultValue: 13,
          min: 9,
          max: 22,
        },
        colorField('headerBackgroundColor', 'Màu nền thanh đầu trang', '#FFFFFF', { admin: { description: 'Nhập mã màu, ví dụ: #FFFFFF' } }),
        colorField('logoBackgroundColor', 'Màu nền khung logo', '#FFFFFF', { admin: { description: 'Nhập mã màu, ví dụ: #FFFFFF' } }),
        colorField('titleColor', 'Màu chữ dòng Bệnh viện ĐA KHOA', '#143653', { admin: { description: 'Nhập mã màu, ví dụ: #143653' } }),
        colorField('subtitleColor', 'Màu chữ dòng KHU VỰC THỚI LAI', '#0878D1', { admin: { description: 'Nhập mã màu, ví dụ: #0878D1' } }),
        { name: 'showLogo', label: 'Hiển thị logo', type: 'checkbox', defaultValue: true },
        { name: 'showHospitalName', label: 'Hiển thị tên bệnh viện', type: 'checkbox', defaultValue: true },
        { name: 'backgroundImage', label: 'Ảnh nền khu vực nhận diện', type: 'upload', relationTo: 'media', admin: { description: 'Có thể chọn ảnh đã tải lên. Để trống sẽ dùng màu nền.' } },
        { name: 'backgroundSize', label: 'Kiểu phủ ảnh nền', type: 'text', defaultValue: 'cover', admin: { placeholder: 'cover hoặc contain' } },
        { name: 'backgroundPosition', label: 'Vị trí ảnh nền', type: 'text', defaultValue: 'center center', admin: { placeholder: 'center center' } },
        { name: 'backgroundOverlay', label: 'Lớp phủ trên ảnh nền', type: 'text', defaultValue: 'rgba(255,255,255,0.88)', admin: { placeholder: 'rgba(255,255,255,0.88)' } },
        { name: 'minHeight', label: 'Chiều cao tối thiểu khối nhận diện (px)', type: 'number', min: 70, max: 260, defaultValue: 110 },
      ],
      admin: { description: 'Logo được chọn ở trường Logo bệnh viện phía trên. Tại đây chỉnh hiển thị, kích thước, màu chữ và ảnh/màu nền của vùng nhận diện.' },
    },
    {
      name: 'headerContactCards',
      label: 'Cấp cứu / Tổng đài / Liên hệ nhanh',
      type: 'array',
      maxRows: 6,
      labels: { singular: 'Ô liên hệ', plural: 'Các ô liên hệ' },
      admin: { description: 'Quản lý duy nhất các ô Cấp cứu, Tổng đài hỗ trợ và ô liên hệ nhanh trên Header. Mỗi ô có thể đổi icon mặc định hoặc tải icon riêng.' },
      fields: [
        { name: 'visible', label: 'Hiển thị', type: 'checkbox', defaultValue: true },
        { name: 'title', label: 'Tiêu đề', type: 'text', required: true },
        { name: 'text', label: 'Nội dung / Số điện thoại', type: 'text', required: true },
        { name: 'href', label: 'Liên kết khi bấm', type: 'text', admin: { placeholder: 'tel:02923689115 hoặc https://...' } },
        { name: 'extraText', label: 'Dòng chữ bổ sung', type: 'text' },
        { name: 'iconType', label: 'Loại icon', type: 'text', defaultValue: 'phone', admin: { description: 'phone, emergency, headset, calendar, heart, info hoặc custom' } },
        { name: 'customIcon', label: 'Đổi icon / Tải icon riêng', type: 'upload', relationTo: 'media', admin: { description: 'Nếu chọn ảnh tại đây, ảnh này sẽ thay icon mặc định của ô liên hệ.' } },
        colorField('background', 'Nền ô', '#FFFFFF'),
        colorField('borderColor', 'Màu viền', '#E1E7EC'),
        colorField('titleColor', 'Màu tiêu đề', '#273B4C'),
        colorField('textColor', 'Màu nội dung', '#0756B4'),
        colorField('iconColor', 'Màu icon', '#075EC2'),
        colorField('iconBackground', 'Nền icon', '#EAF5FF'),
        colorField('extraTextColor', 'Màu dòng bổ sung', '#557082'),
        { name: 'titleFontSize', label: 'Cỡ tiêu đề (px)', type: 'number', min: 8, max: 24, defaultValue: 10 },
        { name: 'textFontSize', label: 'Cỡ nội dung (px)', type: 'number', min: 10, max: 34, defaultValue: 17 },
        { name: 'fontWeight', label: 'Độ đậm nội dung', type: 'text', defaultValue: '800', admin: { placeholder: '600, 700, 800...' } },
      ],
    },
    {
      name: 'headerSocialLinks',
      label: 'Icon mạng xã hội dùng chung Header + Footer',
      type: 'array',
      maxRows: 8,
      labels: { singular: 'Mạng xã hội', plural: 'Mạng xã hội' },
      admin: { description: 'Đây là nơi quản lý DUY NHẤT Facebook, Zalo, YouTube, TikTok trên giao diện. Header và Footer dùng chung danh sách này. Có thể tải icon riêng cho từng mạng.' },
      fields: [
        { name: 'visible', label: 'Hiển thị', type: 'checkbox', defaultValue: true },
        { name: 'platform', label: 'Loại', type: 'text', required: true, admin: { placeholder: 'facebook, zalo, youtube, tiktok hoặc custom' } },
        { name: 'label', label: 'Tên hiển thị', type: 'text' },
        { name: 'url', label: 'Liên kết', type: 'text', required: true },
        { name: 'customIcon', label: 'Đổi icon / Tải icon riêng', type: 'upload', relationTo: 'media', admin: { description: 'Để trống sẽ dùng icon chuẩn tích hợp. Chọn ảnh để thay icon Facebook/Zalo/YouTube/TikTok bằng icon riêng.' } },
      ],
    },
    { name: 'tiktokUrl', label: 'Liên kết TikTok (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    {
      name: 'slogan',
      label: 'Nội dung chữ chạy / Khẩu hiệu',
      type: 'text',
      admin: {
        description: 'Nội dung này chạy ngang ngay dưới menu. Để trống sẽ dùng thông báo đặt khám mặc định của bệnh viện.',
        placeholder: 'Nhập thông báo cần chạy trên website…',
      },
    },
    {
      name: 'tickerAppearance',
      label: 'Cài đặt thanh chữ chạy',
      type: 'group',
      fields: [
        { name: 'enabled', label: 'Hiển thị thanh chữ chạy', type: 'checkbox', defaultValue: true },
        colorField('backgroundColor', 'Màu nền', '#FF9F2F', { admin: { description: 'Nhập mã màu, ví dụ: #FF9F2F' } }),
        colorField('textColor', 'Màu chữ', '#FFFFFF', { admin: { description: 'Nhập mã màu, ví dụ: #FFFFFF' } }),
        {
          name: 'fontSize',
          label: 'Kích thước chữ (px)',
          type: 'number',
          defaultValue: 13,
          min: 10,
          max: 24,
        },
        {
          name: 'duration',
          label: 'Thời gian chạy hết một vòng (giây)',
          type: 'number',
          defaultValue: 24,
          min: 8,
          max: 120,
          admin: { description: 'Số nhỏ chạy nhanh hơn; số lớn chạy chậm hơn.' },
        },
      ],
    },
    {
      name: 'headerBanner',
      label: 'Banner đầu trang (nằm trên menu)',
      type: 'upload',
      relationTo: 'media',
      admin: { description: 'Tải banner mới hoặc chọn lại banner đã có trong thư viện. Nếu chưa chọn, website dùng banner có sẵn trong hệ thống.' },
    },
    {
      name: 'headerBannerWidth',
      label: 'Chiều rộng banner đầu trang (px)',
      type: 'number',
      min: 600,
      max: 3000,
      defaultValue: 1300,
      admin: { description: 'Nên dùng 1300 px. Ảnh banner tải lên nên có đúng kích thước 1300 × 200 px.' },
    },
    {
      name: 'headerBannerHeight',
      label: 'Chiều cao banner đầu trang (px)',
      type: 'number',
      min: 80,
      max: 360,
      defaultValue: 200,
      admin: { description: 'Nên dùng 200 px để khớp banner chuẩn 1300 × 200 px.' },
    },
    { name: 'favicon', label: 'Biểu tượng trình duyệt', type: 'upload', relationTo: 'media', admin: { description: 'Tải mới hoặc chọn lại hình đã có trong Thư viện Tệp & Hình ảnh.' } },
    { name: 'hotline', label: 'Hotline bệnh viện', type: 'text' },
    { name: 'emergencyHotline', label: 'Hotline cấp cứu', type: 'text' },
    { name: 'email', label: 'Email', type: 'email' },
    { name: 'address', label: 'Địa chỉ', type: 'textarea' },
    { name: 'workingHours', label: 'Thời gian làm việc', type: 'text' },
    { name: 'medproUrl', label: 'Liên kết đặt khám Medpro', type: 'text' },
    { name: 'zaloUrl', label: 'Liên kết Zalo (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    { name: 'facebookUrl', label: 'Liên kết Facebook (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    { name: 'youtubeUrl', label: 'Liên kết YouTube (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    {
      name: 'googleMapsEmbed',
      label: 'Bản đồ Google Maps',
      type: 'textarea',
      admin: {
        description: 'Dán toàn bộ mã <iframe> hoặc URL nhúng Google Maps (URL có /embed hoặc output=embed). Để trống, website tự hiển thị bản đồ theo Địa chỉ ở trên.',
      },
    },
    { name: 'footerText', label: 'Nội dung chân trang', type: 'textarea' },
    {
      name: 'servicePricePage',
      label: 'Trang Bảng giá dịch vụ',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, ô tìm kiếm và số dịch vụ hiển thị trên mỗi trang.' },
      fields: [
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Bảng giá dịch vụ' },
        { name: 'description', label: 'Mô tả', type: 'textarea', defaultValue: 'Tra cứu giá BHYT và giá dịch vụ được cập nhật trực tiếp từ hệ thống quản trị.' },
        { name: 'searchPlaceholder', label: 'Chữ gợi ý trong ô tìm kiếm', type: 'text', defaultValue: 'Nhập tên, mã dịch vụ, nhóm hoặc ghi chú…' },
        { name: 'rowsPerPage', label: 'Số dòng hiển thị trên mỗi trang', type: 'select', defaultValue: '40', required: true, options: [
          { label: '40 dịch vụ / trang', value: '40' },
          { label: '50 dịch vụ / trang', value: '50' },
        ] },
        { name: 'searchNotes', label: 'Cho phép tìm trong cột Ghi chú', type: 'checkbox', defaultValue: true },
        { name: 'emptyText', label: 'Thông báo khi không có kết quả', type: 'text', defaultValue: 'Không tìm thấy dịch vụ phù hợp.' },
      ],
    },
    {
      name: 'websiteAssistant',
      label: 'Chatbot và nút lên đầu trang',
      type: 'group',
      admin: { description: 'Tùy chỉnh trợ lý hỗ trợ hiển thị ở góc phải trên toàn bộ website.' },
      fields: [
        { name: 'enabled', label: 'Hiển thị chatbot', type: 'checkbox', defaultValue: true },
        { name: 'backToTopEnabled', label: 'Hiển thị nút lên đầu trang', type: 'checkbox', defaultValue: true },
        { name: 'assistantLogo', label: 'Logo chatbot', type: 'upload', relationTo: 'media', admin: { description: 'Chọn logo đã tải trong thư viện. Để trống sẽ tự dùng Logo bệnh viện.' } },
        { name: 'assistantName', label: 'Tên chatbot', type: 'text', defaultValue: 'Trợ lý Thới Lai' },
        { name: 'statusText', label: 'Dòng trạng thái', type: 'text', defaultValue: 'Đang trực tuyến' },
        {
          name: 'greeting',
          label: 'Lời chào mở đầu',
          type: 'textarea',
          defaultValue: 'Xin chào! Tôi có thể giúp bạn tra cứu lịch khám, bảng giá, tiêm ngừa và thông tin bệnh viện.',
        },
        { name: 'inputPlaceholder', label: 'Chữ gợi ý trong ô nhập', type: 'text', defaultValue: 'Nhập nội dung cần hỏi…' },
        { name: 'noticeText', label: 'Dòng ghi chú cuối chatbot', type: 'text', defaultValue: 'Thông tin chỉ mang tính tham khảo. Trường hợp cấp cứu, vui lòng gọi bệnh viện ngay.' },
        colorField('primaryColor', 'Màu chính chatbot', '#0878D1', { admin: { description: 'Nhập mã màu, ví dụ: #0878D1' } }),
        {
          name: 'quickTopics',
          label: 'Các nút hỏi nhanh',
          type: 'array',
          maxRows: 12,
          defaultValue: defaultQuickTopics,
          admin: { description: 'Thêm, xóa hoặc kéo thả để đổi thứ tự các nút hiển thị dưới nội dung trò chuyện.' },
          fields: [
            { name: 'label', label: 'Tên nút', type: 'text', required: true },
            { name: 'value', label: 'Câu hỏi gửi vào chatbot', type: 'text', required: true },
          ],
        },
        {
          name: 'customAnswers',
          label: 'Kho câu hỏi và câu trả lời',
          type: 'array',
          maxRows: 100,
          defaultValue: defaultAssistantAnswers,
          admin: { description: 'Chatbot dò các từ khóa để chọn câu trả lời. Có thể thêm tối đa 100 nội dung và gắn liên kết riêng. Dùng {{HOTLINE}} hoặc {{MEDPRO_URL}} để tự lấy cấu hình website.' },
          fields: [
            { name: 'question', label: 'Câu hỏi mẫu / Tên nội dung', type: 'text', required: true },
            { name: 'keywords', label: 'Từ khóa nhận biết', type: 'textarea', required: true, admin: { description: 'Ngăn cách bằng dấu phẩy. Ví dụ: lịch khám, bác sĩ, chuyên khoa' } },
            { name: 'answer', label: 'Nội dung trả lời', type: 'textarea', required: true },
            { name: 'linkLabel', label: 'Tên nút liên kết', type: 'text', admin: { placeholder: 'Ví dụ: Xem chi tiết' } },
            { name: 'linkUrl', label: 'Đường dẫn liên kết', type: 'text', admin: { placeholder: '/lich-kham hoặc https://...' } },
            { name: 'openNewTab', label: 'Mở liên kết trong tab mới', type: 'checkbox', defaultValue: false },
          ],
        },
        { name: 'fallbackResponse', label: 'Câu trả lời khi không tìm thấy nội dung', type: 'textarea', defaultValue: 'Tôi chưa hiểu rõ câu hỏi. Bạn hãy chọn một mục gợi ý hoặc liên hệ trực tiếp với bệnh viện để được hỗ trợ.' },
        { name: 'fallbackLinkLabel', label: 'Tên nút của câu trả lời mặc định', type: 'text', defaultValue: 'Liên hệ bệnh viện' },
        { name: 'fallbackLinkUrl', label: 'Liên kết của câu trả lời mặc định', type: 'text', defaultValue: '/lien-he' },
      ],
    },
    {
      name: 'brand',
      label: 'Màu thương hiệu',
      type: 'group',
      fields: [
        colorField('primaryColor', 'Màu chính', '#0878D1'),
        colorField('secondaryColor', 'Màu phụ', '#FFFFFF'),
      ],
    },
  ],
}
