import type { GlobalConfig, Field } from 'payload'
import { moduleAccess } from '@/access'

// Helper: field màu với ColorPickerField custom component
const colorField = (name: string, label: string, defaultValue?: string, opts?: Record<string, unknown>): Field => ({
  name,
  label,
  type: 'text',
  ...(defaultValue ? { defaultValue } : {}),
  admin: {
    components: {
      Field: '/src/components/admin/ColorPickerField#default',
    },
    ...(opts?.admin as Record<string, unknown> || {}),
  },
  ...(opts || {}),
} as Field)


const defaultQuickTopics = [
  { label: '🚑 Cấp cứu 115', value: 'Cấp cứu khẩn cấp' },
  { label: '📅 Lịch khám bác sĩ', value: 'Xem lịch khám bác sĩ' },
  { label: '📝 Đặt lịch khám', value: 'Tôi muốn đặt lịch khám' },
  { label: '💰 BHYT & Bảng giá', value: 'Khám BHYT và bảng giá viện phí' },
  { label: '💉 Tiêm chủng vắc xin', value: 'Thông tin tiêm chủng vắc xin' },
  { label: '⏰ Giờ làm việc', value: 'Giờ làm việc và khám bệnh' },
  { label: '🧭 Hướng dẫn đi khám', value: 'Quy trình và thủ tục khám bệnh' },
  { label: '🩺 Gợi ý khoa khám', value: 'Tư vấn gợi ý chuyên khoa theo triệu chứng' },
]

const defaultAssistantAnswers = [
  {
    question: 'BHYT thông tuyến & Mức hưởng',
    keywords: 'bhyt, bao hiem y te, trai tuyen, trai tuyến, thong tuyen, thông tuyến, muc huong, mức hưởng, bao nhieu phan tram, bao nhiêu phần trăm',
    answer: 'BVĐK Khu vực Thới Lai là bệnh viện tuyến huyện tiếp nhận khám chữa bệnh BHYT THÔNG TUYẾN TOÀN QUỐC:\n\n• Người bệnh có thẻ BHYT đăng ký tại bất kỳ trạm y tế, trung tâm y tế hay bệnh viện quận/huyện nào trên cả nước khi đến khám tại BVĐK KV Thới Lai đều được hưởng ĐÚNG TUYẾN 100% mức quyền lợi trên thẻ (80%, 95% hoặc 100% tùy mã đối tượng).\n• KHÔNG CẦN GIẤY CHUYỂN TUYẾN khi khám ngoại trú và điều trị nội trú.\n• Người bệnh chỉ cần xuất trình CCCD gắn chip hoặc ứng dụng VNeID / VssID.',
    linkLabel: 'Xem chi tiết quyền lợi BHYT',
    linkUrl: '/trang/kham-bhyt',
  },
  {
    question: 'Giấy tờ cần mang khi đi khám bệnh',
    keywords: 'giay to, giấy tờ, thu tuc, thủ tục, mang theo gi, cccd, can cuoc, the bhyt, the bao hiem, vneid, vssid',
    answer: 'Khi đến khám chữa bệnh tại BVĐK Khu vực Thới Lai, quý người bệnh chỉ cần chuẩn bị:\n\n1. Căn cước công dân (CCCD) gắn chip ĐÃ TÍCH HỢP BHYT (hoặc mở thẻ BHYT điện tử trên ứng dụng VNeID / VssID).\n2. Trường hợp chưa tích hợp CCCD: Mang theo thẻ BHYT giấy còn hạn + giấy tờ tùy thân có ảnh.\n3. Trẻ em dưới 6 tuổi: Thẻ BHYT và Giấy khai sinh (bản sao hoặc ảnh chụp).\n4. Sổ khám bệnh, đơn thuốc hoặc kết quả xét nghiệm/phim chụp cũ (nếu có) để bác sĩ theo dõi liên tục.',
    linkLabel: 'Xem quy trình tiếp đón',
    linkUrl: '/trang/kham-bhyt',
  },
  {
    question: 'Quy trình khám bệnh từng bước',
    keywords: 'quy trinh, quy trình, cac buoc kham, các bước khám, lay so, lấy số, kham the nao, huong dan kham',
    answer: 'Quy trình khám bệnh tại BVĐK Khu vực Thới Lai diễn ra nhanh chóng, khép kín:\n\n• Bước 1: Đến Bàn tiếp đón tại Khoa Khám bệnh để lấy số thứ tự, xuất trình CCCD/VNeID để nhân viên tiếp đón đo dấu sinh hiệu và đăng ký phòng khám.\n• Bước 2: Di chuyển đến phòng khám chuyên khoa ghi trên phiếu và ngồi đợi gọi tên vào khám.\n• Bước 3: Bác sĩ thăm khám, chỉ định cận lâm sàng (xét nghiệm, siêu âm, chụp X-quang, nội soi...) nếu cần thiết.\n• Bước 4: Thực hiện cận lâm sàng theo hướng dẫn, sau đó quay lại phòng khám ban đầu để bác sĩ đọc kết quả và kê đơn thuốc.\n• Bước 5: Thanh toán viện phí (đồng chi trả BHYT nếu có) tại quầy Thu ngân và nhận thuốc tại Khoa Dược.',
    linkLabel: 'Sơ đồ & Hướng dẫn quy trình',
    linkUrl: '/trang/kham-bhyt',
  },
  {
    question: 'Bảng giá dịch vụ kỹ thuật & Viện phí',
    keywords: 'bang gia, bảng giá, vien phi, viện phí, chi phi, chi phí, tien kham, tiền khám, gia xet nghiem, giá xét nghiệm, sieu am, xquang, gia tien, giá tiền',
    answer: 'Bảng giá khám bệnh và các dịch vụ kỹ thuật y tế tại BVĐK Khu vực Thới Lai được niêm yết công khai theo đúng khung giá quy định của Bộ Y tế và UBND TP. Cần Thơ:\n\n• Người bệnh có BHYT: Được quỹ BHYT chi trả theo tỷ lệ quy định danh mục kỹ thuật và thuốc men.\n• Khám theo yêu cầu / Dịch vụ tự nguyện: Được giải thích và tư vấn chi phí rõ ràng trước khi thực hiện.\n• Bệnh viện niêm yết công khai bảng giá tiền giường, xét nghiệm máu, siêu âm màu, nội soi tiêu hóa, chụp X-quang kỹ thuật số...',
    linkLabel: 'Tra cứu bảng giá dịch vụ chi tiết',
    linkUrl: '/bang-gia',
  },
  {
    question: 'Thời gian làm việc & Khám ngoài giờ',
    keywords: 'gio lam viec, giờ làm việc, may gio, mấy giờ, gio kham, giờ khám, thu 7, chu nhat, thứ bảy, chủ nhật, ngay nghi, ngày nghỉ, ngoai gio, ngoài giờ',
    answer: 'Thời gian phục vụ khám chữa bệnh tại BVĐK Khu vực Thới Lai:\n\n• CẤP CỨU: Trực 24/24 tất cả các ngày trong tuần (kể cả Lễ, Tết).\n• KHÁM BỆNH NGOẠI TRÚ (Thứ 2 đến Thứ 6):\n  - Buổi sáng: 07:00 – 11:30\n  - Buổi chiều: 13:00 – 16:30\n• THỨ 7, CHỦ NHẬT & NGÀY NGHỈ: Bệnh viện bố trí đội ngũ bác sĩ trực tiếp nhận khám bệnh và xử trí cấp cứu 24/7, quyền lợi BHYT vẫn được đảm bảo đầy đủ.',
    linkLabel: 'Xem lịch làm việc chi tiết',
    linkUrl: '/lich-lam-viec',
  },
  {
    question: 'Lịch khám bác sĩ chuyên khoa',
    keywords: 'lich kham, lịch khám, bac si, bác sĩ, lich truc, lịch trực, ai truc, phòng khám, phong kham',
    answer: 'Lịch làm việc và phân công trực khám của các Bác sĩ chuyên khoa (Nội, Ngoại, Sản, Nhi, Mắt, Tai Mũi Họng, Răng Hàm Mặt, Y học cổ truyền...) được cập nhật thường xuyên trên website.\n\nQuý người bệnh có thể tra cứu để biết chính xác bác sĩ phụ trách từng phòng khám trong ngày.',
    linkLabel: 'Xem lịch khám tuần này',
    linkUrl: '/lich-kham',
  },
  {
    question: 'Đăng ký Đặt lịch khám trực tuyến',
    keywords: 'dat kham, đặt khám, dat lich, đặt lịch, lay so truoc, lấy số trước, dang ky kham, medpro, hen gio',
    answer: 'Để chủ động thời gian và không phải xếp hàng chờ đợi, quý người bệnh có thể đăng ký đặt hẹn trước:\n\n1. Đặt trực tuyến qua nền tảng Medpro: Chủ động lựa chọn ngày khám, khung giờ phù hợp và thanh toán tiện lợi.\n2. Liên hệ số điện thoại tiếp đón của bệnh viện để được nhân viên hỗ trợ ghi nhận lịch hẹn.',
    linkLabel: 'Đặt lịch khám qua Medpro',
    linkUrl: '{{MEDPRO_URL}}',
    openNewTab: true,
  },
  {
    question: 'Phòng Tiêm chủng vắc xin',
    keywords: 'tiem ngua, tiêm ngừa, tiem chung, tiêm chủng, vac xin, vắc xin, vaccine, 6 trong 1, phe cau, cum, dai, uon van',
    answer: 'Phòng Tiêm chủng BVĐK Khu vực Thới Lai cung cấp đa dạng các gói vắc xin chất lượng cao có nguồn gốc rõ ràng, bảo quản theo chuẩn dây chuyền lạnh GSP:\n\n• Vắc xin cho trẻ em: 6 trong 1, Phế cầu Synflorix/Prevenar, Rota virus, Cúm, Thủy đậu, Sởi - Quai bị - Rubella, Viêm não Nhật Bản...\n• Vắc xin cho phụ nữ mang thai: Uốn ván, Bạch hầu - Ho gà - Uốn ván...\n• Vắc xin cho người lớn: Cúm mùa, Viêm gan B, Ung thư cổ tử cung (HPV), Uốn ván, Vắc xin phòng Dại sau phơi nhiễm...\n• Bác sĩ khám sàng lọc miễn phí và theo dõi phản ứng sau tiêm an toàn.',
    linkLabel: 'Xem danh mục vắc xin & Lịch tiêm',
    linkUrl: '/tiem-chung',
  },
  {
    question: 'Khám sức khỏe lái xe, xin việc, định kỳ',
    keywords: 'kham suc khoe, khám sức khỏe, lai xe, lái xe, bang lai, bằng lái, xin viec, xin việc, di lam, đi làm, dinh ky, định kỳ, doi bang, đổi bằng',
    answer: 'BVĐK Khu vực Thới Lai đủ điều kiện pháp lý thực hiện khám và cấp Giấy khám sức khỏe theo quy định của Bộ Y tế:\n\n• Khám sức khỏe lái xe ô tô, mô tô (A1, A2, B1, B2, C, D, E...): Có liên thông dữ liệu Giấy khám sức khỏe lái xe lên Cổng Dịch vụ công Quốc gia để người dân đổi bằng lái xe trực tuyến.\n• Khám sức khỏe tuyển dụng, đi học, đi làm.\n• Khám sức khỏe định kỳ cho cơ quan, doanh nghiệp, trường học.\n\n* Lưu ý: Khi đi khám cần mang theo CCCD và 2 ảnh 4x6 chụp trên nền trắng.',
    linkLabel: 'Xem hướng dẫn khám sức khỏe',
    linkUrl: '/trang/kham-bhyt',
  },
  {
    question: 'Khám thai, sinh nở & Khoa Phụ sản',
    keywords: 'kham thai, khám thai, sieu am thai, siêu âm thai, sinh con, sinh nở, de con, đẻ con, phu san, phụ sản, sinh mo, sinh mổ, tien san, tiền sản',
    answer: 'Khoa Phụ sản - BVĐK Khu vực Thới Lai đồng hành cùng mẹ bầu trong suốt thai kỳ và vượt cạn:\n\n• Khám thai định kỳ, siêu âm sàng lọc dị tật thai nhi, xét nghiệm tiểu đường thai kỳ.\n• Đỡ sinh thường, phẫu thuật mổ lấy thai an toàn, kỹ thuật giảm đau sản khoa.\n• Chăm sóc mẹ và bé sau sinh chu đáo: Da kề da, tiêm vắc xin sơ sinh (Viêm gan B, Lao), đo thính lực và sàng lọc sơ sinh.\n• Hưởng trọn vẹn chế độ BHYT khi sinh con tại viện.',
    linkLabel: 'Xem thông tin Khoa Phụ sản',
    linkUrl: '/chuyen-khoa',
  },
  {
    question: 'Chăm sóc Nhi khoa & Trẻ sơ sinh',
    keywords: 'khoa nhi, khám nhi, tre em, trẻ em, tre nho, trẻ nhỏ, so sinh, sơ sinh, sot cao, sốt cao, ho hen, nôn trớ, co giat',
    answer: 'Khoa Nhi BVĐK Khu vực Thới Lai tiếp nhận khám và điều trị nội - ngoại trú cho trẻ em từ sơ sinh đến 15 tuổi:\n\n• Khám và điều trị các bệnh hô hấp (viêm phế quản, viêm phổi, hen suyễn), tiêu hóa (tiêu chảy cấp, rối loạn tiêu hóa), sốt xuất huyết, tay chân miệng...\n• Đội ngũ bác sĩ và điều dưỡng nhi khoa tận tâm, nhẹ nhàng, thấu hiểu tâm lý trẻ nhỏ.\n• Phòng bệnh sạch sẽ, thoáng mát, thân thiện với bệnh nhi.',
    linkLabel: 'Xem chuyên khoa Nhi',
    linkUrl: '/chuyen-khoa',
  },
  {
    question: 'Cận lâm sàng: Xét nghiệm, X-quang, Siêu âm, Nội soi',
    keywords: 'xet nghiem, xét nghiệm, xquang, x-quang, sieu am, siêu âm, noi soi, nội soi, dien tim, điện tim, chup chieu, chụp chiếu',
    answer: 'Khoa Cận lâm sàng & Chẩn đoán hình ảnh trang bị máy móc hiện đại giúp chẩn đoán bệnh chính xác:\n\n• Xét nghiệm sinh hóa, huyết học, miễn dịch tự động, nước tiểu, đông máu.\n• Siêu âm màu Doppler tổng quát, siêu âm tim, mạch máu, tuyến giáp, sản phụ khoa.\n• Chụp X-quang kỹ thuật số (DR) độ nét cao, liều tia an toàn.\n• Nội soi tiêu hóa (dạ dày, đại tràng) hỗ trợ chẩn đoán sớm bệnh lý tiêu hóa và vi khuẩn HP.',
    linkLabel: 'Xem danh sách dịch vụ kỹ thuật',
    linkUrl: '/bang-gia',
  },
  {
    question: 'Cấp cứu 24/7 & Hỗ trợ khẩn cấp',
    keywords: 'cap cuu, cấp cứu, 115, khan cap, khẩn cấp, tai nan, tai nạn, ngo doc, ngộ độc, dot quy, đột quỵ, bat tinh, bất tỉnh',
    answer: 'Khoa Cấp cứu của BVĐK Khu vực Thới Lai hoạt động 24/24 tất cả các ngày trong tuần (kể cả ban đêm, Thứ 7, Chủ Nhật và ngày Lễ, Tết):\n\n• Sẵn sàng tiếp nhận xử trí các tình huống cấp cứu nội khoa, ngoại khoa, tai nạn giao thông, ngộ độc...\n• Đội ngũ y bác sĩ thường trực cùng xe cấp cứu sẵn sàng điều phối chuyển viện an toàn khi có chỉ định.\n• Đường dây nóng trực cấp cứu 24/7: {{HOTLINE}}.',
    linkLabel: 'Gọi số trực Cấp cứu: {{HOTLINE}}',
    linkUrl: 'tel:{{HOTLINE}}',
  },
  {
    question: 'Gợi ý chuyên khoa theo triệu chứng bệnh',
    keywords: 'dau bung, đau bụng, dau dau, đau đầu, dau nguc, đau ngực, dau mat, đau mắt, dau rang, đau răng, ho sot, ho sốt, chong mat, chóng mặt, trieu chung, triệu chứng, khoa nao, khoa nào',
    answer: 'Định hướng khám bệnh nhanh theo triệu chứng thường gặp:\n\n• Đau bụng, ợ hơi, trào ngược, nôn ói, đi cầu lỏng: Khám Nội tiêu hóa.\n• Ho dai dẳng, sốt, khó thở, tức ngực: Khám Nội hô hấp / Tim mạch.\n• Đau đầu, chóng mặt, mất ngủ, tê bì tay chân: Khám Nội thần kinh.\n• Té ngã, chấn thương, đau khớp, gãy xương: Khám Ngoại chấn thương.\n• Đau răng, sưng nướu, nhổ răng, trồng răng: Chuyên khoa Răng Hàm Mặt.\n• Đau mắt, ngứa mắt, đỏ mắt, mờ mắt: Chuyên khoa Mắt.\n• Nghẹt mũi, đau họng, ù tai, khàn tiếng: Chuyên khoa Tai Mũi Họng.\n\n* Lưu ý: Khi đến bệnh viện, điều dưỡng tại bàn tiếp đón sẽ đo huyết áp và chỉ định phòng khám chính xác nhất.',
    linkLabel: 'Xem danh sách Chuyên khoa',
    linkUrl: '/chuyen-khoa',
  },
  {
    question: 'Địa chỉ & Kênh liên hệ bệnh viện',
    keywords: 'dia chi, địa chỉ, o dau, ở đâu, lien he, liên hệ, hotline, so dien thoai, số điện thoại, sdt, duong di, đường đi',
    answer: 'Thông tin liên hệ Bệnh viện Đa khoa Khu vực Thới Lai:\n\n• Địa chỉ: Thị trấn Thới Lai, Huyện Thới Lai, TP. Cần Thơ.\n• Đường dây nóng tiếp đón & Cấp cứu: {{HOTLINE}}\n• Thời gian tiếp nhận cấp cứu: 24/24 tất cả các ngày.\n• Mọi phản ánh chất lượng dịch vụ hoặc ý kiến đóng góp, quý người bệnh có thể gửi trực tiếp qua website hoặc quầy Chăm sóc khách hàng.',
    linkLabel: 'Xem bản đồ & Liên hệ',
    linkUrl: '/lien-he',
  },
]


export const SiteSettings: GlobalConfig = {
  slug: 'site-settings',
  label: 'Header & Nhận diện',
  admin: { group: '🌐 Trang chủ & Giao diện Website' },
  access: { read: () => true, update: moduleAccess('site-settings', 'edit') },
  versions: { max: 20 },
  hooks: {
    afterRead: [({ doc }) => ({
      ...doc,
      websiteAssistant: {
        enabled: true,
        backToTopEnabled: true,
        assistantName: 'Trợ lý Thới Lai',
        statusText: 'Đang trực tuyến',
        greeting: 'Xin chào! Tôi có thể giúp bạn tra cứu lịch khám, bảng giá, tiêm ngừa và thông tin bệnh viện.',
        inputPlaceholder: 'Nhập nội dung cần hỏi…',
        noticeText: 'Thông tin chỉ mang tính tham khảo. Trường hợp cấp cứu, vui lòng gọi bệnh viện ngay.',
        fallbackResponse: 'Tôi chưa hiểu rõ câu hỏi. Bạn hãy chọn một mục gợi ý hoặc liên hệ trực tiếp với bệnh viện để được hỗ trợ.',
        fallbackLinkLabel: 'Liên hệ bệnh viện',
        fallbackLinkUrl: '/lien-he',
        primaryColor: '#0878D1',
        ...(doc?.websiteAssistant || {}),
        quickTopics: Array.isArray(doc?.websiteAssistant?.quickTopics) ? doc.websiteAssistant.quickTopics : defaultQuickTopics,
        customAnswers: Array.isArray(doc?.websiteAssistant?.customAnswers) ? doc.websiteAssistant.customAnswers : defaultAssistantAnswers,
      },
    })],
  },
  fields: [
    { name: 'hospitalName', label: 'Tên bệnh viện', type: 'text', defaultValue: 'Bệnh viện Đa khoa Khu vực Thới Lai', required: true },
    { name: 'logo', label: 'Logo bệnh viện', type: 'upload', relationTo: 'media', admin: { description: 'Logo chính dùng đồng bộ tại Header và Footer. Website hiển thị trực tiếp file gốc, không dùng ảnh thumbnail. Nên dùng PNG nền trong suốt từ 800×800 px trở lên để chữ và chi tiết logo rõ nét.' } },
    { name: 'headerSlogan', label: 'Slogan dưới tên bệnh viện', type: 'text', defaultValue: 'Điều trị bằng trái tim - Chăm sóc bằng tấm lòng' },
    { name: 'headerShowSlogan', label: 'Hiển thị slogan', type: 'checkbox', defaultValue: true },
    { name: 'headerShowUtilityBar', label: 'Hiển thị thanh ngày giờ / mạng xã hội', type: 'checkbox', defaultValue: true },
    { name: 'headerShowSearch', label: 'Hiển thị ô tìm kiếm', type: 'checkbox', defaultValue: true },
    { name: 'headerShowContactCards', label: 'Hiển thị các ô liên hệ nhanh', type: 'checkbox', defaultValue: true },
    { name: 'headerStickyMenu', label: 'Menu bám đầu trang', type: 'checkbox', defaultValue: true },
    {
      name: 'headerUtilityAppearance',
      label: 'Thanh ngày giờ phía trên',
      type: 'group',
      fields: [
        { name: 'timePrefix', label: 'Chữ trước thời gian', type: 'text', defaultValue: '' },
        { name: 'showCalendarIcon', label: 'Hiển thị icon lịch', type: 'checkbox', defaultValue: true },
        colorField('background', 'Nền thanh trên', '#064a83'),
        colorField('timeColor', 'Màu chữ thời gian', '#FFFFFF'),
        { name: 'timeFontSize', label: 'Cỡ chữ thời gian (px)', type: 'number', min: 10, max: 22, defaultValue: 13 },
        { name: 'timeFontWeight', label: 'Độ đậm chữ thời gian', type: 'text', defaultValue: '700', admin: { placeholder: '600, 700, 800...' } },
      ],
    },
    {
      name: 'headerBrandAppearance',
      label: 'Nhận diện: Logo, tên bệnh viện, slogan và nền Header',
      type: 'group',
      admin: { description: 'Logo được chọn ở trường Logo bệnh viện phía trên. Tại đây chỉnh hiển thị, kích thước, màu chữ, căn lề, bảng màu, font chữ, hiệu ứng nổi bật và ảnh/màu nền của vùng nhận diện.' },
      fields: [
        {
          name: 'colorScheme',
          label: '🎨 Bảng màu chủ đạo (Color Scheme)',
          type: 'select',
          enumName: 'brand_color_scheme',
          defaultValue: 'custom',
          admin: {
            description: 'Chọn bảng màu phối hợp sẵn cho Tên đơn vị + Slogan. Chọn "Tuỳ chọn" để dùng màu tự chọn bên dưới.',
          },
          options: [
            { label: '🏥 Y tế xanh dương (Mặc định)', value: 'custom' },
            { label: '🌊 Navy & Vàng sang trọng', value: 'navy-gold' },
            { label: '🌿 Xanh lá y tế & Trắng tinh khiết', value: 'green-white' },
            { label: '🌙 Tối premium (Dark Mode)', value: 'dark-premium' },
            { label: '❤️ Đỏ y tế & Trắng', value: 'red-white' },
            { label: '☀️ Xanh trời & Cam ấm áp', value: 'sky-orange' },
          ],
        },
        {
          name: 'logoSize',
          label: 'Kích thước logo (px)',
          type: 'number',
          defaultValue: 66,
          min: 42,
          max: 140,
        },
        {
          name: 'titleFontSize',
          label: 'Cỡ chữ dòng “BỆNH VIỆN ĐA KHOA” (px)',
          type: 'number',
          defaultValue: 17,
          min: 12,
          max: 28,
        },
        {
          name: 'subtitleFontSize',
          label: 'Cỡ chữ dòng “KHU VỰC THỚI LAI” (px)',
          type: 'number',
          defaultValue: 13,
          min: 9,
          max: 22,
        },
        {
          name: 'nameFontFamily',
          label: '🔤 Kiểu chữ Tên đơn vị',
          type: 'select',
          enumName: 'brand_name_font',
          defaultValue: 'inherit',
          admin: { description: 'Font chữ riêng cho dòng tên bệnh viện. "Theo website" = dùng font hệ thống chung.' },
          options: [
            { label: 'Theo font hệ thống website', value: 'inherit' },
            { label: '"Be Vietnam Pro" – Hiện đại, chuẩn y tế Việt', value: '"Be Vietnam Pro", sans-serif' },
            { label: '"Montserrat" – Sang trọng, quốc tế', value: '"Montserrat", sans-serif' },
            { label: '"Roboto" – Khoa học, sạch sẽ', value: '"Roboto", sans-serif' },
            { label: '"Nunito" – Mềm mại, thân thiện', value: '"Nunito", sans-serif' },
            { label: '"Inter" – Tối giản, chuyên nghiệp', value: '"Inter", sans-serif' },
          ],
        },
        {
          name: 'nameFontWeight',
          label: '💪 Độ đậm chữ Tên đơn vị',
          type: 'select',
          enumName: 'brand_name_weight',
          defaultValue: '800',
          options: [
            { label: 'Bình thường (400)', value: '400' },
            { label: 'Vừa (600)', value: '600' },
            { label: 'Đậm (700)', value: '700' },
            { label: 'Rất đậm (800) – Khuyên dùng', value: '800' },
            { label: 'Siêu đậm (900)', value: '900' },
          ],
        },
        {
          name: 'nameTextEffect',
          label: '✨ Hiệu ứng nổi bật Tên đơn vị',
          type: 'select',
          enumName: 'brand_name_effect',
          defaultValue: 'none',
          admin: { description: 'Chọn hiệu ứng để tên bệnh viện nổi bật hơn trên Header.' },
          options: [
            { label: 'Bình thường (không hiệu ứng)', value: 'none' },
            { label: '🌟 Chữ gradient màu (Gradient Text)', value: 'gradient-text' },
            { label: '🔦 Đổ bóng nhẹ (Text Shadow)', value: 'shadow' },
            { label: '📌 Viền nhấn bên trái (Left Accent Border)', value: 'border-accent' },
            { label: '〰️ Gạch chân màu nhấn (Underline Accent)', value: 'underline-accent' },
            { label: '🔳 Nền nổi bật (Highlight Background)', value: 'highlight-bg' },
          ],
        },
        colorField('headerBackgroundColor', 'Màu nền thanh đầu trang', '#FFFFFF', { admin: { description: 'Nhập mã màu, ví dụ: #FFFFFF' } }),
        colorField('logoBackgroundColor', 'Màu nền khung logo', '#FFFFFF', { admin: { description: 'Nhập mã màu, ví dụ: #FFFFFF' } }),
        colorField('titleColor', 'Màu chữ dòng Bệnh viện ĐA KHOA', '#143653', { admin: { description: 'Nhập mã màu, ví dụ: #143653' } }),
        colorField('subtitleColor', 'Màu chữ dòng KHU VỰC THỚI LAI', '#0878D1', { admin: { description: 'Nhập mã màu, ví dụ: #0878D1' } }),
        {
          name: 'sloganAlign',
          label: 'Căn lề khẩu hiệu / Slogan',
          type: 'select',
          enumName: 'header_slogan_align',
          defaultValue: 'center',
          options: [
            { label: 'Căn giữa (khuyên dùng)', value: 'center' },
            { label: 'Căn trái', value: 'left' },
            { label: 'Căn phải', value: 'right' },
          ],
          admin: { description: 'Vị trí căn của câu slogan so với tên đơn vị.' },
        },
        colorField('sloganColor', 'Màu chữ slogan', '#0a9b50', { admin: { description: 'Mặc định màu xanh lá #0a9b50 hoặc xanh dương #0878D1' } }),
        { name: 'sloganFontSize', label: 'Cỡ chữ slogan (px)', type: 'number', min: 10, max: 24, defaultValue: 13 },
        {
          name: 'sloganFontWeight',
          label: '💪 Độ đậm chữ Slogan',
          type: 'select',
          enumName: 'brand_slogan_weight',
          defaultValue: '500',
          options: [
            { label: 'Mảnh (400)', value: '400' },
            { label: 'Vừa (500) – Khuyên dùng cho slogan', value: '500' },
            { label: 'Vừa đậm (600)', value: '600' },
            { label: 'Đậm (700)', value: '700' },
            { label: 'Rất đậm (800)', value: '800' },
          ],
        },
        {
          name: 'sloganItalic',
          label: '📝 In nghiêng slogan (Italic)',
          type: 'checkbox',
          defaultValue: false,
          admin: { description: 'Bật để slogan hiển thị nghiêng – phong cách khẩu hiệu truyền thống.' },
        },
        {
          name: 'sloganTextEffect',
          label: '✨ Hiệu ứng nổi bật Slogan',
          type: 'select',
          enumName: 'brand_slogan_effect',
          defaultValue: 'none',
          admin: { description: 'Chọn hiệu ứng để câu slogan nổi bật hơn.' },
          options: [
            { label: 'Bình thường (không hiệu ứng)', value: 'none' },
            { label: '🌟 Chữ gradient màu (Gradient Text)', value: 'gradient-text' },
            { label: '🔦 Đổ bóng nhẹ (Text Shadow)', value: 'shadow' },
            { label: '〰️ Gạch chân trang trí (Decorative Underline)', value: 'decorative-underline' },
            { label: '💎 Icon hoa văn hai bên (★ Slogan ★)', value: 'star-wrap' },
          ],
        },
        { name: 'showLogo', label: 'Hiển thị logo', type: 'checkbox', defaultValue: true },
        { name: 'showHospitalName', label: 'Hiển thị tên bệnh viện', type: 'checkbox', defaultValue: true },
        { name: 'backgroundImage', label: 'Ảnh nền khu vực nhận diện', type: 'upload', relationTo: 'media', admin: { description: 'Có thể chọn ảnh đã tải lên. Để trống sẽ dùng màu nền.' } },
        { name: 'backgroundSize', label: 'Kiểu phủ ảnh nền', type: 'text', defaultValue: 'cover', admin: { placeholder: 'cover hoặc contain' } },
        { name: 'backgroundPosition', label: 'Vị trí ảnh nền', type: 'text', defaultValue: 'center center', admin: { placeholder: 'center center' } },
        { name: 'backgroundOverlay', label: 'Lớp phủ trên ảnh nền', type: 'text', defaultValue: 'rgba(255,255,255,0.88)', admin: { placeholder: 'rgba(255,255,255,0.88)' } },
        { name: 'minHeight', label: 'Chiều cao tối thiểu khối nhận diện (px)', type: 'number', min: 70, max: 260, defaultValue: 110 },
      ],
    },
    {
      name: 'headerMenuAppearance',
      label: '🎨 Tùy chỉnh Menu chính & Menu thả xuống (Dropdown)',
      type: 'group',
      admin: {
        description: 'Tùy chỉnh toàn diện kích thước chữ, khoảng cách, căn lề, màu sắc thanh menu, màu menu con (dropdown), hiệu ứng chuyển động animation và font chữ.',
      },
      fields: [
        {
          type: 'collapsible',
          label: '🔤 Kích thước chữ & Font chữ Menu',
          admin: { initCollapsed: false },
          fields: [
            {
              type: 'row',
              fields: [
                {
                  name: 'fontSize',
                  label: 'Cỡ chữ menu chính (px)',
                  type: 'number',
                  min: 10,
                  max: 24,
                  defaultValue: 14,
                  admin: { width: '33%', description: 'Khuyên dùng 13 - 15px để chữ to, rõ nét và dễ nhìn.' },
                },
                {
                  name: 'fontWeight',
                  label: 'Độ đậm chữ menu chính',
                  type: 'select',
                  enumName: 'menu_font_weight',
                  dbName: 'menu_font_weight',
                  defaultValue: '700',
                  admin: { width: '33%' },
                  options: [
                    { label: 'Bình thường (400)', value: '400' },
                    { label: 'Vừa (600)', value: '600' },
                    { label: 'Đậm (700)', value: '700' },
                    { label: 'Rất đậm (800)', value: '800' },
                    { label: 'Siêu đậm (900)', value: '900' },
                  ],
                },
                {
                  name: 'textTransform',
                  label: 'Kiểu viết hoa / thường',
                  type: 'select',
                  enumName: 'menu_text_transform',
                  dbName: 'menu_text_transform',
                  defaultValue: 'uppercase',
                  admin: { width: '34%' },
                  options: [
                    { label: 'IN HOA TOÀN BỘ (UPPERCASE)', value: 'uppercase' },
                    { label: 'Chữ tiêu chuẩn bình thường (Normal)', value: 'none' },
                    { label: 'Viết Hoa Chữ Cái Đầu (Capitalize)', value: 'capitalize' },
                  ],
                },
              ],
            },
            {
              type: 'row',
              fields: [
                {
                  name: 'fontFamily',
                  label: 'Font chữ menu',
                  type: 'select',
                  enumName: 'menu_font_family',
                  dbName: 'menu_font_family',
                  defaultValue: 'inherit',
                  admin: { width: '50%' },
                  options: [
                    { label: 'Theo font hệ thống website', value: 'inherit' },
                    { label: 'Arial, sans-serif', value: 'Arial, Helvetica, sans-serif' },
                    { label: '"Segoe UI", Roboto, sans-serif', value: '"Segoe UI", Roboto, sans-serif' },
                    { label: '"Montserrat", sans-serif', value: '"Montserrat", sans-serif' },
                    { label: '"Roboto", sans-serif', value: '"Roboto", sans-serif' },
                    { label: '"Be Vietnam Pro", sans-serif', value: '"Be Vietnam Pro", sans-serif' },
                  ],
                },
                {
                  name: 'letterSpacing',
                  label: 'Khoảng cách giữa các ký tự chữ (px)',
                  type: 'number',
                  min: -2,
                  max: 5,
                  defaultValue: 0,
                  admin: { width: '50%', description: '0 là chuẩn, 0.5 - 1px tạo độ thoáng' },
                },
              ],
            },
          ],
        },
        {
          type: 'collapsible',
          label: '📐 Chiều cao, Vị trí & Khoảng cách giữa các Menu',
          admin: { initCollapsed: false },
          fields: [
            {
              type: 'row',
              fields: [
                {
                  name: 'height',
                  label: 'Chiều cao thanh menu (px)',
                  type: 'number',
                  min: 44,
                  max: 80,
                  defaultValue: 56,
                  admin: { width: '33%', description: 'Mặc định 56px' },
                },
                {
                  name: 'justifyContent',
                  label: 'Vị trí dàn hàng menu',
                  type: 'select',
                  enumName: 'menu_justify_content',
                  dbName: 'menu_justify_content',
                  defaultValue: 'space-between',
                  admin: { width: '33%' },
                  options: [
                    { label: 'Dàn đều toàn hàng (Space Between)', value: 'space-between' },
                    { label: 'Căn giữa (Center)', value: 'center' },
                    { label: 'Căn trái (Left / Flex-start)', value: 'flex-start' },
                    { label: 'Căn phải (Right / Flex-end)', value: 'flex-end' },
                    { label: 'Dàn đều có khoảng đệm (Space Around)', value: 'space-around' },
                  ],
                },
                {
                  name: 'itemSpacing',
                  label: 'Khoảng cách đệm giữa các mục (px)',
                  type: 'number',
                  min: 0,
                  max: 40,
                  defaultValue: 8,
                  admin: { width: '34%', description: 'Khoảng trống padding hai bên mỗi mục menu.' },
                },
              ],
            },
            {
              type: 'row',
              fields: [
                {
                  name: 'borderRadius',
                  label: 'Bo tròn góc thanh menu (px)',
                  type: 'number',
                  min: 0,
                  max: 30,
                  defaultValue: 0,
                  admin: { width: '50%' },
                },
                {
                  name: 'itemBorderRadius',
                  label: 'Bo tròn nền khi hover vào mục menu (px)',
                  type: 'number',
                  min: 0,
                  max: 20,
                  defaultValue: 6,
                  admin: { width: '50%' },
                },
              ],
            },
          ],
        },
        {
          type: 'collapsible',
          label: '🎨 Màu sắc Thanh Menu Chính',
          admin: { initCollapsed: false },
          fields: [
            {
              type: 'row',
              fields: [
                colorField('background', 'Màu nền thanh menu', '#075db8'),
                colorField('gradientEnd', 'Màu kết thúc gradient (nếu có)', '#006bc7'),
                colorField('textColor', 'Màu chữ menu', '#FFFFFF'),
              ],
            },
            {
              type: 'row',
              fields: [
                colorField('hoverTextColor', 'Màu chữ khi di chuột (Hover)', '#FFE272'),
                colorField('hoverBackground', 'Màu nền khi di chuột (Hover)', 'rgba(255,255,255,0.1)'),
                colorField('activeIndicatorColor', 'Màu đường gạch chân hiệu ứng', '#FFD24D'),
              ],
            },
          ],
        },
        {
          type: 'collapsible',
          label: '📂 Tùy chỉnh Menu thả xuống (Dropdown)',
          admin: { initCollapsed: false },
          fields: [
            {
              type: 'row',
              fields: [
                {
                  name: 'dropdownWidth',
                  label: 'Chiều rộng hộp menu thả xuống (px)',
                  type: 'number',
                  min: 180,
                  max: 450,
                  defaultValue: 250,
                  admin: { width: '33%' },
                },
                {
                  name: 'dropdownFontSize',
                  label: 'Cỡ chữ menu con (px)',
                  type: 'number',
                  min: 11,
                  max: 20,
                  defaultValue: 14,
                  admin: { width: '33%' },
                },
                {
                  name: 'dropdownBorderRadius',
                  label: 'Bo tròn góc hộp menu thả xuống (px)',
                  type: 'number',
                  min: 0,
                  max: 24,
                  defaultValue: 12,
                  admin: { width: '34%' },
                },
              ],
            },
            {
              type: 'row',
              fields: [
                colorField('dropdownBackground', 'Màu nền hộp menu con', '#FFFFFF'),
                colorField('dropdownTextColor', 'Màu chữ menu con', '#1e3a5f'),
                colorField('dropdownBorderColor', 'Màu đường viền hộp', '#e2e8f0'),
              ],
            },
            {
              type: 'row',
              fields: [
                colorField('dropdownHoverBackground', 'Màu nền menu con khi hover', '#f0f7ff'),
                colorField('dropdownHoverTextColor', 'Màu chữ menu con khi hover', '#075db8'),
                colorField('dropdownArrowColor', 'Màu mũi tên menu con (›)', '#94a3b8'),
              ],
            },
            {
              type: 'row',
              fields: [
                {
                  name: 'animationStyle',
                  label: 'Hiệu ứng Animation khi mở Menu con',
                  type: 'select',
                  enumName: 'menu_anim_style',
                  dbName: 'menu_anim_style',
                  defaultValue: 'slide-down',
                  admin: { width: '50%' },
                  options: [
                    { label: 'Trượt nhẹ từ trên xuống (Slide Down - Mượt mà)', value: 'slide-down' },
                    { label: 'Phóng to nhẹ (Zoom In)', value: 'zoom-in' },
                    { label: 'Mờ dần vào (Fade In)', value: 'fade-in' },
                    { label: 'Lật 3D (Flip In)', value: 'flip-in' },
                  ],
                },
                {
                  name: 'animationSpeed',
                  label: 'Tốc độ hiệu ứng Animation',
                  type: 'select',
                  enumName: 'menu_anim_speed',
                  dbName: 'menu_anim_speed',
                  defaultValue: '0.22s',
                  admin: { width: '50%' },
                  options: [
                    { label: 'Nhanh (0.15 giây)', value: '0.15s' },
                    { label: 'Tiêu chuẩn (0.22 giây)', value: '0.22s' },
                    { label: 'Êm dịu (0.35 giây)', value: '0.35s' },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      name: 'headerContactCards',
      label: 'Cấp cứu / Đặt lịch khám / Liên hệ nhanh Header',
      type: 'array',
      maxRows: 6,
      labels: { singular: 'Ô liên hệ / Nút Header', plural: 'Các ô liên hệ / Nút Header' },
      admin: {
        description: 'Tùy chỉnh toàn diện 2 ô "CẤP CỨU 24/7" và "ĐẶT LỊCH KHÁM" hoặc thêm các ô mới. Bạn có thể đổi đường link, đổi icon, màu sắc chữ, màu nền, font chữ, kích cỡ chữ và kích thước ô.',
        initCollapsed: false,
      },
      fields: [
        {
          type: 'row',
          fields: [
            { name: 'visible', label: 'Hiển thị', type: 'checkbox', defaultValue: true, admin: { width: '20%' } },
            { name: 'title', label: 'Dòng tiêu đề nhỏ', type: 'text', required: true, admin: { width: '40%', placeholder: 'VD: CẤP CỨU 24/7 hoặc ĐẶT LỊCH KHÁM' } },
            { name: 'text', label: 'Dòng nội dung chính', type: 'text', required: true, admin: { width: '40%', placeholder: 'VD: 02923686115 hoặc ĐẶT LỊCH NGAY' } },
          ],
        },
        {
          type: 'row',
          fields: [
            { name: 'href', label: 'Đường dẫn liên kết (Link)', type: 'text', admin: { width: '50%', placeholder: 'VD: tel:02923686115 hoặc /lich-kham hoặc https://medpro.vn' } },
            { name: 'extraText', label: 'Dòng chữ ghi chú phụ (nếu có)', type: 'text', admin: { width: '50%', placeholder: 'VD: Trực liên tục, Tư vấn miễn phí...' } },
          ],
        },
        {
          type: 'row',
          fields: [
            {
              name: 'iconType',
              label: 'Biểu tượng (Icon)',
              type: 'select',
              defaultValue: 'emergency',
              admin: { width: '40%' },
              options: [
                { label: '➕ Dấu thập Cấp cứu (Emergency Cross)', value: 'emergency' },
                { label: '📅 Lịch khám / Đồng hồ (Calendar)', value: 'calendar' },
                { label: '📞 Điện thoại (Phone)', value: 'phone' },
                { label: '🎧 Tổng đài / Tai nghe (Headset)', value: 'headset' },
                { label: '❤️ Trái tim y tế (Heart)', value: 'heart' },
                { label: 'ℹ️ Thông tin hỗ trợ (Info)', value: 'info' },
                { label: '🖼️ Dùng ảnh icon riêng (Upload bên dưới)', value: 'custom' },
              ],
            },
            {
              name: 'customIcon',
              label: 'Ảnh icon tự tải lên (nếu chọn icon riêng)',
              type: 'upload',
              relationTo: 'media',
              admin: { width: '35%', description: 'Tải PNG, SVG hoặc chọn ảnh có sẵn.' },
            },
            {
              name: 'hasArrow',
              label: 'Hiện mũi tên hành động (→)',
              type: 'checkbox',
              defaultValue: false,
              admin: { width: '25%' },
            },
          ],
        },
        {
          type: 'collapsible',
          label: '🎨 Tùy chỉnh màu sắc & Hiệu ứng',
          admin: { initCollapsed: true },
          fields: [
            {
              type: 'row',
              fields: [
                colorField('titleColor', 'Màu chữ tiêu đề', '#273B4C'),
                colorField('textColor', 'Màu chữ nội dung', '#0756B4'),
                colorField('extraTextColor', 'Màu chữ phụ', '#557082'),
              ],
            },
            {
              type: 'row',
              fields: [
                colorField('background', 'Màu nền ô', '#FFFFFF'),
                colorField('borderColor', 'Màu đường viền ô', '#E1E7EC'),
              ],
            },
            {
              type: 'row',
              fields: [
                colorField('iconColor', 'Màu biểu tượng (Icon)', '#075EC2'),
                colorField('iconBackground', 'Màu nền tròn biểu tượng', '#EAF5FF'),
              ],
            },
          ],
        },
        {
          type: 'collapsible',
          label: '🔤 Tùy chỉnh Font chữ & Kích thước hiển thị',
          admin: { initCollapsed: true },
          fields: [
            {
              type: 'row',
              fields: [
                {
                  name: 'fontFamily',
                  label: 'Kiểu font chữ',
                  type: 'select',
                  defaultValue: 'inherit',
                  admin: { width: '50%' },
                  options: [
                    { label: 'Theo font hệ thống website', value: 'inherit' },
                    { label: 'Arial, sans-serif', value: 'Arial, Helvetica, sans-serif' },
                    { label: '"Segoe UI", Roboto, sans-serif', value: '"Segoe UI", Roboto, sans-serif' },
                    { label: '"Montserrat", sans-serif', value: '"Montserrat", sans-serif' },
                    { label: '"Roboto", sans-serif', value: '"Roboto", sans-serif' },
                    { label: '"Be Vietnam Pro", sans-serif', value: '"Be Vietnam Pro", sans-serif' },
                  ],
                },
                {
                  name: 'fontWeight',
                  label: 'Độ đậm nội dung chính',
                  type: 'select',
                  defaultValue: '800',
                  admin: { width: '50%' },
                  options: [
                    { label: 'Bình thường (400)', value: '400' },
                    { label: 'Vừa (600)', value: '600' },
                    { label: 'Đậm (700)', value: '700' },
                    { label: 'Rất đậm (800)', value: '800' },
                    { label: 'Siêu đậm (900)', value: '900' },
                  ],
                },
              ],
            },
            {
              type: 'row',
              fields: [
                { name: 'titleFontSize', label: 'Cỡ chữ tiêu đề (px)', type: 'number', min: 8, max: 30, defaultValue: 11, admin: { width: '33%' } },
                { name: 'textFontSize', label: 'Cỡ chữ nội dung chính (px)', type: 'number', min: 10, max: 40, defaultValue: 17, admin: { width: '33%' } },
                { name: 'iconSize', label: 'Kích cỡ icon (px)', type: 'number', min: 28, max: 64, defaultValue: 46, admin: { width: '34%' } },
              ],
            },
            {
              type: 'row',
              fields: [
                { name: 'minWidth', label: 'Chiều rộng tối thiểu ô (px)', type: 'number', min: 140, max: 400, defaultValue: 220, admin: { width: '50%' } },
                { name: 'borderRadius', label: 'Bo tròn góc ô (px)', type: 'number', min: 0, max: 50, defaultValue: 16, admin: { width: '50%' } },
              ],
            },
          ],
        },
      ],
    },
    {
      name: 'headerSocialLinks',
      label: 'Icon mạng xã hội dùng chung Header + Footer',
      type: 'array',
      maxRows: 8,
      labels: { singular: 'Mạng xã hội', plural: 'Mạng xã hội' },
      admin: { description: 'Đây là nơi quản lý DUY NHẤT Facebook, Zalo, YouTube, TikTok trên giao diện. Header và Footer dùng chung danh sách này. Có thể tải icon riêng cho từng mạng.' },
      fields: [
        { name: 'visible', label: 'Hiển thị', type: 'checkbox', defaultValue: true },
        { name: 'platform', label: 'Loại', type: 'text', required: true, admin: { placeholder: 'facebook, zalo, youtube, tiktok hoặc custom' } },
        { name: 'label', label: 'Tên hiển thị', type: 'text' },
        { name: 'url', label: 'Liên kết', type: 'text', required: true },
        { name: 'customIcon', label: 'Đổi icon / Tải icon riêng', type: 'upload', relationTo: 'media', admin: { description: 'Để trống sẽ dùng icon chuẩn tích hợp. Chọn ảnh để thay icon Facebook/Zalo/YouTube/TikTok bằng icon riêng.' } },
      ],
    },
    { name: 'tiktokUrl', label: 'Liên kết TikTok (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    {
      name: 'slogan',
      label: 'Nội dung chữ chạy (Dữ liệu cũ)',
      type: 'text',
      admin: {
        hidden: true,
      },
    },
    {
      name: 'tickerAppearance',
      label: 'Cài đặt thanh chữ chạy (Marquee)',
      type: 'group',
      fields: [
        { name: 'enabled', label: 'Hiển thị thanh chữ chạy', type: 'checkbox', defaultValue: true },
        {
          name: 'text',
          label: 'Nội dung chữ chạy trên website',
          type: 'text',
          defaultValue: 'Chào mừng đến với Cổng thông tin Bệnh viện Đa khoa khu vực Thới Lai',
          admin: {
            description: 'Dòng chữ này chạy ngang liên tục ngay dưới thanh menu chính.',
            placeholder: 'Nhập nội dung chữ chạy…',
          },
        },
        colorField('backgroundColor', 'Màu nền', '#FF9F2F', { admin: { description: 'Nhập mã màu, ví dụ: #FF9F2F' } }),
        colorField('textColor', 'Màu chữ', '#FFFFFF', { admin: { description: 'Nhập mã màu, ví dụ: #FFFFFF' } }),
        {
          name: 'fontSize',
          label: 'Kích thước chữ (px)',
          type: 'number',
          defaultValue: 13,
          min: 10,
          max: 24,
        },
        {
          name: 'duration',
          label: 'Thời gian chạy hết một vòng (giây)',
          type: 'number',
          defaultValue: 24,
          min: 8,
          max: 120,
          admin: { description: 'Số nhỏ chạy nhanh hơn; số lớn chạy chậm hơn.' },
        },
      ],
    },
    {
      name: 'headerBanner',
      label: 'Banner đầu trang (nằm trên menu)',
      type: 'upload',
      relationTo: 'media',
      admin: { description: 'Tải banner mới hoặc chọn lại banner đã có trong thư viện. Nếu chưa chọn, website dùng banner có sẵn trong hệ thống.' },
    },
    {
      name: 'headerBannerWidth',
      label: 'Chiều rộng banner đầu trang (px)',
      type: 'number',
      min: 600,
      max: 3000,
      defaultValue: 1300,
      admin: { description: 'Nên dùng 1300 px. Ảnh banner tải lên nên có đúng kích thước 1300 × 200 px.' },
    },
    {
      name: 'headerBannerHeight',
      label: 'Chiều cao banner đầu trang (px)',
      type: 'number',
      min: 80,
      max: 360,
      defaultValue: 200,
      admin: { description: 'Nên dùng 200 px để khớp banner chuẩn 1300 × 200 px.' },
    },
    { name: 'favicon', label: 'Biểu tượng trình duyệt', type: 'upload', relationTo: 'media', admin: { description: 'Tải mới hoặc chọn lại hình đã có trong Thư viện Tệp & Hình ảnh.' } },
    { name: 'hotline', label: 'Hotline bệnh viện', type: 'text' },
    { name: 'emergencyHotline', label: 'Hotline cấp cứu', type: 'text' },
    { name: 'email', label: 'Email', type: 'email' },
    { name: 'address', label: 'Địa chỉ', type: 'textarea' },
    { name: 'workingHours', label: 'Thời gian làm việc', type: 'text' },
    { name: 'medproUrl', label: 'Liên kết đặt khám Medpro', type: 'text' },
    { name: 'zaloUrl', label: 'Liên kết Zalo (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    { name: 'facebookUrl', label: 'Liên kết Facebook (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    { name: 'youtubeUrl', label: 'Liên kết YouTube (dữ liệu cũ)', type: 'text', admin: { hidden: true } },
    {
      name: 'googleMapsEmbed',
      label: 'Bản đồ Google Maps',
      type: 'textarea',
      admin: {
        description: 'Dán toàn bộ mã <iframe> hoặc URL nhúng Google Maps (URL có /embed hoặc output=embed). Để trống, website tự hiển thị bản đồ theo Địa chỉ ở trên.',
      },
    },
    { name: 'footerText', label: 'Nội dung chân trang', type: 'textarea' },
    {
      name: 'servicePricePage',
      label: 'Trang Bảng giá dịch vụ',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, thông báo lưu ý BHYT, ô tìm kiếm và số dịch vụ hiển thị trên mỗi trang.' },
      fields: [
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Bảng giá dịch vụ' },
        { name: 'description', label: 'Mô tả', type: 'textarea', defaultValue: 'Tra cứu giá BHYT và giá dịch vụ được cập nhật trực tiếp từ hệ thống quản trị.' },
        {
          name: 'showNoticeBanner',
          label: 'Bật thông báo / lưu ý bảng giá trên đầu trang',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'noticeTitle',
          label: 'Tiêu đề lưu ý bảng giá',
          type: 'text',
          defaultValue: 'Lưu ý về giá khám chữa bệnh BHYT và Viện phí',
        },
        {
          name: 'noticeContent',
          label: 'Nội dung lưu ý (Hỗ trợ Enter xuống dòng)',
          type: 'textarea',
          defaultValue: '• Bảng giá dịch vụ khám bệnh, chữa bệnh được thực hiện công khai theo đúng quy định hiện hành của Bộ Y tế.\n• Người bệnh có thẻ BHYT đúng tuyến hoặc thông tuyến được hưởng đầy đủ quyền lợi chi trả theo quy định.\n• Các dịch vụ kỹ thuật cao, dịch vụ theo yêu cầu được tư vấn rõ ràng trước khi thực hiện.',
        },
        {
          name: 'noticeAlign',
          label: 'Canh lề bảng lưu ý',
          type: 'select',
          dbName: 'sp_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        { name: 'searchPlaceholder', label: 'Chữ gợi ý trong ô tìm kiếm', type: 'text', defaultValue: 'Nhập tên, mã dịch vụ, nhóm hoặc ghi chú…' },
        { name: 'rowsPerPage', label: 'Số dòng hiển thị trên mỗi trang', type: 'select', defaultValue: '40', required: true, options: [
          { label: '40 dịch vụ / trang', value: '40' },
          { label: '50 dịch vụ / trang', value: '50' },
        ] },
        { name: 'searchNotes', label: 'Cho phép tìm trong cột Ghi chú', type: 'checkbox', defaultValue: true },
        { name: 'emptyText', label: 'Thông báo khi không có kết quả', type: 'text', defaultValue: 'Không tìm thấy dịch vụ phù hợp.' },
      ],
    },
    {
      name: 'vaccinationPage',
      label: 'Trang Tiêm chủng vắc xin',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, banner thông báo và lưu ý an toàn tiêm chủng trên trang /tiem-chung.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'TIÊM NGỪA AN TOÀN' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Thông tin tiêm ngừa' },
        { name: 'description', label: 'Mô tả', type: 'textarea', defaultValue: 'Theo dõi thông báo lịch tiêm, các đợt tiêm và danh mục vắc xin tại bệnh viện.' },
        {
          name: 'showNoticeBanner',
          label: 'Bật thông báo lưu ý tiêm chủng',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'noticeTitle',
          label: 'Tiêu đề lưu ý tiêm chủng',
          type: 'text',
          defaultValue: 'Quy trình và An toàn Tiêm chủng tại Bệnh viện',
        },
        {
          name: 'noticeContent',
          label: 'Nội dung lưu ý (Hỗ trợ Enter xuống dòng)',
          type: 'textarea',
          defaultValue: '• Người đến tiêm chủng được khám sàng lọc trước tiêm và tư vấn chỉ định vắc xin phù hợp.\n• Theo dõi sức khỏe ít nhất 30 phút sau tiêm tại phòng theo dõi của bệnh viện.\n• Vui lòng mang theo sổ tiêm chủng hoặc ứng dụng tiêm chủng điện tử khi đến tiêm.',
        },
        {
          name: 'noticeAlign',
          label: 'Canh lề bảng lưu ý',
          type: 'select',
          dbName: 'vc_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    {
      name: 'examinationFlowPage',
      label: 'Trang Quy trình khám bệnh',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả, thông báo lưu ý và cấu hình hiển thị trên trang /quy-trinh-kham-benh.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'HƯỚNG DẪN DÀNH CHO NGƯỜI BỆNH' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Quy trình Khám chữa bệnh' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Sơ đồ và các bước hướng dẫn người bệnh khi đến thăm khám có thẻ BHYT, khám thu phí dịch vụ hoặc tiếp nhận cấp cứu tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        {
          name: 'showNoticeBanner',
          label: 'Bật thông báo đầu trang quy trình',
          type: 'checkbox',
          defaultValue: false,
        },
        {
          name: 'noticeTitle',
          label: 'Tiêu đề thông báo lưu ý',
          type: 'text',
          defaultValue: 'Lưu ý khi đến khám tại Bệnh viện Đa khoa Khu vực Thới Lai',
        },
        {
          name: 'noticeContent',
          label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)',
          type: 'textarea',
          defaultValue: '• Người bệnh có thẻ BHYT đúng tuyến hoặc thông tuyến được hưởng đầy đủ quyền lợi chi trả.\n• Bệnh viện tiếp nhận khám sớm từ 06:30 tại các khoa chuyên môn trọng điểm.\n• Người cao tuổi, phụ nữ mang thai và trẻ nhỏ được cấp số ưu tiên tiếp đón.',
        },
        {
          name: 'noticeAlign',
          label: 'Canh lề bảng lưu ý',
          type: 'select',
          enumName: 'enum_flow_not_align',
          dbName: 'notice_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'showChecklist',
          label: 'Hiển thị khối giấy tờ cần chuẩn bị',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showPriority',
          label: 'Hiển thị khối đối tượng ưu tiên tiếp đón',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showSupportBanner',
          label: 'Hiển thị banner đặt hẹn & cấp cứu',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'flowTabs',
          label: 'Danh sách các Tab Quy trình khám bệnh',
          type: 'array',
          dbName: 'ef_tabs',
          labels: { singular: 'Tab quy trình', plural: 'Các tab quy trình' },
          admin: { description: 'Tùy chỉnh bật/tắt từng tab quy trình (Khám BHYT, Khám Dịch vụ, Cấp cứu 24/24...) và chỉnh sửa chi tiết các bước trong mỗi tab.' },
          fields: [
            { name: 'enabled', label: 'Bật hiển thị Tab này', type: 'checkbox', defaultValue: true },
            { name: 'id', label: 'Mã Tab (id)', type: 'text', required: true, admin: { placeholder: 'bhyt, dich-vu, cap-cuu...' } },
            { name: 'label', label: 'Tên hiển thị trên nút Tab', type: 'text', required: true },
            { name: 'badgeText', label: 'Dòng nhãn nổi bật (Badge)', type: 'text' },
            { name: 'title', label: 'Tiêu đề quy trình', type: 'text', required: true },
            { name: 'summary', label: 'Tóm tắt quy trình (Hỗ trợ Enter)', type: 'textarea', required: true },
            {
              name: 'steps',
              label: 'Các bước thực hiện trong quy trình',
              type: 'array',
              dbName: 'ef_steps',
              labels: { singular: 'Bước quy trình', plural: 'Các bước quy trình' },
              fields: [
                { name: 'enabled', label: 'Bật bước này', type: 'checkbox', defaultValue: true },
                { name: 'step', label: 'Số thứ tự bước', type: 'number', required: true },
                { name: 'title', label: 'Tiêu đề bước', type: 'text', required: true },
                { name: 'location', label: 'Địa điểm / Phòng thực hiện', type: 'text', required: true },
                { name: 'timeEstimate', label: 'Thời gian ước tính', type: 'text', admin: { placeholder: 'VD: 3 – 5 phút' } },
                { name: 'desc', label: 'Mô tả chi tiết bước', type: 'textarea', required: true },
                { name: 'actions', label: 'Các hành động cụ thể (Mỗi dòng 1 gạch đầu dòng, nhấn Enter để xuống dòng)', type: 'textarea' },
                { name: 'note', label: 'Ghi chú quan trọng (Lưu ý)', type: 'text' },
                { name: 'isHighlight', label: 'Làm nổi bật bước này', type: 'checkbox', defaultValue: false },
                { name: 'isEmergency', label: 'Đánh dấu bước khẩn cấp / cấp cứu', type: 'checkbox', defaultValue: false },
              ],
            },
          ],
        },
        {
          name: 'checklists',
          label: 'Danh sách giấy tờ cần chuẩn bị (Checklist)',
          type: 'array',
          dbName: 'ef_checks',
          labels: { singular: 'Giấy tờ cần chuẩn bị', plural: 'Các giấy tờ cần chuẩn bị' },
          admin: { description: 'Tùy chỉnh bật/tắt hoặc chỉnh sửa nội dung từng loại giấy tờ cần mang theo.' },
          fields: [
            { name: 'enabled', label: 'Bật hiển thị', type: 'checkbox', defaultValue: true },
            { name: 'title', label: 'Tên giấy tờ', type: 'text', required: true },
            { name: 'desc', label: 'Mô tả chi tiết', type: 'textarea', required: true },
            { name: 'icon', label: 'Biểu tượng (id, card, file, medical)', type: 'text', defaultValue: 'id' },
          ],
        },
        {
          name: 'priorities',
          label: 'Danh sách đối tượng ưu tiên tiếp đón',
          type: 'array',
          dbName: 'ef_prios',
          labels: { singular: 'Đối tượng ưu tiên', plural: 'Các đối tượng ưu tiên' },
          fields: [
            { name: 'enabled', label: 'Bật hiển thị', type: 'checkbox', defaultValue: true },
            { name: 'text', label: 'Mô tả đối tượng ưu tiên', type: 'text', required: true },
          ],
        },
      ],
    },
    {
      name: 'qualityPage',
      label: 'Trang Chất lượng bệnh viện',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả, thông báo lưu ý và cấu hình hiển thị trên trang /chat-luong-benh-vien.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'QUẢN LÝ CHẤT LƯỢNG & AN TOÀN NGƯỜI BỆNH' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Chất lượng Bệnh viện' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Bộ chỉ số đo lường 83 tiêu chí chất lượng, kết quả khảo sát sự hài lòng và các chương trình cải tiến liên tục tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        {
          name: 'showNoticeBanner',
          label: 'Bật thông báo lưu ý đầu trang',
          type: 'checkbox',
          defaultValue: false,
        },
        {
          name: 'noticeTitle',
          label: 'Tiêu đề thông báo lưu ý',
          type: 'text',
          defaultValue: 'Cam kết chất lượng phục vụ của Bệnh viện Đa khoa Khu vực Thới Lai',
        },
        {
          name: 'noticeContent',
          label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)',
          type: 'textarea',
          defaultValue: '• Lấy người bệnh làm trung tâm phục vụ, đảm bảo an toàn và quyền lợi người bệnh.\n• Đánh giá chất lượng định kỳ theo Bộ 83 Tiêu chí của Bộ Y tế.\n• Mọi ý kiến đóng góp được Ban Giám đốc tiếp nhận và cải tiến liên tục.',
        },
        {
          name: 'noticeAlign',
          label: 'Canh lề bảng lưu ý',
          type: 'select',
          enumName: 'enum_quality_not_align',
          dbName: 'notice_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'showQualityCards',
          label: 'Hiển thị các chỉ số chất lượng chính',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showDimensions',
          label: 'Hiển thị 5 nhóm tiêu chuẩn Bộ Y tế',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showPrograms',
          label: 'Hiển thị các chương trình cải tiến',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showFeedbackBox',
          label: 'Hiển thị khối khảo sát & tiếp nhận ý kiến',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'statCards',
          label: '4 Thẻ chỉ số chất lượng chính đầu trang',
          type: 'array',
          dbName: 'qp_stats',
          labels: { singular: 'Thẻ chỉ số', plural: 'Các thẻ chỉ số' },
          admin: { description: 'Tùy chỉnh số liệu, đơn vị và nhãn của 4 thẻ thống kê chất lượng.' },
          fields: [
            { name: 'enabled', label: 'Bật thẻ này', type: 'checkbox', defaultValue: true },
            { name: 'val', label: 'Giá trị số (VD: 4.22, 94.8, 83, 100)', type: 'text', required: true },
            { name: 'unit', label: 'Đơn vị (VD: / 5.0, %, tiêu chí)', type: 'text' },
            { name: 'label', label: 'Nhãn mô tả chỉ số', type: 'text', required: true },
          ],
        },
        {
          name: 'dimensions',
          label: '5 Nhóm tiêu chuẩn Bộ 83 Tiêu chí Bộ Y tế',
          type: 'array',
          dbName: 'qp_dims',
          labels: { singular: 'Nhóm tiêu chuẩn', plural: 'Các nhóm tiêu chuẩn' },
          admin: { description: 'Chỉnh sửa điểm số, tỷ lệ % và mô tả từng phần tiêu chuẩn (Phần A -> E).' },
          fields: [
            { name: 'enabled', label: 'Bật nhóm này', type: 'checkbox', defaultValue: true },
            { name: 'code', label: 'Mã phần (VD: PHẦN A, PHẦN B...)', type: 'text', required: true },
            { name: 'title', label: 'Tên nhóm tiêu chuẩn', type: 'text', required: true },
            { name: 'desc', label: 'Mô tả nội dung tiêu chuẩn', type: 'textarea', required: true },
            { name: 'score', label: 'Điểm đánh giá (VD: 4.25 / 5.00)', type: 'text', required: true },
            { name: 'percent', label: 'Tỷ lệ % tiến độ thanh đo (VD: 85, 83.6...)', type: 'number', required: true },
          ],
        },
        {
          name: 'programs',
          label: 'Các chương trình cải tiến chất lượng trọng điểm',
          type: 'array',
          dbName: 'qp_progs',
          labels: { singular: 'Chương trình cải tiến', plural: 'Các chương trình cải tiến' },
          admin: { description: 'Chỉnh sửa biểu tượng, tiêu đề, mô tả và các gạch đầu dòng điểm nổi bật.' },
          fields: [
            { name: 'enabled', label: 'Bật chương trình này', type: 'checkbox', defaultValue: true },
            {
              name: 'iconType',
              label: 'Kiểu biểu tượng / màu sắc',
              type: 'select',
              dbName: 'qp_icon_t',
              defaultValue: 'blue',
              options: [
                { label: 'Xanh dương (Chuyển đổi số)', value: 'blue' },
                { label: 'Xanh lá (An toàn & Khử khuẩn)', value: 'green' },
                { label: 'Hổ phách (Văn hóa giao tiếp)', value: 'amber' },
              ],
            },
            { name: 'title', label: 'Tên chương trình cải tiến', type: 'text', required: true },
            { name: 'desc', label: 'Mô tả chi tiết chương trình', type: 'textarea', required: true },
            { name: 'highlights', label: 'Điểm nổi bật (Mỗi dòng 1 gạch đầu dòng, nhấn Enter để xuống dòng)', type: 'textarea' },
          ],
        },
      ],
    },
    {
      name: 'surveyPage',
      label: 'Trang Khảo sát ý kiến',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /khao-sat.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHĂM SÓC NGƯỜI BỆNH & KHẢO SÁT' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Khảo sát Ý kiến & Sự hài lòng' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Bệnh viện Đa khoa Khu vực Thới Lai trân trọng từng ý kiến đóng góp của người bệnh và thân nhân để không ngừng nâng cao y đức, văn hóa phục vụ và chất lượng điều trị.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo lưu ý', type: 'text', defaultValue: 'Quy chế khảo sát ẩn danh' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter)', type: 'textarea', defaultValue: 'Mọi câu trả lời của quý người bệnh hoàn toàn bảo mật và không ảnh hưởng đến quá trình điều trị.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'infoBoxes',
          label: '3 Ô nguyên tắc / lưu ý khảo sát',
          type: 'array',
          dbName: 'sv_boxes',
          labels: { singular: 'Ô thông tin', plural: 'Các ô thông tin' },
          admin: { description: 'Tùy chỉnh bật/tắt, biểu tượng, tiêu đề và mô tả của 3 ô thông tin trên trang /khao-sat.' },
          fields: [
            { name: 'enabled', label: 'Bật ô này', type: 'checkbox', defaultValue: true },
            { name: 'icon', label: 'Biểu tượng (Icon / Emoji)', type: 'text', defaultValue: '🛡️' },
            { name: 'title', label: 'Tiêu đề ô', type: 'text', required: true },
            { name: 'desc', label: 'Nội dung chi tiết', type: 'textarea', required: true },
          ],
        },
      ],
    },
    {
      name: 'faqPage',
      label: 'Trang Hỏi đáp y tế (FAQ)',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /hoi-dap.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHĂM SÓC NGƯỜI BỆNH & GIẢI ĐÁP' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Hỏi đáp Y tế & Câu hỏi thường gặp' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Tổng hợp các giải đáp chính xác, nhanh chóng nhất về chính sách khám chữa bệnh, quyền lợi bảo hiểm và hướng dẫn thủ tục tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo lưu ý', type: 'text', defaultValue: 'Giải đáp thắc mắc người bệnh' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter)', type: 'textarea', defaultValue: 'Nếu chưa tìm thấy thông tin cần biết, quý vị có thể đặt câu hỏi trực tuyến hoặc gọi hotline 02923686115.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    {
      name: 'formsPage',
      label: 'Trang Biểu mẫu điện tử',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /bieu-mau.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHĂM SÓC NGƯỜI BỆNH & THỦ TỤC ĐIỆN TỬ' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Biểu mẫu Điện tử & Đăng ký' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Hệ thống biểu mẫu hành chính số hóa giúp người bệnh đăng ký thủ tục nhanh chóng, tiết kiệm thời gian chờ đợi tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo lưu ý', type: 'text', defaultValue: 'Lưu ý khi điền biểu mẫu trực tuyến' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter)', type: 'textarea', defaultValue: 'Vui lòng cung cấp đúng số điện thoại để nhận mã xác nhận tiếp nhận từ bệnh viện.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'infoBoxes',
          label: '3 Ô tiện ích / hướng dẫn biểu mẫu',
          type: 'array',
          dbName: 'fm_boxes',
          labels: { singular: 'Ô tiện ích', plural: 'Các ô tiện ích' },
          admin: { description: 'Tùy chỉnh bật/tắt, biểu tượng, tiêu đề và mô tả của 3 ô thông tin trên trang /bieu-mau.' },
          fields: [
            { name: 'enabled', label: 'Bật ô này', type: 'checkbox', defaultValue: true },
            { name: 'icon', label: 'Biểu tượng (Icon / Emoji)', type: 'text', defaultValue: '⚡' },
            { name: 'title', label: 'Tiêu đề ô', type: 'text', required: true },
            { name: 'desc', label: 'Nội dung chi tiết', type: 'textarea', required: true },
          ],
        },
      ],
    },
    // ─── TRANG DÀNH CHO NGƯỜI BỆNH (PORTAL) ─────────────────────────────────
    {
      name: 'patientPortalPage',
      label: 'Trang Dành cho người bệnh (Portal)',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /danh-cho-nguoi-benh.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CỔNG TIỆN ÍCH NGƯỜI BỆNH' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Dành cho Người bệnh' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Tổng hợp đầy đủ các tiện ích, hướng dẫn và dịch vụ hỗ trợ người bệnh tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo', type: 'text', defaultValue: 'Thông báo dành cho người bệnh' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)', type: 'textarea', defaultValue: '• Vui lòng mang theo CCCD/CMND và thẻ BHYT khi đến khám.\n• Đặt lịch trực tuyến qua ứng dụng Medpro để được phục vụ ưu tiên.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'pp_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    // ─── TRANG GÓP Ý – PHẢN ÁNH CHẤT LƯỢNG ──────────────────────────────────
    {
      name: 'feedbackPage',
      label: 'Trang Góp ý – Phản ánh chất lượng',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả, thông báo lưu ý và 3 ô thông tin hotline/tra cứu/bảo mật trên trang /gop-y và /gop-y/tra-cuu.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHĂM SÓC NGƯỜI BỆNH & TIẾP NHẬN Ý KIẾN' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Góp ý – Phản ánh Chất lượng' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Mọi ý kiến đóng góp, phản ánh hoặc khen ngợi của quý vị đều được Ban Giám đốc tiếp nhận trực tiếp và giải quyết minh bạch, có mã theo dõi tiến độ.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo lưu ý', type: 'text', defaultValue: 'Quy trình tiếp nhận phản ánh' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter)', type: 'textarea', defaultValue: '• Ban Giám đốc tiếp nhận trực tiếp mọi ý kiến phản ánh của người bệnh và thân nhân.\n• Mọi phản ánh đều được cấp mã tra cứu tiến độ xử lý minh bạch.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'fb_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'infoBoxes',
          label: '3 Ô thông tin Hotline / Mã tra cứu / Bảo mật',
          type: 'array',
          dbName: 'fb_boxes',
          labels: { singular: 'Ô thông tin', plural: 'Các ô thông tin' },
          fields: [
            { name: 'enabled', label: 'Bật ô này', type: 'checkbox', defaultValue: true },
            { name: 'icon', label: 'Biểu tượng (Icon / Emoji)', type: 'text', defaultValue: '📞' },
            { name: 'title', label: 'Tiêu đề ô', type: 'text', required: true },
            { name: 'desc', label: 'Nội dung chi tiết (Hỗ trợ {{HOTLINE}} và {{EMERGENCY_HOTLINE}})', type: 'textarea', required: true },
          ],
        },
      ],
    },
    // ─── TRANG HƯỚNG DẪN ĐIỀU TRỊ NỘI TRÚ ────────────────────────────────────
    {
      name: 'inpatientPage',
      label: 'Trang Hướng dẫn Điều trị Nội trú',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả, thông báo, các bước nhập viện, đồ dùng cần mang, giờ thăm bệnh và chế độ dinh dưỡng trên trang /dieu-tri-noi-tru.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'HƯỚNG DẪN DÀNH CHO NGƯỜI BỆNH' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Hướng dẫn Điều trị Nội trú' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Thông tin chi tiết về thủ tục nhập viện, đồ dùng cần chuẩn bị, quy định buồng bệnh, giờ thăm bệnh và chế độ dinh dưỡng tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: true },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo lưu ý', type: 'text', defaultValue: 'Nội quy buồng bệnh và an toàn người bệnh' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)', type: 'textarea', defaultValue: '• Mỗi người bệnh được tối đa 01 người thân ở lại chăm sóc và phải đeo thẻ nuôi bệnh.\n• Giữ gìn trật tự chung, tuyệt đối không hút thuốc lá trong khuôn viên bệnh viện.\n• Bệnh viện phục vụ chế độ ăn bệnh lý đạt chuẩn an toàn vệ sinh thực phẩm.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'ip_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'admissionSteps',
          label: 'Quy trình các bước nhập viện',
          type: 'array',
          dbName: 'ip_steps',
          labels: { singular: 'Bước nhập viện', plural: 'Các bước nhập viện' },
          fields: [
            { name: 'enabled', label: 'Bật bước này', type: 'checkbox', defaultValue: true },
            { name: 'step', label: 'Số thứ tự', type: 'number', required: true },
            { name: 'title', label: 'Tiêu đề bước', type: 'text', required: true },
            { name: 'location', label: 'Địa điểm / Phòng ban', type: 'text', required: true },
            { name: 'desc', label: 'Nội dung hướng dẫn chi tiết', type: 'textarea', required: true },
            { name: 'note', label: 'Lưu ý cần nhớ (nếu có)', type: 'text' },
          ],
        },
        {
          name: 'visitingHours',
          label: 'Khung giờ thăm bệnh thân nhân',
          type: 'array',
          dbName: 'ip_hours',
          labels: { singular: 'Khung giờ thăm', plural: 'Các khung giờ thăm' },
          fields: [
            { name: 'enabled', label: 'Bật khung giờ này', type: 'checkbox', defaultValue: true },
            { name: 'session', label: 'Buổi thăm (Sáng/Trưa/Chiều tối)', type: 'text', required: true },
            { name: 'timeRange', label: 'Khung giờ (Ví dụ: 06:00 - 07:00)', type: 'text', required: true },
            { name: 'note', label: 'Ghi chú thêm', type: 'text' },
          ],
        },
        {
          name: 'belongingsChecklist',
          label: 'Danh mục đồ dùng cần mang theo & BV cấp phát',
          type: 'array',
          dbName: 'ip_items',
          labels: { singular: 'Mục đồ dùng', plural: 'Các mục đồ dùng' },
          fields: [
            { name: 'enabled', label: 'Bật mục này', type: 'checkbox', defaultValue: true },
            { name: 'icon', label: 'Biểu tượng (Icon / Emoji)', type: 'text', defaultValue: '🎒' },
            { name: 'category', label: 'Phân loại (Người bệnh mang theo / BV cung cấp)', type: 'text', required: true },
            { name: 'title', label: 'Tên vật dụng / Giấy tờ', type: 'text', required: true },
            { name: 'desc', label: 'Chi tiết hướng dẫn', type: 'textarea', required: true },
          ],
        },
      ],
    },
    // ─── TRANG GÓI KHÁM SỨC KHỎE & TẦM SOÁT ─────────────────────────────────
    {
      name: 'checkupPackagesPage',
      label: 'Trang Gói khám sức khỏe & Tầm soát',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả, thông báo và danh sách các gói khám sức khỏe trên trang /goi-kham.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHỦ ĐỘNG BẢO VỆ SỨC KHỎE' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Gói Khám Sức khỏe & Tầm soát Bệnh lý' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Các gói khám sức khỏe tổng quát, tầm soát bệnh lý mạn tính và khám cấp giấy chứng nhận sức khỏe với chi phí minh bạch, chuẩn y tế tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: true },
        { name: 'noticeTitle', label: 'Tiêu đề lưu ý trước khi khám', type: 'text', defaultValue: 'Lưu ý quan trọng trước khi đi khám sức khỏe' },
        { name: 'noticeContent', label: 'Nội dung lưu ý (Hỗ trợ Enter xuống dòng)', type: 'textarea', defaultValue: '• Nhịn ăn sáng từ 8 - 10 tiếng nếu gói khám có xét nghiệm đường huyết, mỡ máu.\n• Uống nhiều nước lọc và nhịn tiểu trước khi làm siêu âm ổ bụng.\n• Không sử dụng rượu bia, chất kích thích 24 giờ trước khi khám.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'pkg_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'packages',
          label: 'Danh sách các gói khám sức khỏe',
          type: 'array',
          dbName: 'chk_pkgs',
          labels: { singular: 'Gói khám', plural: 'Các gói khám' },
          fields: [
            { name: 'enabled', label: 'Bật gói khám này', type: 'checkbox', defaultValue: true },
            { name: 'badge', label: 'Huy hiệu nổi bật (Ví dụ: Phổ biến, Tiết kiệm...)', type: 'text' },
            { name: 'title', label: 'Tên gói khám', type: 'text', required: true },
            { name: 'targetUser', label: 'Đối tượng phù hợp', type: 'text', required: true },
            { name: 'priceText', label: 'Giá niêm yết (Ví dụ: 850.000 đ hoặc Liên hệ)', type: 'text', required: true },
            { name: 'desc', label: 'Mô tả tóm tắt gói khám', type: 'textarea', required: true },
            { name: 'features', label: 'Danh mục kỹ thuật trong gói (Mỗi dòng 1 mục - Hỗ trợ Enter)', type: 'textarea', required: true },
            { name: 'buttonText', label: 'Chữ trên nút', type: 'text', defaultValue: 'Đăng ký gói khám' },
            { name: 'buttonLink', label: 'Đường dẫn nút (URL)', type: 'text', defaultValue: '/dat-lich-kham' },
          ],
        },
      ],
    },
    // ─── TRANG SƠ ĐỒ CHỈ DẪN KHOA PHÒNG & BẢN ĐỒ ─────────────────────────────
    {
      name: 'hospitalMapPage',
      label: 'Trang Sơ đồ & Chỉ dẫn Khoa/Phòng',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả, thông báo, sơ đồ phân tầng và các khu vực tiện ích công cộng trên trang /so-do-benh-vien.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHỈ DẪN TIẾP ĐÓN TIỆN ÍCH' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Sơ đồ Chỉ dẫn Khoa / Phòng & Tiện ích' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Bản đồ chỉ dẫn phân tầng các khoa phòng chuyên môn, phòng khám chức năng và các khu vực dịch vụ công cộng tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: true },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo tiếp đón', type: 'text', defaultValue: 'Bàn Hướng dẫn & Hỗ trợ người bệnh di chuyển' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter)', type: 'textarea', defaultValue: '• Tại sảnh chính Tầng trệt có Tổ Chăm sóc khách hàng trực tiếp chỉ dẫn và xe lăn hỗ trợ người già, người khuyết tật.\n• Thang máy vận chuyển ưu tiên người bệnh nội trú và xe cáng cấp cứu.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'map_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'floors',
          label: 'Danh sách các tầng & khoa phòng chức năng',
          type: 'array',
          dbName: 'hm_floors',
          labels: { singular: 'Tầng / Khu vực', plural: 'Các tầng / Khu vực' },
          fields: [
            { name: 'enabled', label: 'Bật tầng này', type: 'checkbox', defaultValue: true },
            { name: 'floorName', label: 'Tên tầng / Khu vực (Ví dụ: Tầng Trệt, Tầng 1...)', type: 'text', required: true },
            { name: 'overview', label: 'Chức năng tổng quát của tầng', type: 'text', required: true },
            { name: 'rooms', label: 'Danh sách khoa phòng (Mỗi dòng 1 phòng - Hỗ trợ Enter)', type: 'textarea', required: true },
          ],
        },
        {
          name: 'facilities',
          label: 'Các tiện ích công cộng phục vụ người bệnh',
          type: 'array',
          dbName: 'hm_facils',
          labels: { singular: 'Tiện ích công cộng', plural: 'Các tiện ích công cộng' },
          fields: [
            { name: 'enabled', label: 'Bật tiện ích này', type: 'checkbox', defaultValue: true },
            { name: 'icon', label: 'Biểu tượng (Icon / Emoji)', type: 'text', defaultValue: '📍' },
            { name: 'name', label: 'Tên tiện ích (Nhà thuốc, Căn tin, ATM, Bãi xe...)', type: 'text', required: true },
            { name: 'location', label: 'Vị trí cụ thể', type: 'text', required: true },
            { name: 'hours', label: 'Giờ phục vụ', type: 'text', defaultValue: '24/24 hoặc Giờ hành chính' },
            { name: 'desc', label: 'Mô tả ghi chú', type: 'textarea' },
          ],
        },
      ],
    },
    // ─── TRANG LỊCH TRỰC ─────────────────────────────────────────────────────
    {
      name: 'lichTrucPage',
      label: 'Trang Lịch trực cấp cứu',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /lich-truc.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'TRỰC 24/7' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Lịch trực Cấp cứu' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Danh sách bác sĩ, điều dưỡng trực cấp cứu 24/7 tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: true },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo', type: 'text', defaultValue: 'Đường dây cấp cứu bệnh viện' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)', type: 'textarea', defaultValue: '• Cấp cứu 24/7: Gọi ngay 02923686115.\n• Ekip trực cấp cứu sẵn sàng tiếp nhận tất cả các ngày trong tuần, kể cả ngày lễ, Tết.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'lt_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    // ─── TRANG HOẠT ĐỘNG KHOA HỌC ────────────────────────────────────────────
    {
      name: 'scienceActivityPage',
      label: 'Trang Hoạt động Khoa học',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /hoat-dong-khoa-hoc.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'NGHIÊN CỨU & HỌC THUẬT' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Hoạt động Khoa học' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Tổng hợp các hội nghị khoa học, đề tài nghiên cứu, chương trình đào tạo chuyên môn và hoạt động học thuật tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo', type: 'text', defaultValue: 'Thông báo hoạt động khoa học' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)', type: 'textarea', defaultValue: '' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'sa_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
      ],
    },
    // ─── TRANG PHÁC ĐỒ ĐIỀU TRỊ ─────────────────────────────────────────────
    {
      name: 'clinicalProtocolPage',
      label: 'Trang Phác đồ điều trị',
      type: 'group',
      admin: { description: 'Tùy chỉnh tiêu đề, mô tả và thông báo trên trang /phac-do-dieu-tri.' },
      fields: [
        { name: 'eyebrow', label: 'Nhãn nhỏ (Eyebrow)', type: 'text', defaultValue: 'CHUYÊN MÔN LÂM SÀNG' },
        { name: 'title', label: 'Tiêu đề trang', type: 'text', defaultValue: 'Phác đồ Điều trị' },
        { name: 'description', label: 'Mô tả trang', type: 'textarea', defaultValue: 'Hệ thống phác đồ điều trị chuẩn được Ban Giám đốc và Hội đồng Khoa học thông qua, áp dụng thống nhất tại Bệnh viện Đa khoa Khu vực Thới Lai.' },
        { name: 'showNoticeBanner', label: 'Bật thông báo lưu ý đầu trang', type: 'checkbox', defaultValue: false },
        { name: 'noticeTitle', label: 'Tiêu đề thông báo', type: 'text', defaultValue: 'Lưu ý về phác đồ điều trị' },
        { name: 'noticeContent', label: 'Nội dung thông báo (Hỗ trợ Enter xuống dòng)', type: 'textarea', defaultValue: '• Phác đồ được cập nhật định kỳ theo hướng dẫn của Bộ Y tế và y văn quốc tế.\n• Áp dụng theo chỉ định của bác sĩ điều trị, không tự ý thay đổi.' },
        {
          name: 'noticeAlign',
          label: 'Canh lề thông báo',
          type: 'select',
          dbName: 'cp_not_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'showSearchBox',
          label: 'Hiển thị ô tìm kiếm phác đồ',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'showCategoryFilter',
          label: 'Hiển thị bộ lọc theo nhóm bệnh',
          type: 'checkbox',
          defaultValue: true,
        },
      ],
    },
    {
      name: 'websiteAssistant',
      label: 'Chatbot và nút lên đầu trang',
      type: 'group',
      admin: { description: 'Tùy chỉnh trợ lý hỗ trợ hiển thị ở góc phải trên toàn bộ website.' },
      fields: [
        { name: 'enabled', label: 'Hiển thị chatbot', type: 'checkbox', defaultValue: true },
        { name: 'backToTopEnabled', label: 'Hiển thị nút lên đầu trang', type: 'checkbox', defaultValue: true },
        { name: 'assistantLogo', label: 'Logo chatbot', type: 'upload', relationTo: 'media', admin: { description: 'Chọn logo đã tải trong thư viện. Để trống sẽ tự dùng Logo bệnh viện.' } },
        { name: 'assistantName', label: 'Tên chatbot', type: 'text', defaultValue: 'Trợ lý Thới Lai' },
        { name: 'statusText', label: 'Dòng trạng thái', type: 'text', defaultValue: 'Đang trực tuyến' },
        {
          name: 'greeting',
          label: 'Lời chào mở đầu',
          type: 'textarea',
          defaultValue: 'Xin chào! Tôi có thể giúp bạn tra cứu lịch khám, bảng giá, tiêm ngừa và thông tin bệnh viện.',
        },
        { name: 'inputPlaceholder', label: 'Chữ gợi ý trong ô nhập', type: 'text', defaultValue: 'Nhập nội dung cần hỏi…' },
        { name: 'noticeText', label: 'Dòng ghi chú cuối chatbot', type: 'text', defaultValue: 'Thông tin chỉ mang tính tham khảo. Trường hợp cấp cứu, vui lòng gọi bệnh viện ngay.' },
        colorField('primaryColor', 'Màu chính chatbot', '#0878D1', { admin: { description: 'Nhập mã màu, ví dụ: #0878D1' } }),
        {
          name: 'quickTopics',
          dbName: 'site_assistant_topics',
          label: 'Các nút hỏi nhanh',
          type: 'array',
          maxRows: 12,
          defaultValue: defaultQuickTopics,
          admin: { description: 'Thêm, xóa hoặc kéo thả để đổi thứ tự các nút hiển thị dưới nội dung trò chuyện.' },
          fields: [
            { name: 'label', label: 'Tên nút', type: 'text', required: true },
            { name: 'value', label: 'Câu hỏi gửi vào chatbot', type: 'text', required: true },
          ],
        },
        {
          name: 'customAnswers',
          dbName: 'site_assistant_answers',
          label: 'Kho câu hỏi và câu trả lời',
          type: 'array',
          maxRows: 100,
          defaultValue: defaultAssistantAnswers,
          admin: { description: 'Chatbot dò các từ khóa để chọn câu trả lời. Có thể thêm tối đa 100 nội dung và gắn liên kết riêng. Dùng {{HOTLINE}} hoặc {{MEDPRO_URL}} để tự lấy cấu hình website.' },
          fields: [
            { name: 'question', label: 'Câu hỏi mẫu / Tên nội dung', type: 'text', required: true },
            { name: 'keywords', label: 'Từ khóa nhận biết', type: 'textarea', required: true, admin: { description: 'Ngăn cách bằng dấu phẩy. Ví dụ: lịch khám, bác sĩ, chuyên khoa' } },
            { name: 'answer', label: 'Nội dung trả lời', type: 'textarea', required: true },
            { name: 'linkLabel', label: 'Tên nút liên kết', type: 'text', admin: { placeholder: 'Ví dụ: Xem chi tiết' } },
            { name: 'linkUrl', label: 'Đường dẫn liên kết', type: 'text', admin: { placeholder: '/lich-kham hoặc https://...' } },
            { name: 'openNewTab', label: 'Mở liên kết trong tab mới', type: 'checkbox', defaultValue: false },
          ],
        },
        { name: 'fallbackResponse', label: 'Câu trả lời khi không tìm thấy nội dung', type: 'textarea', defaultValue: 'Tôi chưa hiểu rõ câu hỏi. Bạn hãy chọn một mục gợi ý hoặc liên hệ trực tiếp với bệnh viện để được hỗ trợ.' },
        { name: 'fallbackLinkLabel', label: 'Tên nút của câu trả lời mặc định', type: 'text', defaultValue: 'Liên hệ bệnh viện' },
        { name: 'fallbackLinkUrl', label: 'Liên kết của câu trả lời mặc định', type: 'text', defaultValue: '/lien-he' },
      ],
    },
    {
      name: 'brand',
      label: 'Màu thương hiệu (cũ – không dùng)',
      type: 'group',
      admin: { hidden: true, description: 'Trường cũ, đã chuyển sang headerBrandAppearance. Ẩn để tránh nhầm lẫn.' },
      fields: [
        colorField('primaryColor', 'Màu chính', '#0878D1'),
        colorField('secondaryColor', 'Màu phụ', '#FFFFFF'),
      ],
    },
    {
      name: 'smtpSettings',
      label: '📧 Cấu hình Email gửi tự động (SMTP / Quên mật khẩu)',
      type: 'group',
      admin: {
        description: 'Tùy chỉnh hòm thư gửi tự động của hệ thống (Gửi thông báo, Quên mật khẩu). Bạn có thể đổi Gmail hoặc email tên miền tại đây.',
      },
      fields: [
        {
          name: 'enabled',
          label: 'Bật gửi email qua SMTP',
          type: 'checkbox',
          defaultValue: true,
          admin: { description: 'Bật để kích hoạt tính năng gửi mail tự động.' },
        },
        {
          type: 'row',
          fields: [
            {
              name: 'host',
              label: 'Máy chủ SMTP (Host)',
              type: 'text',
              defaultValue: 'smtp.gmail.com',
              admin: { width: '50%', placeholder: 'smtp.gmail.com' },
            },
            {
              name: 'port',
              label: 'Cổng kết nối (Port)',
              type: 'number',
              defaultValue: 465,
              admin: { width: '50%', description: '465 (SSL) hoặc 587 (TLS)' },
            },
          ],
        },
        {
          type: 'row',
          fields: [
            {
              name: 'user',
              label: 'Tài khoản Email gửi',
              type: 'text',
              defaultValue: 'leean170792@gmail.com',
              admin: { width: '50%', placeholder: 'bvdkthoilai@gmail.com' },
            },
            {
              name: 'pass',
              label: 'Mật khẩu ứng dụng (App Password)',
              type: 'text',
              defaultValue: 'mvdbzvsojuorpwgv',
              admin: { width: '50%', description: 'Mã 16 chữ cái tạo từ bảo mật Google.' },
            },
          ],
        },
        {
          type: 'row',
          fields: [
            {
              name: 'fromAddress',
              label: 'Địa chỉ Email người gửi hiển thị',
              type: 'text',
              defaultValue: 'leean170792@gmail.com',
              admin: { width: '50%', placeholder: 'leean170792@gmail.com' },
            },
            {
              name: 'fromName',
              label: 'Tên người gửi hiển thị',
              type: 'text',
              defaultValue: 'Bệnh viện Đa khoa Khu vực Thới Lai',
              admin: { width: '50%', placeholder: 'Bệnh viện Đa khoa Khu vực Thới Lai' },
            },
          ],
        },
      ],
    },
    {
      type: 'collapsible',
      label: '🔒 Bảo mật Tài liệu & Mã PIN Nội bộ',
      admin: {
        initCollapsed: true,
        description: 'Cấu hình mã PIN xác thực mặc định áp dụng chung cho toàn bộ Phác đồ điều trị và Văn bản lưu hành nội bộ.',
      },
      fields: [
        {
          name: 'defaultDocumentPin',
          label: 'Mã PIN bảo mật mặc định toàn viện',
          type: 'text',
          defaultValue: 'BVTL2026',
          admin: {
            description: 'Mã PIN này được dùng khi tài liệu chọn chế độ "Mã PIN bảo mật" nhưng không đặt mã PIN riêng. Cung cấp mã này cho Bác sĩ / Cán bộ nhân viên viện khi cần tải phác đồ.',
          },
        },
      ],
    },
  ],
}
