import type { GlobalConfig } from 'payload'
import { admins } from '@/access'

export const WorkingHoursSettings: GlobalConfig = {
  slug: 'working-hours-settings',
  label: 'Trang Lịch làm việc',
  admin: {
    group: '🏥 Khám bệnh & Dịch vụ Y tế',
    description: 'Quản lý toàn diện nội dung, giờ làm việc từng khoa phòng, các liên kết tab lịch khám và bật/tắt các ô chưa sử dụng trên trang /lich-lam-viec.',
  },
  access: { read: () => true, update: admins },
  fields: [
    // ── 1. BANNER HERO ĐẦU TRANG ──
    {
      name: 'hero',
      label: '1. Phần Banner đầu trang (Hero)',
      type: 'group',
      fields: [
        {
          name: 'badgeText',
          label: 'Nhãn nhỏ (Badge)',
          type: 'text',
          defaultValue: 'THÔNG BÁO CHÍNH THỨC TỪ BỆNH VIỆN',
        },
        {
          name: 'title',
          label: 'Tiêu đề chính',
          type: 'text',
          defaultValue: 'Thời gian Tiếp nhận & Khám chữa bệnh',
          required: true,
        },
        {
          name: 'titleSize',
          label: 'Cỡ chữ tiêu đề chính',
          type: 'select',
          defaultValue: 'default',
          options: [
            { label: 'Chuẩn (34px - 40px - Vừa vặn không bị rớt dòng chữ "bệnh")', value: 'default' },
            { label: 'Gọn gàng (28px - 32px)', value: 'compact' },
            { label: 'Lớn nổi bật (42px - 48px)', value: 'large' },
          ],
        },
        {
          name: 'titleColor',
          label: 'Màu chữ tiêu đề chính',
          type: 'select',
          defaultValue: 'white',
          options: [
            { label: 'Trắng tinh khiết (Mặc định)', value: 'white' },
            { label: 'Vàng nắng nổi bật (Golden Yellow)', value: 'yellow' },
            { label: 'Xanh ngọc sáng (Teal Glow)', value: 'cyan' },
          ],
        },
        {
          name: 'slogan',
          label: 'Mô tả / Khẩu hiệu (Hỗ trợ gõ Enter xuống dòng)',
          type: 'textarea',
          defaultValue: 'Nhằm nâng cao chất lượng phục vụ, tối ưu quy trình khám bệnh, rút ngắn thời gian chờ đợi và đáp ứng tốt hơn nhu cầu chăm sóc sức khỏe của người dân, Bệnh viện Đa khoa Khu vực Thới Lai điều chỉnh thời gian tiếp nhận từ 06:00 và bắt đầu khám bệnh từ 06:30.',
        },
        {
          name: 'bgType',
          label: 'Kiểu nền Banner Hero',
          type: 'select',
          defaultValue: 'gradient',
          options: [
            { label: 'Dải màu Gradient Y tế hiện đại (Mặc định)', value: 'gradient' },
            { label: 'Hình ảnh nền tùy chỉnh (Background Image)', value: 'image' },
            { label: 'Màu đơn sắc chuyên nghiệp (Solid Color)', value: 'solid' },
          ],
        },
        {
          name: 'bgGradient',
          label: 'Bộ tông màu Gradient nền (nếu chọn kiểu Gradient)',
          type: 'select',
          defaultValue: 'blue-teal',
          options: [
            { label: 'Xanh dương y tế sang Xanh ngọc (Blue - Teal) [Mặc định]', value: 'blue-teal' },
            { label: 'Xanh đại dương sâu thẳm (Deep Ocean Navy)', value: 'ocean-navy' },
            { label: 'Xanh ngọc bích sang Xanh lá dịu nhẹ (Teal - Emerald)', value: 'teal-emerald' },
            { label: 'Xanh hoàng gia trang trọng (Royal Blue)', value: 'royal-blue' },
            { label: 'Xám xanh công nghệ y tế (Slate Blue)', value: 'slate-blue' },
          ],
        },
        {
          name: 'bgImage',
          label: 'Hình ảnh nền Hero (nếu chọn kiểu Hình ảnh)',
          type: 'upload',
          relationTo: 'media',
          admin: {
            description: 'Tải lên hình ảnh khuôn viên bệnh viện, sảnh tiếp đón hoặc hoạt động khám chữa bệnh (khuyên dùng tỉ lệ 16:9 hoặc 21:9).',
          },
        },
        {
          name: 'overlayOpacity',
          label: 'Độ tối lớp phủ nền hình ảnh (Giúp chữ luôn nổi bật và sắc nét)',
          type: 'select',
          defaultValue: 'medium',
          options: [
            { label: 'Vừa phải (55% tối) [Khuyên dùng]', value: 'medium' },
            { label: 'Đậm nét (75% tối - Chữ siêu rõ)', value: 'dark' },
            { label: 'Nhẹ nhàng (35% tối)', value: 'light' },
          ],
        },
        {
          name: 'showPrimaryBtn',
          label: 'Hiển thị nút chính (Xem khung giờ)',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'primaryBtnText',
          label: 'Nút chính (Xem khung giờ)',
          type: 'text',
          defaultValue: 'Xem khung giờ khám mới',
        },
        {
          name: 'primaryBtnLink',
          label: 'Liên kết nút chính',
          type: 'text',
          defaultValue: '#kham-benh',
        },
        {
          name: 'showSecondaryBtn',
          label: 'Hiển thị nút phụ (Tra cứu lịch trực)',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'secondaryBtnText',
          label: 'Nút phụ (Tra cứu lịch trực)',
          type: 'text',
          defaultValue: 'Tra cứu lịch trực tuần & ca kíp',
        },
        {
          name: 'secondaryBtnLink',
          label: 'Liên kết nút phụ',
          type: 'text',
          defaultValue: '/lich-kham',
        },
      ],
    },

    // ── 1B. KHỐI THÔNG BÁO ĐIỀU CHỈNH THỜI GIAN KHÁM BỆNH (QUAN TRỌNG) ──
    {
      name: 'announcement',
      label: '1b. Khối Thông báo điều chỉnh giờ khám bệnh (Áp dụng từ 10/08/2026)',
      type: 'group',
      fields: [
        {
          name: 'enabled',
          label: 'Bật hiển thị thông báo này',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'badge',
          label: 'Nhãn thông báo',
          type: 'text',
          defaultValue: 'THÔNG BÁO ĐIỀU CHỈNH THỜI GIAN TIẾP NHẬN & KHÁM BỆNH',
        },
        {
          name: 'effectiveDate',
          label: 'Mốc thời gian áp dụng',
          type: 'text',
          defaultValue: 'Kể từ ngày 10 tháng 8 năm 2026',
        },
        {
          name: 'introText',
          label: 'Lời mở đầu thông báo',
          type: 'textarea',
          defaultValue: 'Nhằm nâng cao chất lượng phục vụ, tối ưu quy trình khám bệnh, rút ngắn thời gian chờ đợi và đáp ứng tốt hơn nhu cầu chăm sóc sức khỏe của người dân, kể từ ngày 10 tháng 8 năm 2026, Bệnh viện Đa khoa Khu vực Thới Lai điều chỉnh thời gian tiếp nhận và khám bệnh như sau:',
        },
        {
          name: 'milestones',
          label: 'Các mốc thời gian tiếp nhận & khám bệnh',
          type: 'array',
          dbName: 'wh_milestones',
          labels: { singular: 'Mốc giờ', plural: 'Các mốc giờ' },
          defaultValue: [
            {
              enabled: true,
              time: '06:00',
              title: 'Bắt đầu tiếp nhận người bệnh',
              desc: 'Phát số thứ tự tự động, tiếp nhận đăng ký khám BHYT và dịch vụ tại sảnh khoa Khám bệnh.',
              highlight: true,
            },
            {
              enabled: true,
              time: '06:30',
              title: 'Bác sĩ bắt đầu khám bệnh tại các khoa trọng điểm:',
              desc: '• Khoa Khám liên chuyên khoa\n• Khoa Ngoại – Phẫu thuật – Gây mê hồi sức\n• Khoa Sức khỏe sinh sản và Phụ sản',
              highlight: true,
            },
            {
              enabled: true,
              time: '07:00',
              title: 'Các phòng khám còn lại bắt đầu hoạt động bình thường:',
              desc: '• Phòng khám Y học cổ truyền\n• Phòng khám Bác sĩ gia đình\n• Phòng khám dịch vụ\n• Các phòng khám khác theo lịch hoạt động của bệnh viện',
              highlight: false,
            },
          ],
          fields: [
            { name: 'enabled', label: 'Bật hiển thị ô mốc giờ này', type: 'checkbox', defaultValue: true },
            { name: 'time', label: 'Khung giờ', type: 'text', required: true },
            { name: 'title', label: 'Tiêu đề mốc giờ', type: 'text', required: true },
            { name: 'desc', label: 'Danh sách khoa phòng / Nội dung', type: 'textarea' },
            { name: 'highlight', label: 'Nổi bật mốc giờ này', type: 'checkbox', defaultValue: false },
            {
              name: 'textAlign',
              label: 'Canh lề nội dung ô',
              type: 'select',
              dbName: 'wh_ms_align',
              defaultValue: 'left',
              options: [
                { label: 'Canh trái (Mặc định)', value: 'left' },
                { label: 'Canh giữa', value: 'center' },
                { label: 'Canh phải', value: 'right' },
                { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
              ],
            },
            {
              name: 'titleColor',
              label: 'Màu chữ tiêu đề',
              type: 'select',
              dbName: 'wh_ms_tcolor',
              defaultValue: 'default',
              options: [
                { label: 'Mặc định (Đen đậm y tế)', value: 'default' },
                { label: 'Xanh lá y tế (Medical Green)', value: 'green' },
                { label: 'Xanh dương đậm (Navy)', value: 'navy' },
                { label: 'Đỏ đậm (Emergency Red)', value: 'red' },
              ],
            },
            {
              name: 'titleSize',
              label: 'Cỡ chữ tiêu đề',
              type: 'select',
              dbName: 'wh_ms_tsize',
              defaultValue: 'normal',
              options: [
                { label: 'Tiêu chuẩn (16px)', value: 'normal' },
                { label: 'Lớn (18px)', value: 'large' },
                { label: 'Rất lớn (20px)', value: 'xlarge' },
              ],
            },
            {
              name: 'descColor',
              label: 'Màu chữ danh sách / nội dung',
              type: 'select',
              dbName: 'wh_ms_dcolor',
              defaultValue: 'default',
              options: [
                { label: 'Mặc định (Xám đậm chuẩn)', value: 'default' },
                { label: 'Đen đậm rõ nét', value: 'black' },
                { label: 'Xanh dương đậm (Navy)', value: 'navy' },
              ],
            },
            {
              name: 'descSize',
              label: 'Cỡ chữ danh sách / nội dung',
              type: 'select',
              dbName: 'wh_ms_dsize',
              defaultValue: 'normal',
              options: [
                { label: 'Tiêu chuẩn (14px)', value: 'normal' },
                { label: 'Lớn dễ đọc (15.5px)', value: 'large' },
              ],
            },
          ],
        },
        {
          name: 'closingText',
          label: 'Lời kết / Kêu gọi chia sẻ',
          type: 'textarea',
          defaultValue: 'Bệnh viện Đa khoa Khu vực Thới Lai trân trọng thông báo để quý bà con chủ động sắp xếp thời gian đến khám, chữa bệnh. Kính mong quý bà con chia sẻ thông tin để nhiều người cùng biết.',
        },
      ],
    },

    // ── 2. KHỐI CẤP CỨU THƯỜNG TRỰC 24/7 ──
    {
      name: 'emergencyBanner',
      label: '2. Khối Cấp cứu thường trực 24/7',
      type: 'group',
      fields: [
        {
          name: 'enabled',
          label: 'Hiển thị khối Cấp cứu 24/7',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'textAlign',
          label: 'Canh lề nội dung banner cấp cứu',
          type: 'select',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'title',
          label: 'Tiêu đề Cấp cứu',
          type: 'text',
          defaultValue: 'KHOA CẤP CỨU HOẠT ĐỘNG 24/24 (24/7)',
        },
        {
          name: 'titleSize',
          label: 'Cỡ chữ tiêu đề Cấp cứu',
          type: 'select',
          defaultValue: 'normal',
          options: [
            { label: 'Tiêu chuẩn (18px)', value: 'normal' },
            { label: 'Lớn nổi bật (21px)', value: 'large' },
            { label: 'Rất lớn (24px)', value: 'xlarge' },
          ],
        },
        {
          name: 'description',
          label: 'Mô tả chi tiết (Tự động giữ nguyên xuống dòng)',
          type: 'textarea',
          defaultValue: 'Tiếp nhận, xử trí cấp cứu mọi trường hợp khẩn cấp liên tục tất cả các ngày trong tuần, thứ Bảy, Chủ Nhật và ngày Lễ.',
        },
        {
          name: 'descSize',
          label: 'Cỡ chữ mô tả',
          type: 'select',
          defaultValue: 'normal',
          options: [
            { label: 'Tiêu chuẩn (14px)', value: 'normal' },
            { label: 'Lớn dễ đọc (16px)', value: 'large' },
          ],
        },
        {
          name: 'hotline',
          label: 'Số điện thoại Hotline Cấp cứu',
          type: 'text',
          defaultValue: '0292 3686 115',
        },
        {
          name: 'buttonLabel',
          label: 'Nhãn nút bấm gọi',
          type: 'text',
          defaultValue: 'HOTLINE CẤP CỨU: 0292 3686 115',
        },
      ],
    },

    // ── 3. DANH SÁCH CÁC Ô KHUNG GIỜ LÀM VIỆC (CÓ THỂ BẬT/TẮT, THÊM MỚI, CHỈNH ICON) ──
    {
      name: 'departments',
      label: '3. Danh sách các Ô khung giờ làm việc theo Khoa / Bộ phận',
      type: 'array',
      dbName: 'wh_depts',
      labels: { singular: 'Ô khung giờ', plural: 'Các ô khung giờ' },
      admin: {
        description: 'Tùy chỉnh bật/tắt (enabled), chỉnh sửa nội dung, thêm ô mới hoặc sắp xếp thứ tự hiển thị.',
      },
      defaultValue: [
        {
          enabled: true,
          title: 'Quầy Tiếp đón & Đăng ký khám',
          subtitle: 'Khu vực phát số tự động & làm thủ tục khám BHYT, Viện phí',
          iconType: 'card',
          customIconText: '💳',
          badgeColor: 'blue',
          timeRows: [
            { label: 'Bắt đầu tiếp nhận:', value: 'Từ 06:00 sáng', highlight: true },
            { label: 'Giờ phục vụ buổi sáng:', value: '06:00 – 11:30', highlight: true },
            { label: 'Giờ phục vụ buổi chiều:', value: '13:00 – 17:00', highlight: false },
            { label: 'Tiếp đón cấp cứu:', value: 'Thường trực 24/24', highlight: false },
          ],
          note: 'Phát số thứ tự tự động từ 06:00. Có quầy ưu tiên cho người cao tuổi, người khuyết tật, phụ nữ mang thai và trẻ nhỏ.',
        },
        {
          enabled: true,
          title: 'Nhóm Khoa Bác sĩ khám sớm (06:30)',
          subtitle: 'Khám sớm nhằm giải tỏa nhanh lượng bệnh nhân đầu ngày',
          iconType: 'stethoscope',
          customIconText: '🩺',
          badgeColor: 'teal',
          timeRows: [
            { label: 'Khoa Khám liên chuyên khoa:', value: 'Từ 06:30 sáng', highlight: true },
            { label: 'Ngoại – Phẫu thuật – GMHS:', value: 'Từ 06:30 sáng', highlight: true },
            { label: 'Sức khỏe sinh sản & Phụ sản:', value: 'Từ 06:30 sáng', highlight: true },
            { label: 'Buổi chiều:', value: '13:00 – 17:00', highlight: false },
          ],
          note: '3 khoa chuyên môn chủ lực bắt đầu khám bệnh từ 06:30 giúp bà con ở xa không phải chờ lâu.',
        },
        {
          enabled: true,
          title: 'Các Phòng khám còn lại (07:00)',
          subtitle: 'Bắt đầu hoạt động bình thường theo lịch bệnh viện',
          iconType: 'calendar',
          customIconText: '🏥',
          badgeColor: 'blue',
          timeRows: [
            { label: 'Phòng khám Y học cổ truyền:', value: 'Từ 07:00 sáng', highlight: true },
            { label: 'Phòng khám Bác sĩ gia đình:', value: 'Từ 07:00 sáng', highlight: true },
            { label: 'Phòng khám dịch vụ & PK khác:', value: 'Từ 07:00 sáng', highlight: true },
            { label: 'Buổi chiều:', value: '13:00 – 17:00', highlight: false },
          ],
          note: 'Áp dụng cho tất cả các phòng khám chuyên khoa nội, nhi, chuyên khoa lẻ theo lịch tuần.',
        },
        {
          enabled: true,
          title: 'Xét nghiệm, X-Quang, Siêu âm',
          subtitle: 'Khoa Cận Lâm Sàng & Chẩn đoán hình ảnh',
          iconType: 'flask',
          customIconText: '🔬',
          badgeColor: 'blue',
          timeRows: [
            { label: 'Lấy mẫu xét nghiệm sớm:', value: 'Từ 06:00 sáng', highlight: true },
            { label: 'Chụp X-Quang & Siêu âm:', value: 'Từ 06:30 sáng', highlight: true },
            { label: 'Phục vụ ca cấp cứu:', value: 'Thường trực 24/24', highlight: true },
          ],
          note: 'Người bệnh cần xét nghiệm máu nên đi sớm và nhịn ăn sáng để kết quả chuẩn xác.',
        },
        {
          enabled: true,
          title: 'Khám Thứ Bảy & Ngoài giờ',
          subtitle: 'Tạo thuận lợi cho người dân bận rộn trong tuần',
          iconType: 'calendar',
          customIconText: '📅',
          badgeColor: 'amber',
          timeRows: [
            { label: 'Khám sáng Thứ Bảy:', value: '07:00 – 11:30', highlight: true },
            { label: 'Khám Ngoài giờ:', value: 'Theo thông báo', highlight: false },
            { label: 'Chủ Nhật & Ngày Lễ:', value: 'Trực Cấp cứu 24/24', highlight: false },
          ],
          note: 'Người bệnh có thể liên hệ tổng đài hoặc đăng ký trực tuyến để giảm thời gian chờ đợi.',
        },
        {
          enabled: true,
          title: 'Phòng Tiêm chủng Vắc xin',
          subtitle: 'Tiêm chủng mở rộng & Tiêm chủng dịch vụ',
          iconType: 'syringe',
          customIconText: '💉',
          badgeColor: 'teal',
          timeRows: [
            { label: 'Buổi sáng:', value: '07:30 – 11:00', highlight: true },
            { label: 'Buổi chiều:', value: '13:30 – 16:30', highlight: true },
            { label: 'Lịch tiêm:', value: 'Theo kế hoạch', highlight: false },
          ],
          note: 'Có khám sàng lọc và tư vấn kỹ lưỡng trước tiêm bởi bác sĩ chuyên khoa.',
        },
        {
          enabled: true,
          title: 'Khu Hành chính & Nghiệp vụ',
          subtitle: 'Giải quyết thủ tục, hồ sơ bệnh án & viện phí',
          iconType: 'building',
          customIconText: '🏢',
          badgeColor: 'blue',
          timeRows: [
            { label: 'Thứ Hai đến Thứ Sáu:', value: '07:00 – 11:30 & 13:00 – 17:00', highlight: false },
            { label: 'Thứ Bảy, Chủ Nhật:', value: 'Nghỉ hành chính', highlight: false },
          ],
          note: 'Giải quyết công văn, giấy tờ hành chính, bảo hiểm y tế và thủ tục hành chính.',
        },
      ],
      fields: [
        {
          name: 'enabled',
          label: 'Bật hiển thị ô này',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'title',
          label: 'Tên Khoa / Dịch vụ',
          type: 'text',
          required: true,
        },
        {
          name: 'subtitle',
          label: 'Mô tả phụ / Phạm vi tiếp nhận',
          type: 'text',
        },
        {
          name: 'iconType',
          label: 'Loại biểu tượng (Icon SVG chuẩn)',
          type: 'select',
          dbName: 'wh_dept_icon',
          defaultValue: 'stethoscope',
          options: [
            { label: 'Ống nghe y tế (stethoscope)', value: 'stethoscope' },
            { label: 'Lịch / Ngày khám (calendar)', value: 'calendar' },
            { label: 'Ống tiêm vắc xin (syringe)', value: 'syringe' },
            { label: 'Ống nghiệm / Cận lâm sàng (flask)', value: 'flask' },
            { label: 'Thẻ / Quầy thu viện phí (card)', value: 'card' },
            { label: 'Tòa nhà / Phòng ban (building)', value: 'building' },
            { label: 'Cấp cứu / Trái tim (heart)', value: 'heart' },
            { label: 'Đồng hồ thời gian (clock)', value: 'clock' },
            { label: 'Biểu tượng tùy chỉnh (Emoji/Text)', value: 'custom' },
          ],
        },
        {
          name: 'customIconText',
          label: 'Biểu tượng Emoji tùy chỉnh (nếu chọn loại biểu tượng tùy chỉnh)',
          type: 'text',
          admin: {
            placeholder: 'Ví dụ: 🩺, 🏥, 💉, ⏰...',
          },
        },
        {
          name: 'badgeColor',
          label: 'Tông màu nền biểu tượng',
          type: 'select',
          dbName: 'wh_dept_badge_color',
          defaultValue: 'blue',
          options: [
            { label: 'Xanh dương y tế (Blue)', value: 'blue' },
            { label: 'Xanh ngọc (Teal)', value: 'teal' },
            { label: 'Vàng cam (Amber)', value: 'amber' },
            { label: 'Đỏ khẩn cấp (Red)', value: 'red' },
            { label: 'Xanh lá (Emerald)', value: 'emerald' },
          ],
        },
        {
          name: 'timeRows',
          label: 'Các dòng thời gian chi tiết',
          type: 'array',
          dbName: 'wh_dept_rows',
          labels: { singular: 'Dòng thời gian', plural: 'Các dòng thời gian' },
          fields: [
            { name: 'label', label: 'Tên ca / Thời điểm', type: 'text', required: true },
            { name: 'value', label: 'Khung giờ', type: 'text', required: true },
            { name: 'highlight', label: 'Làm nổi bật (Nền xanh sáng)', type: 'checkbox', defaultValue: false },
          ],
        },
        {
          name: 'textAlign',
          label: 'Canh lề nội dung ô',
          type: 'select',
          dbName: 'wh_dept_align',
          defaultValue: 'left',
          options: [
            { label: 'Canh trái (Mặc định)', value: 'left' },
            { label: 'Canh giữa', value: 'center' },
            { label: 'Canh phải', value: 'right' },
            { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
          ],
        },
        {
          name: 'titleColor',
          label: 'Màu chữ tiêu đề',
          type: 'select',
          dbName: 'wh_dept_tcolor',
          defaultValue: 'default',
          options: [
            { label: 'Mặc định (Đen đậm y tế)', value: 'default' },
            { label: 'Xanh dương đậm (Navy)', value: 'navy' },
            { label: 'Xanh y tế (Primary Blue)', value: 'blue' },
            { label: 'Xanh lá đậm (Forest Green)', value: 'green' },
            { label: 'Đỏ đậm (Emergency Red)', value: 'red' },
            { label: 'Xám đậm (Slate)', value: 'slate' },
          ],
        },
        {
          name: 'titleSize',
          label: 'Cỡ chữ tiêu đề',
          type: 'select',
          dbName: 'wh_dept_tsize',
          defaultValue: 'normal',
          options: [
            { label: 'Nhỏ vừa (15px)', value: 'small' },
            { label: 'Tiêu chuẩn (17px)', value: 'normal' },
            { label: 'Lớn (19px)', value: 'large' },
            { label: 'Rất lớn (21px)', value: 'xlarge' },
          ],
        },
        {
          name: 'note',
          label: 'Ghi chú thêm ở chân ô (Tự động giữ nguyên xuống dòng)',
          type: 'textarea',
          admin: {
            placeholder: 'Nội dung ghi chú hoặc lưu ý. Có thể gõ Enter để xuống dòng theo ý muốn.',
          },
        },
        {
          name: 'noteColor',
          label: 'Màu chữ ghi chú chân ô',
          type: 'select',
          dbName: 'wh_dept_ncolor',
          defaultValue: 'default',
          options: [
            { label: 'Mặc định (Xám đậm chuẩn)', value: 'default' },
            { label: 'Xanh dương đậm (Navy)', value: 'navy' },
            { label: 'Xanh lá y tế (Green)', value: 'green' },
            { label: 'Đỏ lưu ý đặc biệt', value: 'red' },
          ],
        },
        {
          name: 'noteSize',
          label: 'Cỡ chữ ghi chú chân ô',
          type: 'select',
          dbName: 'wh_dept_nsize',
          defaultValue: 'normal',
          options: [
            { label: 'Tiêu chuẩn (12.5px)', value: 'normal' },
            { label: 'Lớn dễ đọc (14px)', value: 'large' },
          ],
        },
      ],
    },

    // ── 4. LIÊN KẾT ĐIỀU HƯỚNG CÁC TAB LỊCH KHÁM ──
    {
      name: 'scheduleLinksSection',
      label: '4. Khối liên kết điều hướng sang các Tab Lịch khám',
      type: 'group',
      fields: [
        {
          name: 'enabled',
          label: 'Hiển thị khối liên kết',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'title',
          label: 'Tiêu đề khối liên kết',
          type: 'text',
          defaultValue: 'Tra cứu Lịch phân công & Trực theo từng chuyên mục',
        },
        {
          name: 'description',
          label: 'Mô tả hướng dẫn',
          type: 'textarea',
          defaultValue: 'Chọn ngay liên kết tương ứng bên dưới để chuyển trực tiếp đến đúng Tab hiển thị trên hệ thống lịch của bệnh viện:',
        },
        {
          name: 'links',
          label: 'Danh sách các liên kết tab',
          type: 'array',
          dbName: 'wh_sched_links',
          labels: { singular: 'Thẻ liên kết', plural: 'Các thẻ liên kết' },
          defaultValue: [
            {
              enabled: true,
              title: 'Khối Lịch khám Trang chủ',
              subtitle: 'Mục section lịch khám tổng hợp',
              url: '/#schedules',
              iconType: 'home',
              isEmergency: false,
            },
            {
              enabled: true,
              title: 'Tab Lịch theo tuần',
              subtitle: 'Lịch trực tuần & ma trận phân công',
              url: '/#schedules?tab=weekly',
              iconType: 'calendar',
              isEmergency: false,
            },
            {
              enabled: true,
              title: 'Tab Lịch theo ngày',
              subtitle: 'Phân công bác sĩ trực tiếp theo ca',
              url: '/#schedules?tab=daily',
              iconType: 'clock',
              isEmergency: false,
            },
            {
              enabled: true,
              title: 'Tab Lịch đính kèm',
              subtitle: 'Bản ảnh chụp / tệp Excel lịch trực',
              url: '/#schedules?tab=attachments',
              iconType: 'paperclip',
              isEmergency: false,
            },
            {
              enabled: true,
              title: 'Trang Lịch trực cấp cứu 24/24',
              subtitle: 'Xem danh sách lịch trực cấp cứu mới nhất',
              url: '/lich-kham?type=emergency',
              iconType: 'ambulance',
              isEmergency: true,
            },
            {
              enabled: true,
              title: 'Trang Lịch khám bệnh tuần',
              subtitle: 'Bộ lọc chuyên mục Lịch khám theo tuần',
              url: '/lich-kham?type=weekly',
              iconType: 'fileText',
              isEmergency: false,
            },
          ],
          fields: [
            { name: 'enabled', label: 'Bật liên kết', type: 'checkbox', defaultValue: true },
            { name: 'title', label: 'Tên liên kết', type: 'text', required: true },
            { name: 'subtitle', label: 'Mô tả phụ', type: 'text' },
            { name: 'url', label: 'Đường dẫn (URL / Hash)', type: 'text', required: true },
            {
              name: 'iconType',
              label: 'Biểu tượng',
              type: 'select',
              dbName: 'wh_link_icon',
              defaultValue: 'calendar',
              options: [
                { label: 'Trang chủ (home)', value: 'home' },
                { label: 'Lịch tuần (calendar)', value: 'calendar' },
                { label: 'Đồng hồ (clock)', value: 'clock' },
                { label: 'Tệp đính kèm (paperclip)', value: 'paperclip' },
                { label: 'Xe cấp cứu (ambulance)', value: 'ambulance' },
                { label: 'Tài liệu (fileText)', value: 'fileText' },
              ],
            },
            { name: 'isEmergency', label: 'Tông màu cảnh báo Cấp cứu (đỏ)', type: 'checkbox', defaultValue: false },
            {
              name: 'textAlign',
              label: 'Canh lề thẻ liên kết',
              type: 'select',
              dbName: 'wh_link_align',
              defaultValue: 'left',
              options: [
                { label: 'Canh trái (Mặc định)', value: 'left' },
                { label: 'Canh giữa', value: 'center' },
              ],
            },
            {
              name: 'titleColor',
              label: 'Màu chữ liên kết',
              type: 'select',
              dbName: 'wh_link_tcolor',
              defaultValue: 'default',
              options: [
                { label: 'Mặc định (Đen đậm)', value: 'default' },
                { label: 'Xanh dương y tế (Primary Blue)', value: 'blue' },
                { label: 'Xanh dương đậm (Navy)', value: 'navy' },
                { label: 'Đỏ nổi bật (Red)', value: 'red' },
              ],
            },
            {
              name: 'titleSize',
              label: 'Cỡ chữ liên kết',
              type: 'select',
              dbName: 'wh_link_tsize',
              defaultValue: 'normal',
              options: [
                { label: 'Tiêu chuẩn (14.5px)', value: 'normal' },
                { label: 'Lớn dễ nhìn (16px)', value: 'large' },
              ],
            },
          ],
        },
      ],
    },

    // ── 5. KHỐI LƯU Ý DÀNH CHO NGƯỜI BỆNH ──
    {
      name: 'notesSection',
      label: '5. Khối Lưu ý dành cho người bệnh và thân nhân',
      type: 'group',
      fields: [
        {
          name: 'enabled',
          label: 'Hiển thị khối Lưu ý',
          type: 'checkbox',
          defaultValue: true,
        },
        {
          name: 'title',
          label: 'Tiêu đề khối Lưu ý',
          type: 'text',
          defaultValue: 'LƯU Ý DÀNH CHO NGƯỜI BỆNH VÀ THÂN NHÂN',
        },
        {
          name: 'items',
          label: 'Các dòng lưu ý',
          type: 'array',
          dbName: 'wh_notes',
          labels: { singular: 'Lưu ý', plural: 'Các lưu ý' },
          defaultValue: [
            {
              enabled: true,
              boldPrefix: 'Giấy tờ cần mang theo:',
              content: 'Căn cước công dân gắn chip (hoặc ứng dụng VNeID mức 2 tích hợp thẻ BHYT), thẻ BHYT giấy (nếu chưa tích hợp), sổ khám bệnh và các đơn thuốc/kết quả xét nghiệm cũ (nếu có).',
            },
            {
              enabled: true,
              boldPrefix: 'Lưu ý trước khi làm xét nghiệm máu:',
              content: 'Người bệnh nên nhịn ăn sáng (có thể uống ít nước lọc) để đảm bảo độ chính xác cho các chỉ số đường huyết, mỡ máu, chức năng gan thận.',
            },
            {
              enabled: true,
              boldPrefix: 'Hỗ trợ & Hướng dẫn:',
              content: 'Luôn có nhân viên Chăm sóc khách hàng và Đoàn viên thanh niên trực tiếp hỗ trợ tại sảnh chính tiếp đón bệnh nhân. Đường dây nóng bệnh viện sẵn sàng giải đáp.',
            },
          ],
          fields: [
            { name: 'enabled', label: 'Bật hiển thị dòng lưu ý này', type: 'checkbox', defaultValue: true },
            { name: 'boldPrefix', label: 'Tiêu đề in đậm đầu dòng', type: 'text' },
            { name: 'content', label: 'Nội dung chi tiết (Tự động giữ nguyên xuống dòng)', type: 'textarea', required: true },
            {
              name: 'textAlign',
              label: 'Canh lề dòng lưu ý',
              type: 'select',
              dbName: 'wh_note_align',
              defaultValue: 'left',
              options: [
                { label: 'Canh trái (Mặc định)', value: 'left' },
                { label: 'Canh đều 2 bên (Justify)', value: 'justify' },
              ],
            },
            {
              name: 'textColor',
              label: 'Màu chữ',
              type: 'select',
              dbName: 'wh_note_tcolor',
              defaultValue: 'default',
              options: [
                { label: 'Mặc định (Xám đậm êm dịu)', value: 'default' },
                { label: 'Đen đậm rõ nét', value: 'black' },
                { label: 'Xanh dương đậm (Navy)', value: 'navy' },
                { label: 'Đỏ lưu ý đặc biệt', value: 'red' },
              ],
            },
            {
              name: 'textSize',
              label: 'Cỡ chữ',
              type: 'select',
              dbName: 'wh_note_tsize',
              defaultValue: 'normal',
              options: [
                { label: 'Tiêu chuẩn (14px)', value: 'normal' },
                { label: 'Lớn dễ đọc (16px)', value: 'large' },
              ],
            },
          ],
        },
      ],
    },
  ],
}
