/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    notices: Notice;
    procurement: Procurement;
    documents: Document;
    departments: Department;
    doctors: Doctor;
    schedules: Schedule;
    services: Service;
    vaccinations: Vaccination;
    recruitment: Recruitment;
    pages: Page;
    feedback: Feedback;
    consultations: Consultation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    notices: NoticesSelect<false> | NoticesSelect<true>;
    procurement: ProcurementSelect<false> | ProcurementSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    schedules: SchedulesSelect<false> | SchedulesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    vaccinations: VaccinationsSelect<false> | VaccinationsSelect<true>;
    recruitment: RecruitmentSelect<false> | RecruitmentSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    consultations: ConsultationsSelect<false> | ConsultationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    homepage: Homepage;
    'organization-chart': OrganizationChart;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'organization-chart': OrganizationChartSelect<false> | OrganizationChartSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'admin' | 'editor' | 'reviewer' | 'procurement' | 'department-manager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Kho dùng chung cho toàn website. Ảnh và tệp tải lên một lần có thể chọn lại ở logo, banner, bài viết, lịch khám, tiêm ngừa và các mục khác.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    article?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Đăng và quản lý tin tức, hoạt động và kiến thức sức khỏe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Tự động tạo từ Tiêu đề.
   */
  slug: string;
  excerpt?: string | null;
  /**
   * Tải ảnh mới hoặc chọn lại ảnh đã có trong Thư viện Tệp & Hình ảnh.
   */
  cover?: (number | null) | Media;
  /**
   * Hỗ trợ đậm, nghiêng, gạch chân, tiêu đề, cỡ chữ, căn trái/giữa/phải/đều, danh sách, liên kết, bảng, ảnh và tệp.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Có thể nhập chuyên mục mới. Dùng cùng một tên để bài viết hiển thị chung trong một tab.
   */
  category: string;
  attachments?:
    | {
        /**
         * Website tự động sử dụng tên và định dạng của tệp đã tải lên.
         */
        label?: string | null;
        /**
         * Chọn “Tạo mới” để tải tệp lên hoặc “Chọn từ thư viện” để dùng lại tệp đã có.
         */
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  pinned?: boolean | null;
  publishedAt?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Có thể tải ảnh mới hoặc chọn lại ảnh đã có trong Thư viện Tệp & Hình ảnh.
   */
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices".
 */
export interface Notice {
  id: number;
  title: string;
  /**
   * Tự động tạo từ Tiêu đề.
   */
  slug: string;
  /**
   * Ảnh hiển thị trên trang chủ và trang danh sách. Có thể tải mới hoặc chọn lại từ Thư viện Tệp & Hình ảnh.
   */
  cover?: (number | null) | Media;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  level?: ('normal' | 'important' | 'urgent') | null;
  attachments?:
    | {
        /**
         * Website tự động sử dụng tên và định dạng của tệp đã tải lên.
         */
        label?: string | null;
        /**
         * Chọn “Tạo mới” để tải tệp lên hoặc “Chọn từ thư viện” để dùng lại tệp đã có.
         */
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  startAt?: string | null;
  expireAt?: string | null;
  pinned?: boolean | null;
  showOnHome?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Có thể tải ảnh mới hoặc chọn lại ảnh đã có trong Thư viện Tệp & Hình ảnh.
   */
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procurement".
 */
export interface Procurement {
  id: number;
  title: string;
  /**
   * Tự động tạo từ Tiêu đề.
   */
  slug: string;
  /**
   * Ảnh hiển thị trên trang chủ và trang danh sách. Có thể tải mới hoặc chọn lại từ Thư viện Tệp & Hình ảnh.
   */
  cover?: (number | null) | Media;
  excerpt?: string | null;
  referenceCode?: string | null;
  type:
    | 'Thông báo mời thầu'
    | 'Kế hoạch lựa chọn nhà thầu'
    | 'Yêu cầu báo giá'
    | 'Mua sắm'
    | 'Kết quả lựa chọn nhà thầu'
    | 'Đính chính';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  deadlineAt?: string | null;
  procurementStatus?: ('open' | 'closing' | 'closed' | 'cancelled') | null;
  contactUnit?: string | null;
  contactInfo?: string | null;
  attachments?:
    | {
        /**
         * Website tự động sử dụng tên và định dạng của tệp đã tải lên.
         */
        label?: string | null;
        /**
         * Chọn “Tạo mới” để tải tệp lên hoặc “Chọn từ thư viện” để dùng lại tệp đã có.
         */
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  changeLog?:
    | {
        date: string;
        note: string;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Có thể tải ảnh mới hoặc chọn lại ảnh đã có trong Thư viện Tệp & Hình ảnh.
   */
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  number?: string | null;
  /**
   * Có thể tự nhập loại tài liệu mới.
   */
  category?: string | null;
  issuedAt?: string | null;
  year?: number | null;
  /**
   * Tải tệp mới hoặc chọn lại tệp đã có trong Thư viện Tệp & Hình ảnh.
   */
  file: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  name: string;
  /**
   * Có thể tự nhập tên nhóm mới. Nhập đúng cùng một tên để các khoa/phòng được gom vào cùng một tab.
   */
  kind: string;
  /**
   * Tự động tạo từ Tên.
   */
  slug: string;
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  leader?: string | null;
  phone?: string | null;
  location?: string | null;
  /**
   * Tải ảnh mới hoặc chọn lại từ Thư viện Tệp & Hình ảnh.
   */
  cover?: (number | null) | Media;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Có thể tải ảnh mới hoặc chọn lại ảnh đã có trong Thư viện Tệp & Hình ảnh.
   */
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  name: string;
  /**
   * Tự động tạo từ Tên.
   */
  slug: string;
  title?: string | null;
  degree?: string | null;
  /**
   * Tải ảnh mới hoặc chọn lại từ Thư viện Tệp & Hình ảnh.
   */
  avatar?: (number | null) | Media;
  department: number | Department;
  specialty?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  experience?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  education?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Có thể tải ảnh mới hoặc chọn lại ảnh đã có trong Thư viện Tệp & Hình ảnh.
   */
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tạo lịch theo ngày, lập bảng lịch theo tuần hoặc đăng lịch bằng ảnh / tệp đính kèm.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export interface Schedule {
  id: number;
  title: string;
  /**
   * Hiển thị ở thẻ danh sách trước khi người xem bấm Xem chi tiết.
   */
  summary?: string | null;
  /**
   * Dùng cho mọi loại lịch. Có thể tải mới hoặc chọn lại ảnh đã có trong thư viện.
   */
  coverImage?: (number | null) | Media;
  /**
   * Nội dung chỉ hiển thị trong trang chi tiết của lịch.
   */
  detailContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mode: 'daily' | 'weekly' | 'attachment';
  doctor?: (number | null) | Doctor;
  department?: (number | null) | Department;
  date?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  room?: string | null;
  weekStart?: string | null;
  weekEnd?: string | null;
  /**
   * Bấm Thêm để chọn sẵn thứ, bác sĩ, khoa và khung giờ.
   */
  weeklySlots?:
    | {
        dayOfWeek: '2' | '3' | '4' | '5' | '6' | '7' | '8';
        doctor: number | Doctor;
        department: number | Department;
        startTime: string;
        endTime: string;
        room?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tải ảnh JPG/PNG mới hoặc chọn lại ảnh lịch đã có trong thư viện.
   */
  scheduleImage?: (number | null) | Media;
  /**
   * Tải Excel/PDF/Word mới hoặc chọn lại tệp lịch đã có trong thư viện.
   */
  scheduleFile?: (number | null) | Media;
  validFrom?: string | null;
  validTo?: string | null;
  note?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Thêm từng dịch vụ hoặc dùng khung nhập Excel ngay phía trên danh sách.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  sequence?: number | null;
  code: string;
  name: string;
  category?: string | null;
  insurancePrice?: number | null;
  price?: number | null;
  note?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quản lý thông báo lịch tiêm chung, các đợt tiêm và danh mục vắc xin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vaccinations".
 */
export interface Vaccination {
  id: number;
  entryType: 'announcement' | 'campaign' | 'vaccine';
  vaccineName: string;
  summary?: string | null;
  announcementContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tải ảnh mới hoặc chọn lại ảnh đã có trong thư viện.
   */
  announcementImage?: (number | null) | Media;
  /**
   * Tải tệp mới hoặc chọn lại tệp đã có trong thư viện.
   */
  announcementFile?: (number | null) | Media;
  /**
   * Tải ảnh mới hoặc chọn lại ảnh đã có trong thư viện.
   */
  campaignImage?: (number | null) | Media;
  target?: string | null;
  date?: string | null;
  endDate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  location?: string | null;
  manufacturer?: string | null;
  origin?: string | null;
  prevents?: string | null;
  ageGroup?: string | null;
  /**
   * Tải ảnh mới hoặc chọn lại ảnh đã có trong thư viện.
   */
  vaccineImage?: (number | null) | Media;
  /**
   * Nội dung chỉ hiện khi người xem bấm Xem chi tiết.
   */
  detailContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  availability?: ('available' | 'coming' | 'unavailable') | null;
  fee?: number | null;
  note?: string | null;
  registrationUrl?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment".
 */
export interface Recruitment {
  id: number;
  title: string;
  /**
   * Tự động tạo từ Tiêu đề.
   */
  slug: string;
  department?: (number | null) | Department;
  quantity?: number | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  deadlineAt?: string | null;
  /**
   * Tải tệp mới hoặc chọn lại tệp đã có trong Thư viện Tệp & Hình ảnh.
   */
  attachment?: (number | null) | Media;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Có thể tải ảnh mới hoặc chọn lại ảnh đã có trong Thư viện Tệp & Hình ảnh.
   */
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Tự động tạo từ Tiêu đề.
   */
  slug: string;
  layout?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Tải ảnh mới hoặc chọn lại ảnh đã có trong thư viện.
             */
            image: number | Media;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            images?:
              | {
                  /**
                   * Tải ảnh mới hoặc chọn lại ảnh đã có trong thư viện.
                   */
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            items?:
              | {
                  label?: string | null;
                  /**
                   * Tải tệp mới hoặc chọn lại tệp đã có trong thư viện.
                   */
                  file: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'downloads';
          }
      )[]
    | null;
  attachments?:
    | {
        /**
         * Website tự động sử dụng tên và định dạng của tệp đã tải lên.
         */
        label?: string | null;
        /**
         * Chọn “Tạo mới” để tải tệp lên hoặc “Chọn từ thư viện” để dùng lại tệp đã có.
         */
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Có thể tải ảnh mới hoặc chọn lại ảnh đã có trong Thư viện Tệp & Hình ảnh.
   */
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  type: 'Góp ý' | 'Khen ngợi' | 'Khiếu nại' | 'Khác';
  message: string;
  status?: ('new' | 'processing' | 'done') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations".
 */
export interface Consultation {
  id: number;
  publicToken: string;
  question: string;
  status: 'new' | 'processing' | 'answered' | 'closed';
  /**
   * Nhập câu trả lời và bấm Lưu. Người dùng đang mở chatbot sẽ nhận được nội dung tự động.
   */
  staffReply?: string | null;
  answeredAt?: string | null;
  /**
   * Không hiển thị cho người dùng.
   */
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'notices';
        value: number | Notice;
      } | null)
    | ({
        relationTo: 'procurement';
        value: number | Procurement;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'schedules';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'vaccinations';
        value: number | Vaccination;
      } | null)
    | ({
        relationTo: 'recruitment';
        value: number | Recruitment;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'consultations';
        value: number | Consultation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        article?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  category?: T;
  attachments?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  featured?: T;
  pinned?: T;
  publishedAt?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices_select".
 */
export interface NoticesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  level?: T;
  attachments?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  startAt?: T;
  expireAt?: T;
  pinned?: T;
  showOnHome?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procurement_select".
 */
export interface ProcurementSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  excerpt?: T;
  referenceCode?: T;
  type?: T;
  content?: T;
  publishedAt?: T;
  deadlineAt?: T;
  procurementStatus?: T;
  contactUnit?: T;
  contactInfo?: T;
  attachments?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  changeLog?:
    | T
    | {
        date?: T;
        note?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  number?: T;
  category?: T;
  issuedAt?: T;
  year?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  slug?: T;
  summary?: T;
  content?: T;
  leader?: T;
  phone?: T;
  location?: T;
  cover?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  degree?: T;
  avatar?: T;
  department?: T;
  specialty?: T;
  bio?: T;
  experience?: T;
  education?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules_select".
 */
export interface SchedulesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  coverImage?: T;
  detailContent?: T;
  mode?: T;
  doctor?: T;
  department?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  room?: T;
  weekStart?: T;
  weekEnd?: T;
  weeklySlots?:
    | T
    | {
        dayOfWeek?: T;
        doctor?: T;
        department?: T;
        startTime?: T;
        endTime?: T;
        room?: T;
        note?: T;
        id?: T;
      };
  scheduleImage?: T;
  scheduleFile?: T;
  validFrom?: T;
  validTo?: T;
  note?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  sequence?: T;
  code?: T;
  name?: T;
  category?: T;
  insurancePrice?: T;
  price?: T;
  note?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vaccinations_select".
 */
export interface VaccinationsSelect<T extends boolean = true> {
  entryType?: T;
  vaccineName?: T;
  summary?: T;
  announcementContent?: T;
  announcementImage?: T;
  announcementFile?: T;
  campaignImage?: T;
  target?: T;
  date?: T;
  endDate?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  manufacturer?: T;
  origin?: T;
  prevents?: T;
  ageGroup?: T;
  vaccineImage?: T;
  detailContent?: T;
  availability?: T;
  fee?: T;
  note?: T;
  registrationUrl?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment_select".
 */
export interface RecruitmentSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  department?: T;
  quantity?: T;
  content?: T;
  deadlineAt?: T;
  attachment?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              image?: T;
              content?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        downloads?:
          | T
          | {
              items?:
                | T
                | {
                    label?: T;
                    file?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  attachments?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  type?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations_select".
 */
export interface ConsultationsSelect<T extends boolean = true> {
  publicToken?: T;
  question?: T;
  status?: T;
  staffReply?: T;
  answeredAt?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  hospitalName: string;
  /**
   * Thay đổi kích thước nhận diện bệnh viện trên thanh menu đầu trang.
   */
  headerBrandAppearance?: {
    logoSize?: number | null;
    titleFontSize?: number | null;
    subtitleFontSize?: number | null;
    /**
     * Nhập mã màu, ví dụ: #FFFFFF
     */
    headerBackgroundColor?: string | null;
    /**
     * Nhập mã màu, ví dụ: #FFFFFF
     */
    logoBackgroundColor?: string | null;
    /**
     * Nhập mã màu, ví dụ: #143653
     */
    titleColor?: string | null;
    /**
     * Nhập mã màu, ví dụ: #0878D1
     */
    subtitleColor?: string | null;
  };
  /**
   * Nội dung này chạy ngang ngay dưới menu. Để trống sẽ dùng thông báo đặt khám mặc định của bệnh viện.
   */
  slogan?: string | null;
  tickerAppearance?: {
    enabled?: boolean | null;
    /**
     * Nhập mã màu, ví dụ: #FF9F2F
     */
    backgroundColor?: string | null;
    /**
     * Nhập mã màu, ví dụ: #FFFFFF
     */
    textColor?: string | null;
    fontSize?: number | null;
    /**
     * Số nhỏ chạy nhanh hơn; số lớn chạy chậm hơn.
     */
    duration?: number | null;
  };
  /**
   * Tải logo mới hoặc chọn lại logo đã có trong Thư viện Tệp & Hình ảnh.
   */
  logo?: (number | null) | Media;
  /**
   * Tải banner mới hoặc chọn lại banner đã có trong thư viện. Nếu chưa chọn, website dùng banner có sẵn trong hệ thống.
   */
  headerBanner?: (number | null) | Media;
  /**
   * Nên dùng 1300 px. Ảnh banner tải lên nên có đúng kích thước 1300 × 200 px.
   */
  headerBannerWidth?: number | null;
  /**
   * Nên dùng 200 px để khớp banner chuẩn 1300 × 200 px.
   */
  headerBannerHeight?: number | null;
  /**
   * Tải mới hoặc chọn lại hình đã có trong Thư viện Tệp & Hình ảnh.
   */
  favicon?: (number | null) | Media;
  hotline?: string | null;
  emergencyHotline?: string | null;
  email?: string | null;
  address?: string | null;
  workingHours?: string | null;
  medproUrl?: string | null;
  zaloUrl?: string | null;
  facebookUrl?: string | null;
  youtubeUrl?: string | null;
  /**
   * Dán toàn bộ mã <iframe> hoặc URL nhúng Google Maps (URL có /embed hoặc output=embed). Để trống, website tự hiển thị bản đồ theo Địa chỉ ở trên.
   */
  googleMapsEmbed?: string | null;
  footerText?: string | null;
  /**
   * Tùy chỉnh tiêu đề, ô tìm kiếm và số dịch vụ hiển thị trên mỗi trang.
   */
  servicePricePage: {
    title?: string | null;
    description?: string | null;
    searchPlaceholder?: string | null;
    rowsPerPage: '40' | '50';
    searchNotes?: boolean | null;
    emptyText?: string | null;
  };
  /**
   * Tùy chỉnh trợ lý hỗ trợ hiển thị ở góc phải trên toàn bộ website.
   */
  websiteAssistant?: {
    enabled?: boolean | null;
    backToTopEnabled?: boolean | null;
    /**
     * Chọn logo đã tải trong thư viện. Để trống sẽ tự dùng Logo bệnh viện.
     */
    assistantLogo?: (number | null) | Media;
    assistantName?: string | null;
    statusText?: string | null;
    greeting?: string | null;
    inputPlaceholder?: string | null;
    noticeText?: string | null;
    /**
     * Nhập mã màu, ví dụ: #0878D1
     */
    primaryColor?: string | null;
    /**
     * Thêm, xóa hoặc kéo thả để đổi thứ tự các nút hiển thị dưới nội dung trò chuyện.
     */
    quickTopics?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Chatbot dò các từ khóa để chọn câu trả lời. Có thể thêm tối đa 100 nội dung và gắn liên kết riêng. Dùng {{HOTLINE}} hoặc {{MEDPRO_URL}} để tự lấy cấu hình website.
     */
    customAnswers?:
      | {
          question: string;
          /**
           * Ngăn cách bằng dấu phẩy. Ví dụ: lịch khám, bác sĩ, chuyên khoa
           */
          keywords: string;
          answer: string;
          linkLabel?: string | null;
          linkUrl?: string | null;
          openNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    fallbackResponse?: string | null;
    fallbackLinkLabel?: string | null;
    fallbackLinkUrl?: string | null;
  };
  brand?: {
    primaryColor?: string | null;
    secondaryColor?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Mỗi menu và menu con có thể gắn cả một mục website (Tin tức, Thông báo, Lịch khám…), một bài cụ thể hoặc một liên kết bên ngoài.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Thêm, xóa hoặc kéo thả để sắp xếp. Mỗi dòng có thể gắn cả mục website hoặc một bài cụ thể.
   */
  items?:
    | {
        label: string;
        /**
         * Ví dụ: chọn “Gắn cả mục” để menu Thông báo mở toàn bộ mục Thông báo, không phải một bài thông báo.
         */
        linkType: 'preset' | 'reference' | 'url' | 'custom';
        /**
         * Chỉ dùng khi mục cần gắn chưa có trong danh sách mục website.
         */
        url?: string | null;
        /**
         * Chọn một mục để khi bấm menu sẽ mở toàn bộ danh sách nội dung của mục đó.
         */
        preset?:
          | (
              | '/'
              | '/gioi-thieu'
              | '/so-do-to-chuc'
              | '/don-vi'
              | '/bac-si'
              | '/tin-tuc'
              | '/thong-bao'
              | '/lich-kham'
              | '/bang-gia'
              | '/tiem-chung'
              | '/dau-thau-mua-sam'
              | '/van-ban'
              | '/tuyen-dung'
              | '/trang/kham-bhyt'
              | '/lien-he'
            )
          | null;
        /**
         * Tùy chọn này chỉ mở một bài cụ thể. Nếu muốn mở cả mục Tin tức hoặc Thông báo, hãy chọn “Gắn cả mục của website”.
         */
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'news';
              value: number | News;
            } | null)
          | ({
              relationTo: 'notices';
              value: number | Notice;
            } | null)
          | ({
              relationTo: 'procurement';
              value: number | Procurement;
            } | null)
          | ({
              relationTo: 'departments';
              value: number | Department;
            } | null)
          | ({
              relationTo: 'doctors';
              value: number | Doctor;
            } | null);
        customUrl?: string | null;
        openInNewTab?: boolean | null;
        visible?: boolean | null;
        children?:
          | {
              label: string;
              /**
               * Ví dụ: chọn “Gắn cả mục” để menu Thông báo mở toàn bộ mục Thông báo, không phải một bài thông báo.
               */
              linkType: 'preset' | 'reference' | 'url' | 'custom';
              /**
               * Chỉ dùng khi mục cần gắn chưa có trong danh sách mục website.
               */
              url?: string | null;
              /**
               * Chọn một mục để khi bấm menu sẽ mở toàn bộ danh sách nội dung của mục đó.
               */
              preset?:
                | (
                    | '/'
                    | '/gioi-thieu'
                    | '/so-do-to-chuc'
                    | '/don-vi'
                    | '/bac-si'
                    | '/tin-tuc'
                    | '/thong-bao'
                    | '/lich-kham'
                    | '/bang-gia'
                    | '/tiem-chung'
                    | '/dau-thau-mua-sam'
                    | '/van-ban'
                    | '/tuyen-dung'
                    | '/trang/kham-bhyt'
                    | '/lien-he'
                  )
                | null;
              /**
               * Tùy chọn này chỉ mở một bài cụ thể. Nếu muốn mở cả mục Tin tức hoặc Thông báo, hãy chọn “Gắn cả mục của website”.
               */
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'news';
                    value: number | News;
                  } | null)
                | ({
                    relationTo: 'notices';
                    value: number | Notice;
                  } | null)
                | ({
                    relationTo: 'procurement';
                    value: number | Procurement;
                  } | null)
                | ({
                    relationTo: 'departments';
                    value: number | Department;
                  } | null)
                | ({
                    relationTo: 'doctors';
                    value: number | Doctor;
                  } | null);
              customUrl?: string | null;
              openInNewTab?: boolean | null;
              visible?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Quản lý banner, nội dung, thứ tự, màu sắc và cỡ chữ của các mục trên trang chủ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Tải ảnh mới hoặc chọn lại từ Thư viện Tệp & Hình ảnh.
     */
    desktopImage?: (number | null) | Media;
    /**
     * Tải ảnh mới hoặc chọn lại từ Thư viện Tệp & Hình ảnh.
     */
    mobileImage?: (number | null) | Media;
  };
  /**
   * Thêm nhiều banner và kéo thả để đổi thứ tự. Website tự chuyển lần lượt theo số giây cấu hình bên dưới. Ảnh có thể tải mới hoặc chọn lại từ Thư viện Tệp & Hình ảnh.
   */
  banners?:
    | {
        eyebrow: string;
        title: string;
        description?: string | null;
        /**
         * Tải banner mới hoặc chọn lại banner đã có trong thư viện.
         */
        desktopImage?: (number | null) | Media;
        /**
         * Không bắt buộc. Tải mới hoặc chọn lại ảnh mobile đã có trong thư viện.
         */
        mobileImage?: (number | null) | Media;
        buttonLabel?: string | null;
        buttonUrl?: string | null;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Bỏ dấu chọn để ẩn toàn bộ banner dưới menu. Các banner đã nhập vẫn được giữ nguyên để bật lại sau.
   */
  showHeroBanners?: boolean | null;
  /**
   * Khuyên dùng 5–7 giây. Chỉ áp dụng khi có từ 2 banner đang hiển thị.
   */
  bannerAutoplaySeconds?: number | null;
  /**
   * Quản lý các ô: Đặt khám chuyên khoa, theo bác sĩ, BHYT, xét nghiệm, tiêm chủng, bảng giá… Có thể kéo thả để đổi thứ tự; xóa một hàng để ẩn.
   */
  quickLinks?:
    | {
        title: string;
        description?: string | null;
        url: string;
        icon?: ('calendar' | 'doctor' | 'price' | 'insurance' | 'hospital' | 'map' | 'phone' | 'document') | null;
        id?: string | null;
      }[]
    | null;
  intro?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Tải ảnh mới hoặc chọn lại từ Thư viện Tệp & Hình ảnh.
     */
    image?: (number | null) | Media;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Kéo thả để sắp xếp thứ tự. Có thể đổi nội dung, màu sắc, cỡ chữ, màu nền hoặc tắt từng mục.
   */
  sections?:
    | {
        type:
          | 'featured-news'
          | 'news-portal'
          | 'organization'
          | 'notices'
          | 'schedules'
          | 'vaccinations'
          | 'procurement'
          | 'science'
          | 'introduction'
          | 'documents'
          | 'custom';
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        visible?: boolean | null;
        /**
         * Thêm, xóa hoặc kéo thả để sắp xếp tab. Tên tab, chuyên mục và nội dung thủ công đều có thể tự nhập; hàng để trống sẽ được bỏ qua khi hiển thị.
         */
        contentTabs?:
          | {
              label?: string | null;
              values?:
                | {
                    value?: string | null;
                    id?: string | null;
                  }[]
                | null;
              manualItems?:
                | {
                    title?: string | null;
                    description?: string | null;
                    url?: string | null;
                    image?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Tự nhập tên tab và tên nhóm đơn vị. Có thể thêm nội dung thủ công; hàng trống không làm lỗi khi lưu.
         */
        departmentTabs?:
          | {
              label?: string | null;
              values?:
                | {
                    value?: string | null;
                    id?: string | null;
                  }[]
                | null;
              manualItems?:
                | {
                    title?: string | null;
                    description?: string | null;
                    url?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Kéo thả để đổi vị trí; bỏ dấu Hiển thị nếu muốn ẩn một tab.
         */
        scheduleTabOrder?:
          | {
              label?: string | null;
              tab?: ('attachments' | 'daily' | 'weekly') | null;
              visible?: boolean | null;
              manualItems?:
                | {
                    title?: string | null;
                    description?: string | null;
                    url?: string | null;
                    image?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Kéo thả để đổi thứ tự; có thể tắt từng tab khi chưa cần hiển thị.
         */
        vaccinationTabOrder?:
          | {
              label?: string | null;
              tab?: ('announcements' | 'campaigns' | 'vaccines') | null;
              visible?: boolean | null;
              manualItems?:
                | {
                    title?: string | null;
                    description?: string | null;
                    url?: string | null;
                    image?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Soạn nội dung hiển thị trực tiếp trên trang chủ.
         */
        customContent?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Tải ảnh mới hoặc chọn lại từ Thư viện Tệp & Hình ảnh.
         */
        customImage?: (number | null) | Media;
        imagePosition?: ('left' | 'right' | 'top') | null;
        buttonLabel?: string | null;
        buttonUrl?: string | null;
        eyebrowColor?: string | null;
        titleColor?: string | null;
        descriptionColor?: string | null;
        backgroundColor?: string | null;
        eyebrowSize?: number | null;
        titleSize?: number | null;
        descriptionSize?: number | null;
        paddingTop?: number | null;
        paddingBottom?: number | null;
        contentWidth?: number | null;
        headingGap?: number | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Quản lý sơ đồ 3 tầng: Giám đốc, 3 Phó Giám đốc và 4 Phòng – 9 Khoa.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-chart".
 */
export interface OrganizationChart {
  id: number;
  pageTitle: string;
  description?: string | null;
  director: {
    name: string;
    title: string;
    /**
     * Có thể tải ảnh mới hoặc chọn lại ảnh đã có trong thư viện.
     */
    photo?: (number | null) | Media;
    responsibility?: string | null;
  };
  /**
   * Có thể nhập từ 1 đến 3 Phó Giám đốc. Trang chỉ hiển thị những người đã nhập họ tên; kéo thả để đổi vị trí.
   */
  deputyDirectors?:
    | {
        name: string;
        title: string;
        /**
         * Có thể tải ảnh mới hoặc chọn lại ảnh đã có trong thư viện.
         */
        photo?: (number | null) | Media;
        responsibility?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Chọn đúng 4 Phòng; kéo thả để đổi thứ tự.
   */
  offices?:
    | {
        unit: number | Department;
        id?: string | null;
      }[]
    | null;
  /**
   * Chọn đúng 9 Khoa; kéo thả để đổi thứ tự.
   */
  departments?:
    | {
        unit: number | Department;
        id?: string | null;
      }[]
    | null;
  appearance?: {
    primaryColor?: string | null;
    directorColor?: string | null;
    deputyColor?: string | null;
    officeColor?: string | null;
    departmentColor?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  hospitalName?: T;
  headerBrandAppearance?:
    | T
    | {
        logoSize?: T;
        titleFontSize?: T;
        subtitleFontSize?: T;
        headerBackgroundColor?: T;
        logoBackgroundColor?: T;
        titleColor?: T;
        subtitleColor?: T;
      };
  slogan?: T;
  tickerAppearance?:
    | T
    | {
        enabled?: T;
        backgroundColor?: T;
        textColor?: T;
        fontSize?: T;
        duration?: T;
      };
  logo?: T;
  headerBanner?: T;
  headerBannerWidth?: T;
  headerBannerHeight?: T;
  favicon?: T;
  hotline?: T;
  emergencyHotline?: T;
  email?: T;
  address?: T;
  workingHours?: T;
  medproUrl?: T;
  zaloUrl?: T;
  facebookUrl?: T;
  youtubeUrl?: T;
  googleMapsEmbed?: T;
  footerText?: T;
  servicePricePage?:
    | T
    | {
        title?: T;
        description?: T;
        searchPlaceholder?: T;
        rowsPerPage?: T;
        searchNotes?: T;
        emptyText?: T;
      };
  websiteAssistant?:
    | T
    | {
        enabled?: T;
        backToTopEnabled?: T;
        assistantLogo?: T;
        assistantName?: T;
        statusText?: T;
        greeting?: T;
        inputPlaceholder?: T;
        noticeText?: T;
        primaryColor?: T;
        quickTopics?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        customAnswers?:
          | T
          | {
              question?: T;
              keywords?: T;
              answer?: T;
              linkLabel?: T;
              linkUrl?: T;
              openNewTab?: T;
              id?: T;
            };
        fallbackResponse?: T;
        fallbackLinkLabel?: T;
        fallbackLinkUrl?: T;
      };
  brand?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        linkType?: T;
        url?: T;
        preset?: T;
        reference?: T;
        customUrl?: T;
        openInNewTab?: T;
        visible?: T;
        children?:
          | T
          | {
              label?: T;
              linkType?: T;
              url?: T;
              preset?: T;
              reference?: T;
              customUrl?: T;
              openInNewTab?: T;
              visible?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        desktopImage?: T;
        mobileImage?: T;
      };
  banners?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        desktopImage?: T;
        mobileImage?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        visible?: T;
        id?: T;
      };
  showHeroBanners?: T;
  bannerAutoplaySeconds?: T;
  quickLinks?:
    | T
    | {
        title?: T;
        description?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  intro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        type?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        visible?: T;
        contentTabs?:
          | T
          | {
              label?: T;
              values?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              manualItems?:
                | T
                | {
                    title?: T;
                    description?: T;
                    url?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
        departmentTabs?:
          | T
          | {
              label?: T;
              values?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              manualItems?:
                | T
                | {
                    title?: T;
                    description?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
        scheduleTabOrder?:
          | T
          | {
              label?: T;
              tab?: T;
              visible?: T;
              manualItems?:
                | T
                | {
                    title?: T;
                    description?: T;
                    url?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
        vaccinationTabOrder?:
          | T
          | {
              label?: T;
              tab?: T;
              visible?: T;
              manualItems?:
                | T
                | {
                    title?: T;
                    description?: T;
                    url?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
        customContent?: T;
        customImage?: T;
        imagePosition?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        eyebrowColor?: T;
        titleColor?: T;
        descriptionColor?: T;
        backgroundColor?: T;
        eyebrowSize?: T;
        titleSize?: T;
        descriptionSize?: T;
        paddingTop?: T;
        paddingBottom?: T;
        contentWidth?: T;
        headingGap?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-chart_select".
 */
export interface OrganizationChartSelect<T extends boolean = true> {
  pageTitle?: T;
  description?: T;
  director?:
    | T
    | {
        name?: T;
        title?: T;
        photo?: T;
        responsibility?: T;
      };
  deputyDirectors?:
    | T
    | {
        name?: T;
        title?: T;
        photo?: T;
        responsibility?: T;
        id?: T;
      };
  offices?:
    | T
    | {
        unit?: T;
        id?: T;
      };
  departments?:
    | T
    | {
        unit?: T;
        id?: T;
      };
  appearance?:
    | T
    | {
        primaryColor?: T;
        directorColor?: T;
        deputyColor?: T;
        officeColor?: T;
        departmentColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}